/-
Copyright (c) 2026 BEI-lean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import BEI.Radical
import BEI.PrimeDecomposition

/-!
# CI Ideals — Section 4, Binary Output Case

We formalize the connection between conditional independence (CI) ideals
and binomial edge ideals from Section 4 of Herzog et al. (2010),
restricted to the case of binary output (d_0 = 2).

Given random variables X_0 (binary), X_1, ..., X_N, the elementary
probabilities p_{a,w} (a in {1,2}, w in Omega = X_{[N]}) form a
2 x |Omega| matrix. The 2x2 minors p_{1,w}p_{2,w'} - p_{1,w'}p_{2,w}
are exactly the binomial edge generators x_w y_{w'} - x_{w'} y_w under
the identification p_{1,w} <-> x_w, p_{2,w} <-> y_w.

## Main definitions

* `CIStatement` -- a single binary-output CI statement, bundling a
  conditioning type and projection.
* `ciGraph` -- graph on Omega for a single CI statement.
* `ciIdeal` -- CI ideal for a single CI statement.
* `ciGraphSpec` -- union graph for a family of CI statements
  (robustness specification).
* `ciIdealSpec` -- CI ideal for the full specification.

## Main results

* `ciIdeal_single_eq_binomialEdgeIdeal` -- single-statement bridge.
* `ciIdealSpec_eq_binomialEdgeIdeal` -- specification-level bridge.
* `ciIdealSpec_isRadical` -- the CI ideal of a robustness specification
  is radical (transferred from Corollary 2.2).
* `ciIdealSpec_primeDecomposition` -- prime decomposition of the CI
  ideal (transferred from Theorem 3.2).
-/

variable {K : Type*} [Field K]
variable {Ω : Type*} [LinearOrder Ω]
variable {α : Type*}
variable {ι : Type*}

noncomputable section

open MvPolynomial

/-! ## Single CI statement -/

/-- The graph associated to a single CI statement `X_0 _|_ X_S | X_T`
with binary output. Two states `w, w' in Omega` are adjacent iff they
agree on the conditioning variables (`proj w = proj w'`) and are
distinct. Here `proj` is the projection onto the T-coordinates. -/
def ciGraph (proj : Ω → α) : SimpleGraph Ω where
  Adj ω ω' := proj ω = proj ω' ∧ ω ≠ ω'
  symm := fun {_ _} ⟨h, hne⟩ => ⟨h.symm, hne.symm⟩
  loopless := ⟨fun _ ⟨_, hne⟩ => hne rfl⟩

omit [LinearOrder Ω] in
@[simp]
theorem ciGraph_adj (proj : Ω → α) (ω ω' : Ω) :
    (ciGraph proj).Adj ω ω' ↔ proj ω = proj ω' ∧ ω ≠ ω' :=
  Iff.rfl

/-- The CI ideal for a single binary-output CI statement `X_0 _|_ X_S | X_T`.
Generated by 2x2 minors `x_w * y_{w'} - x_{w'} * y_w` for all
pairs `(w, w')` agreeing on the conditioning projection. -/
def ciIdeal (proj : Ω → α) : Ideal (MvPolynomial (BinomialEdgeVars Ω) K) :=
  Ideal.span { f | ∃ ω ω' : Ω, proj ω = proj ω' ∧ ω ≠ ω' ∧
    f = x ω * y ω' - x ω' * y ω }

/-- **Single-statement bridge theorem** (Section 4, Herzog et al.):
the CI ideal of a binary-output CI statement `X_0 _|_ X_S | X_T` equals
the binomial edge ideal of the associated CI graph. -/
theorem ciIdeal_single_eq_binomialEdgeIdeal (proj : Ω → α) :
    (ciIdeal proj : Ideal (MvPolynomial (BinomialEdgeVars Ω) K)) =
    binomialEdgeIdeal (ciGraph proj) := by
  apply le_antisymm
  · -- CI generators ⊆ BEI ideal
    apply Ideal.span_le.mpr
    rintro _ ⟨ω, ω', hproj, hne, rfl⟩
    rcases lt_or_gt_of_ne hne with h | h
    · -- ω < ω': directly a BEI generator
      apply Ideal.subset_span
      exact ⟨ω, ω', ⟨hproj, hne⟩, h, rfl⟩
    · -- ω' < ω: negative of a BEI generator
      have hmem : (x ω' : MvPolynomial (BinomialEdgeVars Ω) K) * y ω - x ω * y ω' ∈
          binomialEdgeIdeal (ciGraph proj) := by
        apply Ideal.subset_span
        exact ⟨ω', ω, ⟨hproj.symm, hne.symm⟩, h, rfl⟩
      have : (x ω : MvPolynomial (BinomialEdgeVars Ω) K) * y ω' - x ω' * y ω =
          -(x ω' * y ω - x ω * y ω') := by ring
      rw [this]
      exact neg_mem hmem
  · -- BEI generators ⊆ CI ideal
    apply Ideal.span_le.mpr
    rintro _ ⟨i, j, hadj, _, rfl⟩
    apply Ideal.subset_span
    exact ⟨i, j, hadj.1, hadj.2, rfl⟩

/-! ## Robustness specification -/

/-- A single binary-output CI statement: a conditioning projection
`proj : Omega -> alpha` where `alpha` is the type of conditioning values.
A robustness specification is a finite family `stmt : iota -> CIStatement Omega`. -/
structure CIStatement (Ω : Type*) where
  /-- The type of conditioning values. -/
  α : Type*
  /-- The projection onto the conditioning coordinates. -/
  proj : Ω → α

/-- The graph associated to a robustness specification (family of
binary-output CI statements). Two states are adjacent iff some statement
in the family assigns them the same conditioning value. -/
def ciGraphSpec (stmt : ι → CIStatement Ω) : SimpleGraph Ω where
  Adj ω ω' := ∃ i, (stmt i).proj ω = (stmt i).proj ω' ∧ ω ≠ ω'
  symm := fun {_ _} ⟨i, h, hne⟩ => ⟨i, h.symm, hne.symm⟩
  loopless := ⟨fun _ ⟨_, _, hne⟩ => hne rfl⟩

omit [LinearOrder Ω] in
@[simp]
theorem ciGraphSpec_adj (stmt : ι → CIStatement Ω) (ω ω' : Ω) :
    (ciGraphSpec stmt).Adj ω ω' ↔
    ∃ i, (stmt i).proj ω = (stmt i).proj ω' ∧ ω ≠ ω' :=
  Iff.rfl

/-- The CI ideal of a robustness specification with binary output.
Generated by all 2x2 minors from all statements in the family. -/
def ciIdealSpec (stmt : ι → CIStatement Ω) : Ideal (MvPolynomial (BinomialEdgeVars Ω) K) :=
  Ideal.span { f | ∃ (i : ι) (ω ω' : Ω), (stmt i).proj ω = (stmt i).proj ω' ∧ ω ≠ ω' ∧
    f = x ω * y ω' - x ω' * y ω }

/-- **Specification-level bridge theorem** (Section 4, Herzog et al.):
the CI ideal of a binary-output robustness specification equals the
binomial edge ideal of the union graph `ciGraphSpec`. -/
theorem ciIdealSpec_eq_binomialEdgeIdeal (stmt : ι → CIStatement Ω) :
    (ciIdealSpec stmt : Ideal (MvPolynomial (BinomialEdgeVars Ω) K)) =
    binomialEdgeIdeal (ciGraphSpec stmt) := by
  apply le_antisymm
  · -- CI generators ⊆ BEI ideal
    apply Ideal.span_le.mpr
    rintro _ ⟨i, ω, ω', hproj, hne, rfl⟩
    rcases lt_or_gt_of_ne hne with h | h
    · -- ω < ω': directly a BEI generator
      apply Ideal.subset_span
      exact ⟨ω, ω', ⟨i, hproj, hne⟩, h, rfl⟩
    · -- ω' < ω: negative of a BEI generator
      have hmem : (x ω' : MvPolynomial (BinomialEdgeVars Ω) K) * y ω - x ω * y ω' ∈
          binomialEdgeIdeal (ciGraphSpec stmt) := by
        apply Ideal.subset_span
        exact ⟨ω', ω, ⟨i, hproj.symm, hne.symm⟩, h, rfl⟩
      have : (x ω : MvPolynomial (BinomialEdgeVars Ω) K) * y ω' - x ω' * y ω =
          -(x ω' * y ω - x ω * y ω') := by ring
      rw [this]
      exact neg_mem hmem
  · -- BEI generators ⊆ CI ideal
    apply Ideal.span_le.mpr
    rintro _ ⟨ω, ω', hadj, _, rfl⟩
    obtain ⟨i, hproj, hne⟩ := hadj
    apply Ideal.subset_span
    exact ⟨i, ω, ω', hproj, hne, rfl⟩

/-! ## Downstream consequences -/

/-- The CI ideal of a robustness specification is radical.
Transferred from Corollary 2.2 via the bridge theorem. -/
theorem ciIdealSpec_isRadical [Finite Ω] (stmt : ι → CIStatement Ω) :
    (ciIdealSpec stmt : Ideal (MvPolynomial (BinomialEdgeVars Ω) K)).IsRadical := by
  cases nonempty_fintype Ω
  rw [ciIdealSpec_eq_binomialEdgeIdeal]
  exact corollary_2_2 (ciGraphSpec stmt)

/-- Prime decomposition of the CI ideal of a robustness specification.
Transferred from Theorem 3.2 via the bridge theorem. -/
theorem ciIdealSpec_primeDecomposition [Finite Ω] (stmt : ι → CIStatement Ω) :
    (ciIdealSpec stmt : Ideal (MvPolynomial (BinomialEdgeVars Ω) K)) =
    ⨅ S : Finset Ω, primeComponent (K := K) (ciGraphSpec stmt) S := by
  cases nonempty_fintype Ω
  rw [ciIdealSpec_eq_binomialEdgeIdeal]
  exact theorem_3_2 (ciGraphSpec stmt)
