/-
Copyright (c) 2026 BEI-lean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import BEI.Definitions

/-!
# CI Ideals — Section 4, Binary Output Case

We formalize the connection between conditional independence (CI) ideals
and binomial edge ideals from Section 4 of Herzog et al. (2010),
restricted to the case of binary output (d₀ = 2).

Given random variables X₀ (binary), X₁, ..., X_N, the elementary
probabilities p_{a,w} (a in {1,2}, w in Omega = X_{[N]}) form a
2 x |Omega| matrix. The 2x2 minors p_{1,w}p_{2,w'} - p_{1,w'}p_{2,w}
are exactly the binomial edge generators x_w y_{w'} - x_{w'} y_w under
the identification p_{1,w} <-> x_w, p_{2,w} <-> y_w.

## Main definitions

* `ciGraph` -- graph on Omega whose edges connect states with the same
  projection (same conditioning value).
* `ciIdeal` -- CI ideal generated by all such 2x2 minors.

## Main results

* `ciIdeal_single_eq_binomialEdgeIdeal` -- the CI ideal of a single
  statement X_0 _|_ X_S | X_T equals the binomial edge ideal of `ciGraph`.
-/

variable {K : Type*} [Field K]
variable {Ω : Type*} [LinearOrder Ω]
variable {α : Type*}

noncomputable section

open MvPolynomial

/-- The graph associated to a single CI statement `X₀ ⊥ X_S | X_T`
with binary output. Two states `ω, ω' ∈ Ω` are adjacent iff they
agree on the conditioning variables (`proj ω = proj ω'`) and are
distinct. Here `proj` is the projection onto the T-coordinates. -/
def ciGraph (proj : Ω → α) : SimpleGraph Ω where
  Adj ω ω' := proj ω = proj ω' ∧ ω ≠ ω'
  symm := fun {_ _} ⟨h, hne⟩ => ⟨h.symm, hne.symm⟩
  loopless := ⟨fun _ ⟨_, hne⟩ => hne rfl⟩

omit [LinearOrder Ω] in
@[simp]
theorem ciGraph_adj (proj : Ω → α) (ω ω' : Ω) :
    (ciGraph proj).Adj ω ω' ↔ proj ω = proj ω' ∧ ω ≠ ω' :=
  Iff.rfl

/-- The CI ideal for a single binary-output CI statement `X₀ ⊥ X_S | X_T`.
Generated by 2×2 minors `x_ω · y_{ω'} − x_{ω'} · y_ω` for all
pairs `(ω, ω')` agreeing on the conditioning projection. -/
def ciIdeal (proj : Ω → α) : Ideal (MvPolynomial (BinomialEdgeVars Ω) K) :=
  Ideal.span { f | ∃ ω ω' : Ω, proj ω = proj ω' ∧ ω ≠ ω' ∧
    f = x ω * y ω' - x ω' * y ω }

/-- **Single-statement bridge theorem** (Section 4, Herzog et al.):
the CI ideal of a binary-output CI statement `X₀ ⊥ X_S | X_T` equals
the binomial edge ideal of the associated CI graph. -/
theorem ciIdeal_single_eq_binomialEdgeIdeal (proj : Ω → α) :
    (ciIdeal proj : Ideal (MvPolynomial (BinomialEdgeVars Ω) K)) =
    binomialEdgeIdeal (ciGraph proj) := by
  apply le_antisymm
  · -- CI generators ⊆ BEI ideal
    apply Ideal.span_le.mpr
    rintro _ ⟨ω, ω', hproj, hne, rfl⟩
    rcases lt_or_gt_of_ne hne with h | h
    · -- ω < ω': directly a BEI generator
      apply Ideal.subset_span
      exact ⟨ω, ω', ⟨hproj, hne⟩, h, rfl⟩
    · -- ω' < ω: negative of a BEI generator
      have hmem : (x ω' : MvPolynomial (BinomialEdgeVars Ω) K) * y ω - x ω * y ω' ∈
          binomialEdgeIdeal (ciGraph proj) := by
        apply Ideal.subset_span
        exact ⟨ω', ω, ⟨hproj.symm, hne.symm⟩, h, rfl⟩
      have : (x ω : MvPolynomial (BinomialEdgeVars Ω) K) * y ω' - x ω' * y ω =
          -(x ω' * y ω - x ω * y ω') := by ring
      rw [this]
      exact (binomialEdgeIdeal (ciGraph proj)).neg_mem hmem
  · -- BEI generators ⊆ CI ideal
    apply Ideal.span_le.mpr
    rintro _ ⟨i, j, hadj, _, rfl⟩
    apply Ideal.subset_span
    exact ⟨i, j, hadj.1, hadj.2, rfl⟩
