/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import BEI.Definitions
import Mathlib.RingTheory.Ideal.Height
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.KrullDimension.Polynomial

/-!
# Material for potential Mathlib upstreaming

This file collects general-purpose lemmas about `Ideal.height` in polynomial rings
that are NOT specific to binomial edge ideals. These could be contributed to Mathlib
once proved.

## Contents

### Sorry'd (Mathlib gaps)
- `height_span_X_image`: Height of a variable-generated ideal in `MvPolynomial σ K`
  equals the number of variables.
- `height_binomialEdgeIdeal_complete`: Height of J_{K_m} = m − 1 (2-minors).

### Discussion: What Mathlib needs
1. **Catenary property for polynomial rings**: The formula
   `height(P) + dim(R/P) = dim(R)` for primes P in `MvPolynomial σ K`.
   This would immediately give height computations via `MvPolynomial.ringKrullDim`.

2. **Height of variable ideals**: `Ideal.span (X '' s)` has height `|s|` in
   `MvPolynomial σ R` when s ⊆ σ and R is nontrivial. Follows from Krull
   (upper bound) + explicit chain of variable-generated primes (lower bound).

3. **Height of determinantal ideals**: The ideal of t-minors of a generic
   m × n matrix has height (m − t + 1)(n − t + 1). For 2-minors of a
   2 × n matrix: height = n − 1 (Eagon–Northcott theorem).

4. **Height additivity for disjoint-variable ideals**: For primes I₁ ⊆ K[X₁],
   I₂ ⊆ K[X₂] in disjoint variable sets, `height(I₁ + I₂) = height(I₁) + height(I₂)`.
   Available via `Algebra.HasGoingDown` for flat extensions
   (`Module.Free → Module.Flat → HasGoingDown`) combined with
   `height_eq_height_add_of_liesOver_of_hasGoingDown`, but the MvPolynomial
   plumbing (splitting variables, LiesOver setup) is nontrivial.
-/

variable {K : Type*} [Field K]

noncomputable section

open MvPolynomial

/-! ## Height of variable-generated ideals -/

/-- The ideal generated by a set of variables `{X i : i ∈ s}` in `MvPolynomial σ K`
has height equal to `|s|`.

**Proof sketch:** Upper bound by Krull's height theorem (the ideal is generated
by |s| elements). Lower bound by the chain
`(X i₁) ⊊ (X i₁, X i₂) ⊊ ... ⊊ (X i₁, ..., X i_{|s|})`,
where each ideal is prime (quotient is a polynomial ring). -/
theorem height_span_X_image {σ : Type*} [Fintype σ] [DecidableEq σ]
    (s : Finset σ) :
    (Ideal.span ((↑s : Set σ).image (X : σ → MvPolynomial σ K))).height = s.card := by
  sorry

/-! ## Height of 2-minor ideals (complete graph binomial edge ideals) -/

variable {V : Type*} [LinearOrder V] [DecidableEq V] [Fintype V]

/-- The binomial edge ideal of the complete graph K_m has height m − 1.
Equivalently, the ideal of 2×2 minors of a generic 2×m matrix has height m − 1.

This is a special case of the Eagon–Northcott theorem: the ideal of t-minors
of a generic p × q matrix has height (p − t + 1)(q − t + 1). For t = 2, p = 2,
q = m: height = (2 − 2 + 1)(m − 2 + 1) = m − 1.

**Proof sketch:** The ideal P = J_{K_m} is the kernel of the Segre-type map
`x_i ↦ t · u_i, y_i ↦ u_i`. The image has Krull dimension m + 1. Since the
ambient ring has dimension 2m, `height(P) = 2m − (m+1) = m − 1` by the
catenary property of polynomial rings (NOT in Mathlib v4.28.0). -/
theorem height_binomialEdgeIdeal_complete (m : ℕ) (hm : 2 ≤ m) :
    Ideal.height (binomialEdgeIdeal (K := K) (⊤ : SimpleGraph (Fin m))) = m - 1 := by
  sorry

end
