import BEI.Definitions
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected
import Mathlib.Combinatorics.SimpleGraph.Connectivity.WalkCounting

variable {K : Type*} [Field K]
variable {V : Type*} [LinearOrder V] [DecidableEq V] [Fintype V]

/-!
# Prime ideals P_S(G) and their basic properties (Section 3)

For each subset `S ⊆ V`, we define the prime ideal `P_S(G)` and establish
its basic properties (primeness, containment in J_G, height formula).

## Definition of P_S(G)
For `S ⊆ V`, let `T = V \ S`. The connected components of `G[T]` are
`G₁, ..., G_c`. Then:
  `P_S(G) = ({xᵢ, yᵢ | i ∈ S}, J_{G̃₁}, ..., J_{G̃_c})`
where `G̃ₖ` is the complete graph on the vertex set of `Gₖ`.

## Reference: Herzog et al. (2010), Section 3
-/

noncomputable section

open MvPolynomial SimpleGraph

/-! ## Connected component count -/

/--
The number of connected components of the induced subgraph on `V \ S`.
This is `c(S)` in the paper's notation.

Defined as `Nat.card` of the `ConnectedComponent` type of the induced subgraph of `G`
on `{v : V | v ∉ S}`. Using `Nat.card` (rather than `Fintype.card`) avoids requiring
a `DecidableRel G.Adj` instance; it equals `Fintype.card` whenever the type is finite.
-/
noncomputable def componentCount (G : SimpleGraph V) (S : Finset V) : ℕ :=
  Nat.card (G.induce {v : V | v ∉ S}).ConnectedComponent

/-- c(∅) equals the number of connected components of G itself.
When S = ∅ the induced subgraph is G.induce Set.univ ≃g G. -/
theorem componentCount_empty (G : SimpleGraph V) :
    componentCount G ∅ = Nat.card G.ConnectedComponent := by
  unfold componentCount
  have hset : {v : V | v ∉ (∅ : Finset V)} = Set.univ := by ext v; simp
  rw [hset]
  exact Nat.card_congr G.induceUnivIso.connectedComponentEquiv

/-! ## The prime ideal P_S(G) -/

/--
Two vertices `u v : V` lie in the same connected component of `G[V \ S]`.
-/
def SameComponent (G : SimpleGraph V) (S : Finset V) (u v : V) : Prop :=
  u ∉ S ∧ v ∉ S ∧
  Relation.ReflTransGen (fun a b => G.Adj a b ∧ a ∉ S ∧ b ∉ S) u v

/--
The prime ideal `P_S(G)` is generated by:
- `X (Sum.inl i)` and `X (Sum.inr i)` for each `i ∈ S`, and
- `x_j * y_k - x_k * y_j` for all j < k in the same component of `G[V \ S]`.

Reference: Herzog et al. (2010), Section 3.
-/
noncomputable def primeComponent (G : SimpleGraph V) (S : Finset V) :
    Ideal (MvPolynomial (BinomialEdgeVars V) K) :=
  Ideal.span
    ({ f : MvPolynomial (BinomialEdgeVars V) K |
        ∃ i ∈ S, f = X (Sum.inl i) ∨ f = X (Sum.inr i) } ∪
     { f : MvPolynomial (BinomialEdgeVars V) K |
        ∃ j k : V, j < k ∧ SameComponent G S j k ∧
             f = x j * y k - x k * y j })

/-! ## Basic properties -/

/-- `P_S(G)` is a prime ideal. -/
theorem primeComponent_isPrime (G : SimpleGraph V) (S : Finset V) :
    (primeComponent (K := K) G S).IsPrime := by
  sorry

/-- `J_G ⊆ P_S(G)` for every subset S. -/
theorem binomialEdgeIdeal_le_primeComponent (G : SimpleGraph V) (S : Finset V) :
    binomialEdgeIdeal (K := K) G ≤ primeComponent (K := K) G S := by
  apply Ideal.span_le.mpr
  intro f hf
  obtain ⟨i, j, hAdj, hij, rfl⟩ := hf
  -- f = x i * y j - x j * y i, with G.Adj i j and i < j
  by_cases hiS : i ∈ S
  · -- i ∈ S: X(Sum.inl i) and X(Sum.inr i) are generators of P_S(G)
    have hxi : X (Sum.inl i) ∈ primeComponent (K := K) G S :=
      Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inl rfl⟩)
    have hyi : X (Sum.inr i) ∈ primeComponent (K := K) G S :=
      Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inr rfl⟩)
    -- x i * y j = X(Sum.inl i) * y j ∈ P_S(G) since X(Sum.inl i) ∈ P_S(G)
    -- x j * y i = x j * X(Sum.inr i) ∈ P_S(G) since X(Sum.inr i) ∈ P_S(G)
    apply (primeComponent (K := K) G S).sub_mem
    · exact Ideal.mul_mem_right _ _ hxi
    · exact (primeComponent (K := K) G S).mul_mem_left _ hyi
  · by_cases hjS : j ∈ S
    · -- j ∈ S: X(Sum.inl j) and X(Sum.inr j) are generators of P_S(G)
      have hxj : X (Sum.inl j) ∈ primeComponent (K := K) G S :=
        Ideal.subset_span (Set.mem_union_left _ ⟨j, hjS, Or.inl rfl⟩)
      have hyj : X (Sum.inr j) ∈ primeComponent (K := K) G S :=
        Ideal.subset_span (Set.mem_union_left _ ⟨j, hjS, Or.inr rfl⟩)
      apply (primeComponent (K := K) G S).sub_mem
      · exact (primeComponent (K := K) G S).mul_mem_left _ hyj
      · exact Ideal.mul_mem_right _ _ hxj
    · -- i ∉ S and j ∉ S: the generator is directly in P_S(G) via SameComponent
      -- i and j are adjacent in G and both not in S, so they are in the same
      -- connected component of G[V \ S]
      apply Ideal.subset_span
      exact Set.mem_union_right _
        ⟨i, j, hij, ⟨hiS, hjS, Relation.ReflTransGen.single ⟨hAdj, hiS, hjS⟩⟩, rfl⟩

/-! ## Lemma 3.1: Height formula -/

/--
Placeholder for ideal height (Krull height of a prime ideal).
The correct Mathlib API is `Ideal.primeHeight` or similar.
-/
noncomputable def idealHeight (I : Ideal (MvPolynomial (BinomialEdgeVars V) K)) : ℕ := sorry

/--
**Lemma 3.1** (Herzog et al. 2010):
  `height(P_S(G)) = |S| + (|V| - c(S))`

Reference: Herzog et al. (2010), Lemma 3.1.
-/
theorem lemma_3_1 (G : SimpleGraph V) (S : Finset V) :
    idealHeight (primeComponent (K := K) G S) =
      S.card + (Fintype.card V - componentCount G S) := by
  sorry

/--
For connected G, `P_∅(G)` equals `J_G`.
(The only component of `G[V]` is G itself, and the complete graph on V(G) is J_G.)
-/
theorem primeComponent_empty_connected (G : SimpleGraph V) (hConn : G.Connected) :
    primeComponent (K := K) G ∅ = binomialEdgeIdeal (K := K) G := by
  sorry

/-! ## Proposition 3.6: When J_G is prime -/

/--
**Proposition 3.6** (Herzog et al. 2010): `J_G` is a prime ideal if and only if
every connected component of G is a complete graph.

Reference: Herzog et al. (2010), Proposition 3.6.
-/
theorem prop_3_6 (G : SimpleGraph V) :
    (binomialEdgeIdeal (K := K) G).IsPrime ↔
    ∀ u w : V, G.Reachable u w → G.Adj u w ∨ u = w := by
  sorry

end
