import BEI.Definitions
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.RingTheory.Ideal.Height
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected
import Mathlib.Combinatorics.SimpleGraph.Connectivity.WalkCounting

variable {K : Type*} [Field K]
variable {V : Type*} [LinearOrder V] [DecidableEq V] [Fintype V]

/-!
# Prime ideals P_S(G) and their basic properties (Section 3)

For each subset `S ⊆ V`, we define the prime ideal `P_S(G)` and establish
its basic properties (primeness, containment in J_G, height formula).

## Definition of P_S(G)
For `S ⊆ V`, let `T = V \ S`. The connected components of `G[T]` are
`G₁, ..., G_c`. Then:
  `P_S(G) = ({xᵢ, yᵢ | i ∈ S}, J_{G̃₁}, ..., J_{G̃_c})`
where `G̃ₖ` is the complete graph on the vertex set of `Gₖ`.

## Reference: Herzog et al. (2010), Section 3
-/

noncomputable section

open MvPolynomial SimpleGraph

/-! ## Connected component count -/

/--
The number of connected components of the induced subgraph on `V \ S`.
This is `c(S)` in the paper's notation.

Defined as `Nat.card` of the `ConnectedComponent` type of the induced subgraph of `G`
on `{v : V | v ∉ S}`. Using `Nat.card` (rather than `Fintype.card`) avoids requiring
a `DecidableRel G.Adj` instance; it equals `Fintype.card` whenever the type is finite.
-/
noncomputable def componentCount (G : SimpleGraph V) (S : Finset V) : ℕ :=
  Nat.card (G.induce {v : V | v ∉ S}).ConnectedComponent

/-- c(∅) equals the number of connected components of G itself.
When S = ∅ the induced subgraph is G.induce Set.univ ≃g G. -/
theorem componentCount_empty (G : SimpleGraph V) :
    componentCount G ∅ = Nat.card G.ConnectedComponent := by
  unfold componentCount
  have hset : {v : V | v ∉ (∅ : Finset V)} = Set.univ := by ext v; simp
  rw [hset]
  exact Nat.card_congr G.induceUnivIso.connectedComponentEquiv

/-! ## The prime ideal P_S(G) -/

/--
Two vertices `u v : V` lie in the same connected component of `G[V \ S]`.
-/
def SameComponent (G : SimpleGraph V) (S : Finset V) (u v : V) : Prop :=
  u ∉ S ∧ v ∉ S ∧
  Relation.ReflTransGen (fun a b => G.Adj a b ∧ a ∉ S ∧ b ∉ S) u v

private lemma reflTransGen_symm {R : V → V → Prop}
    (hR : ∀ a b, R a b → R b a) {u v : V}
    (h : Relation.ReflTransGen R u v) : Relation.ReflTransGen R v u := by
  induction h with
  | refl => exact .refl
  | tail _ hab ih => exact (Relation.ReflTransGen.single (hR _ _ hab)).trans ih

lemma SameComponent.symm {G : SimpleGraph V} {S : Finset V}
    {u v : V} (h : SameComponent G S u v) : SameComponent G S v u :=
  ⟨h.2.1, h.1, reflTransGen_symm
    (fun _ _ ⟨hadj, ha, hb⟩ => ⟨hadj.symm, hb, ha⟩) h.2.2⟩

lemma SameComponent.trans {G : SimpleGraph V} {S : Finset V}
    {u v w : V} (h1 : SameComponent G S u v) (h2 : SameComponent G S v w) :
    SameComponent G S u w :=
  ⟨h1.1, h2.2.1, h1.2.2.trans h2.2.2⟩

/-! ## Component representative and ring homomorphism for primeness proof -/

open Classical in
/-- The minimum vertex in the same connected component of `G[V\S]` as `v`.
For `v ∈ S`, returns `v` itself (unused in the primeness proof). -/
noncomputable def compRep (G : SimpleGraph V) (S : Finset V) (v : V) : V :=
  if hv : v ∈ S then v
  else (Finset.univ.filter (fun w => SameComponent G S v w)).min'
      (Finset.filter_nonempty_iff.mpr ⟨v, Finset.mem_univ _,
        ⟨hv, hv, Relation.ReflTransGen.refl⟩⟩)

open Classical in
lemma compRep_eq_of_sameComponent (G : SimpleGraph V) (S : Finset V)
    {u v : V} (h : SameComponent G S u v) : compRep G S u = compRep G S v := by
  unfold compRep
  simp only [h.1, h.2.1, ↓reduceDIte]
  congr 1; ext w
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  exact ⟨SameComponent.trans h.symm, SameComponent.trans h⟩

open Classical in
/-- The ring homomorphism `φ : K[x,y] → K[x,y]` used to prove `P_S(G)` is prime.
Maps `x_i ↦ 0`, `y_i ↦ 0` for `i ∈ S`, and `x_j ↦ x_j`,
`y_j ↦ x_j * y_{rep(j)}` for `j ∉ S`, where `rep(j)` is the component representative. -/
noncomputable def primeComponentMap (G : SimpleGraph V) (S : Finset V) :
    MvPolynomial (BinomialEdgeVars V) K →ₐ[K]
    MvPolynomial (BinomialEdgeVars V) K :=
  MvPolynomial.aeval (fun v : BinomialEdgeVars V =>
    match v with
    | Sum.inl i =>
      if i ∈ S then 0 else X (Sum.inl i : BinomialEdgeVars V)
    | Sum.inr i =>
      if i ∈ S then 0
      else X (Sum.inl i : BinomialEdgeVars V) *
           X (Sum.inr (compRep G S i) : BinomialEdgeVars V))

/--
The prime ideal `P_S(G)` is generated by:
- `X (Sum.inl i)` and `X (Sum.inr i)` for each `i ∈ S`, and
- `x_j * y_k - x_k * y_j` for all j < k in the same component of `G[V \ S]`.

Reference: Herzog et al. (2010), Section 3.
-/
noncomputable def primeComponent (G : SimpleGraph V) (S : Finset V) :
    Ideal (MvPolynomial (BinomialEdgeVars V) K) :=
  Ideal.span
    ({ f : MvPolynomial (BinomialEdgeVars V) K |
        ∃ i ∈ S, f = X (Sum.inl i) ∨ f = X (Sum.inr i) } ∪
     { f : MvPolynomial (BinomialEdgeVars V) K |
        ∃ j k : V, j < k ∧ SameComponent G S j k ∧
             f = x j * y k - x k * y j })

/-! ## Basic properties -/

-- Generators of P_S(G) map to 0 under primeComponentMap
set_option maxHeartbeats 400000 in -- aeval_X unfolding is expensive
open Classical in
private lemma primeComponent_le_ker (G : SimpleGraph V) (S : Finset V) :
    primeComponent (K := K) G S ≤ RingHom.ker (primeComponentMap G S).toRingHom := by
  apply Ideal.span_le.mpr
  intro f hf
  simp only [Set.mem_union, Set.mem_setOf_eq] at hf
  change (primeComponentMap G S).toRingHom f = 0
  rcases hf with ⟨i, hiS, rfl | rfl⟩ | ⟨j, k, _, hsc, rfl⟩
  · -- x_i for i ∈ S
    change (primeComponentMap G S) (X (Sum.inl i)) = 0
    simp [primeComponentMap, MvPolynomial.aeval_X, hiS]
  · -- y_i for i ∈ S
    change (primeComponentMap G S) (X (Sum.inr i)) = 0
    simp [primeComponentMap, MvPolynomial.aeval_X, hiS]
  · -- x_j * y_k - x_k * y_j for j,k in same component
    change (primeComponentMap G S) (x j * y k - x k * y j) = 0
    simp only [x, y, map_sub, map_mul]
    simp only [primeComponentMap, MvPolynomial.aeval_X, hsc.1, hsc.2.1, ite_false]
    rw [compRep_eq_of_sameComponent G S hsc]; ring

/-! ### Helpers for ker ≤ P_S(G) -/

-- Use an open section to avoid repeating `open Classical in`
section ker_helpers
open Classical

/-- x_j * y_k - x_k * y_j ∈ P_S(G) when j,k are in the same connected component of G[V\S]. -/
private lemma minor_mem_primeComponent (G : SimpleGraph V) (S : Finset V)
    {j k : V} (hjk : j ≠ k) (hsc : SameComponent G S j k) :
    (x (K := K) j * y k - x k * y j) ∈ primeComponent G S := by
  rcases lt_or_gt_of_ne hjk with h | h
  · exact Ideal.subset_span (Set.mem_union_right _ ⟨j, k, h, hsc, rfl⟩)
  · have : x (K := K) k * y j - x j * y k ∈ primeComponent G S :=
      Ideal.subset_span (Set.mem_union_right _ ⟨k, j, h, hsc.symm, rfl⟩)
    convert (primeComponent G S).neg_mem this using 1; ring

/-- A monomial with S-support lies in `P_S(G)`. -/
private lemma monomial_S_support_mem (G : SimpleGraph V) (S : Finset V)
    (d : BinomialEdgeVars V →₀ ℕ) (c : K) {i : V} (hi : i ∈ S)
    (hd : d (Sum.inl i : BinomialEdgeVars V) ≥ 1 ∨
          d (Sum.inr i : BinomialEdgeVars V) ≥ 1) :
    (monomial d c : MvPolynomial (BinomialEdgeVars V) K) ∈ primeComponent G S := by
  rcases hd with h | h
  · -- Factor out X(Sum.inl i)
    set s : BinomialEdgeVars V →₀ ℕ := Finsupp.single (Sum.inl i) 1
    have hle : s ≤ d := Finsupp.single_le_iff.mpr h
    have hfact : monomial d c = monomial (d - s) c * monomial s 1 := by
      rw [monomial_mul, mul_one, tsub_add_cancel_of_le hle]
    rw [hfact]
    exact (primeComponent G S).mul_mem_left _
      (Ideal.subset_span (Set.mem_union_left _ ⟨i, hi, Or.inl rfl⟩))
  · -- Factor out X(Sum.inr i)
    set s : BinomialEdgeVars V →₀ ℕ := Finsupp.single (Sum.inr i) 1
    have hle : s ≤ d := Finsupp.single_le_iff.mpr h
    have hfact : monomial d c = monomial (d - s) c * monomial s 1 := by
      rw [monomial_mul, mul_one, tsub_add_cancel_of_le hle]
    rw [hfact]
    exact (primeComponent G S).mul_mem_left _
      (Ideal.subset_span (Set.mem_union_left _ ⟨i, hi, Or.inr rfl⟩))

/-! #### The single-swap monomial identity -/

/-- The single-swap monomial difference lies in P_S(G):
`monomial d c - monomial d' c ∈ P_S(G)` when `d = e + sxk + syj` and `d' = e + sxj + syk`
for vertices j,k in the same component. Takes the two exponents directly. -/
private lemma single_swap_mem (G : SimpleGraph V) (S : Finset V)
    (d d' : BinomialEdgeVars V →₀ ℕ) (e : BinomialEdgeVars V →₀ ℕ) (c : K) {j k : V}
    (hjk : j ≠ k) (hsc : SameComponent G S j k)
    (hd : d = e + (Finsupp.single (Sum.inl k) 1 : BinomialEdgeVars V →₀ ℕ) +
              (Finsupp.single (Sum.inr j) 1 : BinomialEdgeVars V →₀ ℕ))
    (hd' : d' = e + (Finsupp.single (Sum.inl j) 1 : BinomialEdgeVars V →₀ ℕ) +
               (Finsupp.single (Sum.inr k) 1 : BinomialEdgeVars V →₀ ℕ)) :
    (monomial d c - monomial d' c : MvPolynomial (BinomialEdgeVars V) K) ∈
      primeComponent (K := K) G S := by
  subst hd; subst hd'
  set sxk : BinomialEdgeVars V →₀ ℕ := Finsupp.single (Sum.inl k) 1
  set syj : BinomialEdgeVars V →₀ ℕ := Finsupp.single (Sum.inr j) 1
  set sxj : BinomialEdgeVars V →₀ ℕ := Finsupp.single (Sum.inl j) 1
  set syk : BinomialEdgeVars V →₀ ℕ := Finsupp.single (Sum.inr k) 1
  -- Factor: monomial (e + sxk + syj) c = monomial e c * monomial (sxk + syj) 1
  have hfact1 : (monomial (e + sxk + syj) c : MvPolynomial (BinomialEdgeVars V) K) =
      monomial e c * monomial (sxk + syj) 1 := by
    rw [monomial_mul, mul_one, add_assoc]
  have hfact2 : (monomial (e + sxj + syk) c : MvPolynomial (BinomialEdgeVars V) K) =
      monomial e c * monomial (sxj + syk) 1 := by
    rw [monomial_mul, mul_one, add_assoc]
  rw [hfact1, hfact2, ← mul_sub]
  apply (primeComponent G S).mul_mem_left
  -- Need: monomial (sxk + syj) 1 - monomial (sxj + syk) 1 ∈ primeComponent G S
  -- Strategy: show each monomial is X * X, then use minor_mem_primeComponent
  -- X v = monomial (Finsupp.single v 1) 1, and monomial_mul gives the product
  suffices h : (X (Sum.inl k : BinomialEdgeVars V) *
      X (Sum.inr j : BinomialEdgeVars V) -
    X (Sum.inl j : BinomialEdgeVars V) *
      X (Sum.inr k : BinomialEdgeVars V) :
    MvPolynomial (BinomialEdgeVars V) K) ∈ primeComponent (K := K) G S by
    convert h using 1
    change monomial (sxk + syj) (1 : K) - monomial (sxj + syk) 1 =
      X (Sum.inl k : BinomialEdgeVars V) * X (Sum.inr j : BinomialEdgeVars V) -
      X (Sum.inl j : BinomialEdgeVars V) * X (Sum.inr k : BinomialEdgeVars V)
    simp only [MvPolynomial.X]
    congr 1 <;> { rw [monomial_mul, one_mul]; congr 1 <;> simp [sxk, syj, sxj, syk] }
  have := minor_mem_primeComponent (K := K) G S hjk hsc
  convert (primeComponent (K := K) G S).neg_mem this using 1
  simp only [x, y]; ring

/-! #### Monomial swap lemma (by induction on deviation) -/

/-- The "deviation" measuring excess y-exponents of `d₀` over `d₁`. -/
private noncomputable def yDeviation (d₀ d₁ : BinomialEdgeVars V →₀ ℕ) : ℕ :=
  Finset.univ.sum fun j : V => d₀ (Sum.inr j : BinomialEdgeVars V) -
    d₁ (Sum.inr j : BinomialEdgeVars V)

/-- Two exponents are fiber-equivalent: same total per vertex and same y-total per component,
with no S-support on either side. -/
private def FiberEquiv (G : SimpleGraph V) (S : Finset V)
    (d₀ d₁ : BinomialEdgeVars V →₀ ℕ) : Prop :=
  (∀ j : V, d₀ (Sum.inl j : BinomialEdgeVars V) + d₀ (Sum.inr j : BinomialEdgeVars V) =
    d₁ (Sum.inl j : BinomialEdgeVars V) + d₁ (Sum.inr j : BinomialEdgeVars V)) ∧
  (∀ r : V, Finset.univ.sum (fun k : V =>
      if compRep G S k = r ∧ k ∉ S then d₀ (Sum.inr k : BinomialEdgeVars V) else 0) =
    Finset.univ.sum (fun k : V =>
      if compRep G S k = r ∧ k ∉ S then d₁ (Sum.inr k : BinomialEdgeVars V) else 0)) ∧
  (∀ i ∈ S, d₀ (Sum.inl i : BinomialEdgeVars V) = 0 ∧
    d₀ (Sum.inr i : BinomialEdgeVars V) = 0) ∧
  (∀ i ∈ S, d₁ (Sum.inl i : BinomialEdgeVars V) = 0 ∧
    d₁ (Sum.inr i : BinomialEdgeVars V) = 0)

/-- When deviation is 0 and fiber-equivalent, the exponents are equal. -/
private lemma fiber_equiv_of_yDeviation_zero {G : SimpleGraph V} {S : Finset V}
    {d₀ d₁ : BinomialEdgeVars V →₀ ℕ}
    (hfe : FiberEquiv G S d₀ d₁) (hdev : yDeviation (V := V) d₀ d₁ = 0) :
    d₀ = d₁ := by
  obtain ⟨htot, hcomp, hS0, hS1⟩ := hfe
  -- Step 1: yDeviation = 0 implies d₀(inr j) ≤ d₁(inr j) for all j
  have hle_y : ∀ j : V, d₀ (Sum.inr j : BinomialEdgeVars V) ≤
      d₁ (Sum.inr j : BinomialEdgeVars V) := by
    intro j
    have h0 : Finset.univ.sum (fun j : V => d₀ (Sum.inr j : BinomialEdgeVars V) -
        d₁ (Sum.inr j : BinomialEdgeVars V)) = 0 := hdev
    have hall := (Finset.sum_eq_zero_iff_of_nonneg (fun _ _ => Nat.zero_le _)).mp h0
    have := hall j (Finset.mem_univ j)
    omega
  -- Step 2: From condition 1, d₀(inl j) ≥ d₁(inl j)
  have hge_x : ∀ j : V, d₁ (Sum.inl j : BinomialEdgeVars V) ≤
      d₀ (Sum.inl j : BinomialEdgeVars V) := by
    intro j; have := htot j; have := hle_y j; omega
  -- Step 3: d₀(inr j) = d₁(inr j) for all j
  -- Use the per-component sums (condition 2).
  -- For each component rep r, the sum of d₀(inr k) over k in the component
  -- equals the sum of d₁(inr k). Combined with d₀(inr k) ≤ d₁(inr k) pointwise,
  -- each ite(..., d₀(inr k), 0) ≤ ite(..., d₁(inr k), 0) and sums are equal,
  -- so each term is equal.
  have heq_y : ∀ j : V, d₀ (Sum.inr j : BinomialEdgeVars V) =
      d₁ (Sum.inr j : BinomialEdgeVars V) := by
    intro j
    by_cases hjS : j ∈ S
    · exact le_antisymm (hle_y j) (by rw [(hS0 j hjS).2, (hS1 j hjS).2])
    · -- j ∉ S: use the per-component sum condition
      set r := compRep G S j
      have hcond : compRep G S j = r ∧ j ∉ S := ⟨rfl, hjS⟩
      -- The per-component sum equality
      have hsum_eq := hcomp r
      -- Each term in the sum has ite(..., d₀(inr k), 0) ≤ ite(..., d₁(inr k), 0)
      have hle_ite : ∀ k : V,
          (if compRep G S k = r ∧ k ∉ S then d₀ (Sum.inr k : BinomialEdgeVars V) else 0) ≤
          (if compRep G S k = r ∧ k ∉ S then d₁ (Sum.inr k : BinomialEdgeVars V) else 0) := by
        intro k
        split
        · exact hle_y k
        · exact le_refl 0
      -- Since ∑ le terms = ∑ ge terms and pointwise ≤, each term is equal
      have hall_eq : ∀ k ∈ Finset.univ,
          (if compRep G S k = r ∧ k ∉ S then d₀ (Sum.inr k : BinomialEdgeVars V) else 0) =
          (if compRep G S k = r ∧ k ∉ S then d₁ (Sum.inr k : BinomialEdgeVars V) else 0) := by
        have hle_sum : Finset.univ.sum (fun k : V =>
            if compRep G S k = r ∧ k ∉ S then d₀ (Sum.inr k : BinomialEdgeVars V) else 0) ≤
            Finset.univ.sum (fun k : V =>
            if compRep G S k = r ∧ k ∉ S then d₁ (Sum.inr k : BinomialEdgeVars V) else 0) :=
          Finset.sum_le_sum (fun k _ => hle_ite k)
        exact fun k _ => le_antisymm (hle_ite k)
          (by_contra fun hlt => by
            push_neg at hlt
            have : Finset.univ.sum (fun k : V =>
                if compRep G S k = r ∧ k ∉ S then d₀ (Sum.inr k : BinomialEdgeVars V) else 0) <
                Finset.univ.sum (fun k : V =>
                if compRep G S k = r ∧ k ∉ S then d₁ (Sum.inr k : BinomialEdgeVars V) else 0) :=
              Finset.sum_lt_sum (fun k _ => hle_ite k) ⟨k, Finset.mem_univ k, hlt⟩
            linarith [hsum_eq])
      have hk_eq := hall_eq j (Finset.mem_univ j)
      simp only [hcond] at hk_eq
      exact hk_eq
  -- Step 4: d₀(inl j) = d₁(inl j) follows from condition 1 and Step 3
  have heq_x : ∀ j : V, d₀ (Sum.inl j : BinomialEdgeVars V) =
      d₁ (Sum.inl j : BinomialEdgeVars V) := by
    intro j; have := htot j; have := heq_y j; omega
  -- Conclude d₀ = d₁
  ext v
  rcases v with j | j
  · exact heq_x j
  · exact heq_y j

/-- compRep is in the same component as v (when v ∉ S). -/
private lemma sameComponent_compRep (G : SimpleGraph V) (S : Finset V)
    {v : V} (hv : v ∉ S) : SameComponent G S v (compRep G S v) := by
  unfold compRep
  simp only [hv, ↓reduceDIte]
  have hmem := Finset.min'_mem (Finset.univ.filter (fun w => SameComponent G S v w))
    (Finset.filter_nonempty_iff.mpr ⟨v, Finset.mem_univ _,
      ⟨hv, hv, Relation.ReflTransGen.refl⟩⟩)
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hmem
  exact hmem

/-- If two vertices have the same compRep and both ∉ S, they are in the same component. -/
private lemma sameComponent_of_compRep_eq (G : SimpleGraph V) (S : Finset V)
    {j k : V} (hjS : j ∉ S) (hkS : k ∉ S)
    (heq : compRep G S j = compRep G S k) : SameComponent G S j k :=
  (sameComponent_compRep G S hjS).trans
    (heq ▸ (sameComponent_compRep G S hkS).symm)

/-- When deviation > 0, find suitable swap vertices. -/
private lemma exists_swap_vertices {G : SimpleGraph V} {S : Finset V}
    {d₀ d₁ : BinomialEdgeVars V →₀ ℕ}
    (hfe : FiberEquiv G S d₀ d₁) (hdev : yDeviation (V := V) d₀ d₁ > 0) :
    ∃ j k : V, j ≠ k ∧ SameComponent G S j k ∧
      d₀ (Sum.inr j : BinomialEdgeVars V) > d₁ (Sum.inr j : BinomialEdgeVars V) ∧
      d₀ (Sum.inr k : BinomialEdgeVars V) < d₁ (Sum.inr k : BinomialEdgeVars V) ∧
      d₀ (Sum.inr j : BinomialEdgeVars V) ≥ 1 ∧
      d₀ (Sum.inl k : BinomialEdgeVars V) ≥ 1 := by
  obtain ⟨htot, hcomp, hS0, hS1⟩ := hfe
  -- Step 1: Find j with d₀(inr j) > d₁(inr j)
  have hpos := (Finset.sum_pos_iff_of_nonneg (fun _ _ => Nat.zero_le _)).mp hdev
  obtain ⟨j, _, hjgt⟩ := hpos
  have hjgt' : d₀ (Sum.inr j : BinomialEdgeVars V) > d₁ (Sum.inr j : BinomialEdgeVars V) := by
    omega
  -- j ∉ S (otherwise d₀(inr j) = 0)
  have hjS : j ∉ S := by intro hjS; have := (hS0 j hjS).2; omega
  -- d₀(inr j) ≥ 1
  have hyj : d₀ (Sum.inr j : BinomialEdgeVars V) ≥ 1 := by omega
  -- Step 2: Find k in j's component with d₀(inr k) < d₁(inr k)
  -- Use per-component sum equality
  set r := compRep G S j
  have hsum_eq := hcomp r
  -- The sum for d₁ must be strictly larger than d₀ on *some* term in the same component,
  -- because the sums are equal but d₀(inr j) > d₁(inr j) and j is in the component.
  -- First, show that if every term with compRep = r, k ∉ S has d₀ ≥ d₁, we get a contradiction.
  suffices ∃ k : V, compRep G S k = r ∧ k ∉ S ∧
      d₀ (Sum.inr k : BinomialEdgeVars V) < d₁ (Sum.inr k : BinomialEdgeVars V) by
    obtain ⟨k, hkr, hkS, hlk⟩ := this
    have hjk : j ≠ k := by intro heq; subst heq; omega
    have hsc : SameComponent G S j k :=
      sameComponent_of_compRep_eq G S hjS hkS (show compRep G S j = compRep G S k from by
        rw [show compRep G S j = r from rfl, hkr])
    have hxk : d₀ (Sum.inl k : BinomialEdgeVars V) ≥ 1 := by
      have := htot k; have := hlk; omega
    exact ⟨j, k, hjk, hsc, hjgt', hlk, hyj, hxk⟩
  -- Prove the existence of such k by contradiction
  by_contra hno
  push_neg at hno
  -- hno : ∀ k, compRep G S k = r → k ∉ S → d₁(inr k) ≤ d₀(inr k)
  -- From the per-component sums being equal and every term d₁ ≤ d₀,
  -- with one term d₁ < d₀ (namely j), we get a contradiction.
  have hle_all : ∀ k ∈ Finset.univ,
      (if compRep G S k = r ∧ k ∉ S then d₁ (Sum.inr k : BinomialEdgeVars V) else 0) ≤
      (if compRep G S k = r ∧ k ∉ S then d₀ (Sum.inr k : BinomialEdgeVars V) else 0) := by
    intro k _
    split
    · next hcond => exact hno k hcond.1 hcond.2
    · exact le_refl 0
  have hlt_j : (if compRep G S j = r ∧ j ∉ S
      then d₁ (Sum.inr j : BinomialEdgeVars V) else 0) <
      (if compRep G S j = r ∧ j ∉ S
      then d₀ (Sum.inr j : BinomialEdgeVars V) else 0) := by
    simp only [show compRep G S j = r from rfl, hjS, and_self, not_false_eq_true, ite_true]
    exact hjgt'
  have hlt := Finset.sum_lt_sum hle_all ⟨j, Finset.mem_univ j, hlt_j⟩
  omega

/-- The swap preserves fiber-equivalence.
Takes the swapped exponent `d₀'` as a parameter to avoid type-class issues. -/
private lemma swapExp_fiberEquiv {G : SimpleGraph V} {S : Finset V}
    {d₀ d₁ d₀' : BinomialEdgeVars V →₀ ℕ} {j k : V}
    (hfe : FiberEquiv G S d₀ d₁)
    (hjk : j ≠ k) (hsc : SameComponent G S j k)
    (hyj : d₀ (Sum.inr j : BinomialEdgeVars V) ≥ 1)
    (hxk : d₀ (Sum.inl k : BinomialEdgeVars V) ≥ 1)
    (hgj : d₀ (Sum.inr j : BinomialEdgeVars V) > d₁ (Sum.inr j : BinomialEdgeVars V))
    (hd₀' : ∀ v : BinomialEdgeVars V, d₀' v =
      d₀ v + (Finsupp.single (Sum.inl j : BinomialEdgeVars V) 1 v +
        Finsupp.single (Sum.inr k : BinomialEdgeVars V) 1 v) -
      (Finsupp.single (Sum.inr j : BinomialEdgeVars V) 1 v +
        Finsupp.single (Sum.inl k : BinomialEdgeVars V) 1 v)) :
    FiberEquiv G S d₀' d₁ := by
  obtain ⟨htot, hcomp, hS0, hS1⟩ := hfe
  -- Helper: compute d₀' at key positions using the pointwise swap spec
  -- The swap: d₀'(v) = d₀(v) + single(xj)(v) + single(yk)(v) - single(yj)(v) - single(xk)(v)
  -- At yj: d₀(yj) + 0 + 0 - 1 - 0 = d₀(yj) - 1
  -- At xj: d₀(xj) + 1 + 0 - 0 - 0 = d₀(xj) + 1
  -- At yk: d₀(yk) + 0 + 1 - 0 - 0 = d₀(yk) + 1
  -- At xk: d₀(xk) + 0 + 0 - 0 - 1 = d₀(xk) - 1
  -- Otherwise: d₀(v)
  -- Helper tactic pattern: specialize hd₀' at a variable, use rw to evaluate single_eq_same/of_ne
  have NE_lr : ∀ (a b : V), (Sum.inl a : BinomialEdgeVars V) ≠ Sum.inr b :=
    fun _ _ => Sum.inl_ne_inr
  have NE_rl : ∀ (a b : V), (Sum.inr a : BinomialEdgeVars V) ≠ Sum.inl b :=
    fun _ _ => Sum.inr_ne_inl
  have hd₀'_yj : d₀' (Sum.inr j : BinomialEdgeVars V) =
      d₀ (Sum.inr j : BinomialEdgeVars V) - 1 := by
    have h := hd₀' (Sum.inr j : BinomialEdgeVars V)
    rw [Finsupp.single_eq_of_ne (NE_rl j j),
        Finsupp.single_eq_of_ne (show (Sum.inr j : BinomialEdgeVars V) ≠ Sum.inr k from
          fun he => hjk (Sum.inr.inj he)),
        Finsupp.single_eq_same,
        Finsupp.single_eq_of_ne (NE_rl j k)] at h; omega
  have hd₀'_xj : d₀' (Sum.inl j : BinomialEdgeVars V) =
      d₀ (Sum.inl j : BinomialEdgeVars V) + 1 := by
    have h := hd₀' (Sum.inl j : BinomialEdgeVars V)
    rw [Finsupp.single_eq_same,
        Finsupp.single_eq_of_ne (NE_lr j k),
        Finsupp.single_eq_of_ne (NE_lr j j),
        Finsupp.single_eq_of_ne (show (Sum.inl j : BinomialEdgeVars V) ≠ Sum.inl k from
          fun he => hjk (Sum.inl.inj he))] at h; omega
  have hd₀'_yk : d₀' (Sum.inr k : BinomialEdgeVars V) =
      d₀ (Sum.inr k : BinomialEdgeVars V) + 1 := by
    have h := hd₀' (Sum.inr k : BinomialEdgeVars V)
    rw [Finsupp.single_eq_of_ne (NE_rl k j),
        Finsupp.single_eq_same,
        Finsupp.single_eq_of_ne (show (Sum.inr k : BinomialEdgeVars V) ≠ Sum.inr j from
          fun he => hjk.symm (Sum.inr.inj he)),
        Finsupp.single_eq_of_ne (NE_rl k k)] at h; omega
  have hd₀'_xk : d₀' (Sum.inl k : BinomialEdgeVars V) =
      d₀ (Sum.inl k : BinomialEdgeVars V) - 1 := by
    have h := hd₀' (Sum.inl k : BinomialEdgeVars V)
    rw [Finsupp.single_eq_of_ne (show (Sum.inl k : BinomialEdgeVars V) ≠ Sum.inl j from
          fun he => hjk.symm (Sum.inl.inj he)),
        Finsupp.single_eq_of_ne (NE_lr k k),
        Finsupp.single_eq_of_ne (NE_lr k j),
        Finsupp.single_eq_same] at h; omega
  have hd₀'_other : ∀ v : BinomialEdgeVars V,
      v ≠ Sum.inl j → v ≠ Sum.inr j → v ≠ Sum.inl k → v ≠ Sum.inr k →
      d₀' v = d₀ v := by
    intro v h1 h2 h3 h4
    have h := hd₀' v
    simp only [Finsupp.single_apply] at h
    rw [if_neg (Ne.symm h1), if_neg (Ne.symm h4),
        if_neg (Ne.symm h2), if_neg (Ne.symm h3)] at h
    omega
  -- Condition 1: per-vertex totals preserved
  refine ⟨fun m => ?_, fun r' => ?_, fun i hi => ?_, hS1⟩
  · -- d₀'(inl m) + d₀'(inr m) = d₁(inl m) + d₁(inr m)
    by_cases hmj : m = j
    · rw [show m = j from hmj]; rw [hd₀'_xj, hd₀'_yj]; have := htot j; have := hyj; omega
    · by_cases hmk : m = k
      · rw [show m = k from hmk]; rw [hd₀'_xk, hd₀'_yk]; have := htot k; have := hxk; omega
      · have h1 : (Sum.inl m : BinomialEdgeVars V) ≠ Sum.inl j :=
            fun h => hmj (Sum.inl.inj h)
        have h2 : (Sum.inr m : BinomialEdgeVars V) ≠ Sum.inr j :=
            fun h => hmj (Sum.inr.inj h)
        have h3 : (Sum.inl m : BinomialEdgeVars V) ≠ Sum.inl k :=
            fun h => hmk (Sum.inl.inj h)
        have h4 : (Sum.inr m : BinomialEdgeVars V) ≠ Sum.inr k :=
            fun h => hmk (Sum.inr.inj h)
        have hinj1 : (Sum.inl m : BinomialEdgeVars V) ≠ Sum.inr j := Sum.inl_ne_inr
        have hinj2 : (Sum.inr m : BinomialEdgeVars V) ≠ Sum.inl j := Sum.inr_ne_inl
        have hinj3 : (Sum.inl m : BinomialEdgeVars V) ≠ Sum.inr k := Sum.inl_ne_inr
        have hinj4 : (Sum.inr m : BinomialEdgeVars V) ≠ Sum.inl k := Sum.inr_ne_inl
        rw [hd₀'_other (Sum.inl m) h1 hinj1 h3 hinj3,
            hd₀'_other (Sum.inr m) hinj2 h2 hinj4 h4]
        exact htot m
  · -- Per-component y-sums preserved (∀ r', ∑ ite(cond) d₀' = ∑ ite(cond) d₀)
    -- The only y-variables that change are inr j (decreases by 1) and inr k (increases by 1)
    -- j and k have the same compRep, so the net change in any component sum is 0
    have hrep_eq : compRep G S j = compRep G S k :=
      compRep_eq_of_sameComponent G S hsc
    have hjS : j ∉ S := hsc.1
    have hkS : k ∉ S := hsc.2.1
    -- Show: ∑ ite(cond, d₀'(inr m), 0) = ∑ ite(cond, d₀(inr m), 0)
    -- Then use hcomp r' to conclude.
    suffices heq_d₀ : Finset.univ.sum (fun m : V =>
        if compRep G S m = r' ∧ m ∉ S then d₀' (Sum.inr m : BinomialEdgeVars V) else 0) =
      Finset.univ.sum (fun m : V =>
        if compRep G S m = r' ∧ m ∉ S then d₀ (Sum.inr m : BinomialEdgeVars V) else 0) from
      heq_d₀.trans (hcomp r')
    -- For m ≠ j and m ≠ k, the terms are equal.
    -- For m = j: d₀'(inr j) = d₀(inr j) - 1, and the ite condition holds iff compRep j = r' ∧ j ∉ S
    -- For m = k: d₀'(inr k) = d₀(inr k) + 1, and the ite condition holds iff compRep k = r' ∧ k ∉ S
    -- Since compRep j = compRep k, both conditions hold or neither holds.
    -- When both hold: (d₀(inr j) - 1) + (d₀(inr k) + 1) = d₀(inr j) + d₀(inr k) (since d₀(inr j) ≥ 1)
    -- When neither holds: 0 + 0 = 0 + 0
    -- So the sums are equal.
    by_cases hr : compRep G S j = r'
    · -- j and k are in this component
      have hcond_j : compRep G S j = r' ∧ j ∉ S := ⟨hr, hjS⟩
      have hcond_k : compRep G S k = r' ∧ k ∉ S := ⟨hrep_eq ▸ hr, hkS⟩
      -- Split the sum: separate out j and k terms
      -- ∑_m f(m) = f(j) + f(k) + ∑_{m ≠ j, m ≠ k} f(m)
      -- The sum over m ≠ j, k is the same for d₀' and d₀
      -- f(j) + f(k) for d₀' is (d₀(inr j) - 1) + (d₀(inr k) + 1) = d₀(inr j) + d₀(inr k)
      -- f(j) + f(k) for d₀ is d₀(inr j) + d₀(inr k)
      -- So the sums are equal.
      -- Use Finset.sum_congr won't work because individual terms differ.
      -- Instead, use sum splitting: pull out j and k from the sum.
      have hjmem : j ∈ Finset.univ := Finset.mem_univ j
      have hkmem : k ∈ (Finset.univ.erase j) := by
        simp [Finset.mem_erase, hjk.symm]
      -- For d₀':
      rw [← Finset.add_sum_erase _ _ hjmem,
        ← Finset.add_sum_erase _ _ hkmem]
      -- For d₀:
      conv_rhs => rw [← Finset.add_sum_erase _ _ hjmem,
        ← Finset.add_sum_erase _ _ hkmem]
      -- The remaining sums are equal (m ≠ j, m ≠ k, so d₀' = d₀)
      -- Split into j-term, k-term, and remaining sum
      -- The j and k terms in d₀' sum cancel: (d₀(inr j) - 1) + (d₀(inr k) + 1) = d₀(inr j) + d₀(inr k)
      have hj_plus_k : d₀' (Sum.inr j) + d₀' (Sum.inr k) = d₀ (Sum.inr j) + d₀ (Sum.inr k) := by
        simp only [hd₀'_yj, hd₀'_yk]
        have h1 := hyj
        omega
      have hrest_eq : Finset.sum (Finset.univ.erase j |>.erase k) (fun m : V =>
        if compRep G S m = r' ∧ m ∉ S then d₀' (Sum.inr m : BinomialEdgeVars V) else 0) =
        Finset.sum (Finset.univ.erase j |>.erase k) (fun m : V =>
        if compRep G S m = r' ∧ m ∉ S then d₀ (Sum.inr m : BinomialEdgeVars V) else 0) := by
        apply Finset.sum_congr rfl
        intro m hm
        simp only [Finset.mem_erase] at hm
        obtain ⟨hmk, hmj, _⟩ := hm
        rw [hd₀'_other (Sum.inr m) (fun h => by cases h)
          (by intro h; exact hmj (Sum.inr.inj h)) (fun h => by cases h)
          (by intro h; exact hmk (Sum.inr.inj h))]
      simp only [if_pos hcond_j, if_pos hcond_k, hrest_eq]
      linarith [hj_plus_k]
    · -- j and k are NOT in this component: both ite conditions are false
      apply Finset.sum_congr rfl
      intro m _hm
      by_cases hmj : m = j
      · rw [hmj]
        simp only [show ¬(compRep G S j = r' ∧ j ∉ S) from fun ⟨h, _⟩ => hr h, ite_false]
      · by_cases hmk : m = k
        · rw [hmk]
          simp only [show ¬(compRep G S k = r' ∧ k ∉ S) from fun ⟨h, _⟩ => hr (hrep_eq ▸ h), ite_false]
        · rw [hd₀'_other (Sum.inr m) (fun h => by cases h)
                (by intro h; exact hmj (Sum.inr.inj h)) (fun h => by cases h)
                (by intro h; exact hmk (Sum.inr.inj h))]
  · -- S-support condition for d₀'
    have hjS : j ∉ S := hsc.1
    have hkS : k ∉ S := hsc.2.1
    constructor
    · -- d₀'(inl i) = 0
      rw [hd₀'_other (Sum.inl i) (by intro h; have := Sum.inl.inj h; subst this; exact hjS hi)
        (fun h => by cases h)
        (by intro h; have := Sum.inl.inj h; subst this; exact hkS hi)
        (fun h => by cases h)]
      exact (hS0 i hi).1
    · -- d₀'(inr i) = 0
      rw [hd₀'_other (Sum.inr i) (fun h => by cases h)
        (by intro h; have := Sum.inr.inj h; subst this; exact hjS hi)
        (fun h => by cases h)
        (by intro h; have := Sum.inr.inj h; subst this; exact hkS hi)]
      exact (hS0 i hi).2

/-- The swap decreases deviation. -/
private lemma swapExp_yDeviation_lt {d₀ d₁ d₀' : BinomialEdgeVars V →₀ ℕ} {j k : V}
    (hjk : j ≠ k)
    (hgj : d₀ (Sum.inr j : BinomialEdgeVars V) > d₁ (Sum.inr j : BinomialEdgeVars V))
    (hlk : d₀ (Sum.inr k : BinomialEdgeVars V) < d₁ (Sum.inr k : BinomialEdgeVars V))
    (hd₀' : ∀ v : BinomialEdgeVars V, d₀' v =
      d₀ v + (Finsupp.single (Sum.inl j : BinomialEdgeVars V) 1 v +
        Finsupp.single (Sum.inr k : BinomialEdgeVars V) 1 v) -
      (Finsupp.single (Sum.inr j : BinomialEdgeVars V) 1 v +
        Finsupp.single (Sum.inl k : BinomialEdgeVars V) 1 v)) :
    yDeviation (V := V) d₀' d₁ < yDeviation (V := V) d₀ d₁ := by
  have hd₀'_inr : ∀ m : V, d₀' (Sum.inr m : BinomialEdgeVars V) =
      d₀ (Sum.inr m) + (if k = m then 1 else 0) - (if j = m then 1 else 0) := by
    intro m
    have h := hd₀' (Sum.inr m : BinomialEdgeVars V)
    simp only [Finsupp.single_apply, Sum.inl_ne_inr, ↓reduceIte, Sum.inr.injEq] at h
    omega
  unfold yDeviation
  apply Finset.sum_lt_sum
  · intro m _
    rw [hd₀'_inr]
    by_cases hmj : j = m
    · subst hmj; rw [if_pos rfl, if_neg hjk.symm]; omega
    · rw [if_neg hmj]
      by_cases hmk : k = m
      · subst hmk; rw [if_pos rfl]; omega
      · rw [if_neg hmk]; omega
  · exact ⟨j, Finset.mem_univ j, by rw [hd₀'_inr, if_pos rfl, if_neg hjk.symm]; omega⟩

/-- The monomial swap lemma: fiber-equivalent monomials differ by an element of P_S(G). -/
private lemma monomial_swap_mem (G : SimpleGraph V) (S : Finset V)
    {d₀ d₁ : BinomialEdgeVars V →₀ ℕ} {c : K}
    (hfe : FiberEquiv G S d₀ d₁) :
    (monomial d₀ c - monomial d₁ c : MvPolynomial (BinomialEdgeVars V) K) ∈
      primeComponent (K := K) G S := by
  -- Strong induction on yDeviation d₀ d₁
  suffices h : ∀ (n : ℕ) (d₀ d₁ : BinomialEdgeVars V →₀ ℕ) (c : K),
      FiberEquiv G S d₀ d₁ → yDeviation (V := V) d₀ d₁ ≤ n →
      (monomial d₀ c - monomial d₁ c : MvPolynomial (BinomialEdgeVars V) K) ∈
        primeComponent (K := K) G S from h _ _ _ _ hfe le_rfl
  intro n
  induction n with
  | zero =>
    intro d₀ d₁ c hfe hle
    have hdev : yDeviation (V := V) d₀ d₁ = 0 := Nat.le_zero.mp hle
    rw [fiber_equiv_of_yDeviation_zero hfe hdev, sub_self]
    exact (primeComponent (K := K) G S).zero_mem
  | succ n ih =>
    intro d₀ d₁ c hfe hle
    by_cases hdev0 : yDeviation (V := V) d₀ d₁ = 0
    · rw [fiber_equiv_of_yDeviation_zero hfe hdev0, sub_self]
      exact (primeComponent (K := K) G S).zero_mem
    · have hpos : 0 < yDeviation (V := V) d₀ d₁ := Nat.pos_of_ne_zero hdev0
      obtain ⟨j, k, hjk, hsc, hjgt, hlk, hyj, hxk⟩ := exists_swap_vertices hfe hpos
      -- Define d₀' by swapping one x_k·y_j → x_j·y_k in d₀
      set d₀' : BinomialEdgeVars V →₀ ℕ :=
        d₀ + (Finsupp.single (Sum.inl j) 1 : BinomialEdgeVars V →₀ ℕ) +
        (Finsupp.single (Sum.inr k) 1 : BinomialEdgeVars V →₀ ℕ) -
        ((Finsupp.single (Sum.inr j) 1 : BinomialEdgeVars V →₀ ℕ) +
         (Finsupp.single (Sum.inl k) 1 : BinomialEdgeVars V →₀ ℕ)) with hd₀'_def
      -- Prove the pointwise spec for d₀'
      have hd₀'_spec : ∀ v : BinomialEdgeVars V, d₀' v =
          d₀ v + (Finsupp.single (Sum.inl j : BinomialEdgeVars V) 1 v +
            Finsupp.single (Sum.inr k : BinomialEdgeVars V) 1 v) -
          (Finsupp.single (Sum.inr j : BinomialEdgeVars V) 1 v +
            Finsupp.single (Sum.inl k : BinomialEdgeVars V) 1 v) := by
        intro v
        simp only [hd₀'_def, Finsupp.tsub_apply, Finsupp.add_apply]
        omega
      -- d₀' is fiber-equivalent to d₁
      have hfe' : FiberEquiv G S d₀' d₁ :=
        swapExp_fiberEquiv hfe hjk hsc hyj hxk hjgt hd₀'_spec
      -- yDeviation strictly decreases
      have hlt : yDeviation (V := V) d₀' d₁ < yDeviation (V := V) d₀ d₁ :=
        swapExp_yDeviation_lt hjk hjgt hlk hd₀'_spec
      -- Induction hypothesis: monomial d₀' c - monomial d₁ c ∈ P_S(G)
      have ih1 : (monomial d₀' c - monomial d₁ c : MvPolynomial (BinomialEdgeVars V) K) ∈
          primeComponent (K := K) G S :=
        ih d₀' d₁ c hfe' (by omega)
      -- Define e = d₀ with x_k and y_j subtracted (base for single_swap_mem)
      set e : BinomialEdgeVars V →₀ ℕ :=
        d₀ - (Finsupp.single (Sum.inl k) 1 : BinomialEdgeVars V →₀ ℕ) -
        (Finsupp.single (Sum.inr j) 1 : BinomialEdgeVars V →₀ ℕ) with he_def
      -- d₀ = e + single(x_k) + single(y_j)
      have hd_eq : d₀ = e + (Finsupp.single (Sum.inl k) 1 : BinomialEdgeVars V →₀ ℕ) +
          (Finsupp.single (Sum.inr j) 1 : BinomialEdgeVars V →₀ ℕ) := by
        ext v
        simp only [he_def, Finsupp.tsub_apply, Finsupp.add_apply, Finsupp.single_apply]
        by_cases h1 : (Sum.inl k : BinomialEdgeVars V) = v
        · by_cases h2 : (Sum.inr j : BinomialEdgeVars V) = v
          · exact absurd (h1.trans h2.symm) Sum.inl_ne_inr
          · simp only [if_pos h1, if_neg h2]; rw [← h1]; omega
        · by_cases h2 : (Sum.inr j : BinomialEdgeVars V) = v
          · simp only [if_neg h1, if_pos h2]; rw [← h2]; omega
          · simp only [if_neg h1, if_neg h2]; omega
      -- d₀' = e + single(x_j) + single(y_k)
      have hd'_eq : d₀' = e + (Finsupp.single (Sum.inl j) 1 : BinomialEdgeVars V →₀ ℕ) +
          (Finsupp.single (Sum.inr k) 1 : BinomialEdgeVars V →₀ ℕ) := by
        ext v
        simp only [hd₀'_def, he_def, Finsupp.tsub_apply, Finsupp.add_apply, Finsupp.single_apply]
        by_cases h1 : (Sum.inl j : BinomialEdgeVars V) = v
        · by_cases h1k : (Sum.inl k : BinomialEdgeVars V) = v
          · -- inl j = inl k → j = k, contradiction
            exact absurd (Sum.inl.inj (h1.trans h1k.symm)) hjk
          · by_cases h2j : (Sum.inr j : BinomialEdgeVars V) = v
            · exact absurd (h1.trans h2j.symm) Sum.inl_ne_inr
            · by_cases h2k : (Sum.inr k : BinomialEdgeVars V) = v
              · exact absurd (h1.trans h2k.symm) Sum.inl_ne_inr
              · simp only [if_pos h1, if_neg h1k, if_neg h2j, if_neg h2k]; rw [← h1]; omega
        · by_cases h1k : (Sum.inl k : BinomialEdgeVars V) = v
          · by_cases h2j : (Sum.inr j : BinomialEdgeVars V) = v
            · exact absurd (h1k.trans h2j.symm) Sum.inl_ne_inr
            · by_cases h2k : (Sum.inr k : BinomialEdgeVars V) = v
              · exact absurd (h1k.trans h2k.symm) Sum.inl_ne_inr
              · simp only [if_neg h1, if_pos h1k, if_neg h2j, if_neg h2k]; rw [← h1k]; omega
          · by_cases h2j : (Sum.inr j : BinomialEdgeVars V) = v
            · by_cases h2k : (Sum.inr k : BinomialEdgeVars V) = v
              · -- inr j = inr k → j = k, contradiction
                exact absurd (Sum.inr.inj (h2j.trans h2k.symm)) hjk
              · simp only [if_neg h1, if_neg h1k, if_pos h2j, if_neg h2k]; rw [← h2j]; omega
            · by_cases h2k : (Sum.inr k : BinomialEdgeVars V) = v
              · simp only [if_neg h1, if_neg h1k, if_neg h2j, if_pos h2k]; rw [← h2k]; omega
              · simp only [if_neg h1, if_neg h1k, if_neg h2j, if_neg h2k]; omega
      -- single_swap_mem: monomial d₀ c - monomial d₀' c ∈ P_S(G)
      have ih2 : (monomial d₀ c - monomial d₀' c : MvPolynomial (BinomialEdgeVars V) K) ∈
          primeComponent (K := K) G S :=
        single_swap_mem G S d₀ d₀' e c hjk hsc hd_eq hd'_eq
      -- Combine: (d₀ - d₁) = (d₀ - d₀') + (d₀' - d₁)
      have hcomb : (monomial d₀ c - monomial d₁ c : MvPolynomial (BinomialEdgeVars V) K) =
          (monomial d₀ c - monomial d₀' c) + (monomial d₀' c - monomial d₁ c) := by ring
      rw [hcomb]
      exact (primeComponent (K := K) G S).add_mem ih2 ih1

/-! #### Normalized exponent for the φ computation -/

/-- The "normalized" exponent of d: x-total per vertex, y-total per component rep. -/
private noncomputable def normExp (G : SimpleGraph V) (S : Finset V)
    (d : BinomialEdgeVars V →₀ ℕ) : BinomialEdgeVars V →₀ ℕ :=
  Finsupp.onFinset Finset.univ
    (fun v => match v with
      | Sum.inl i => d (Sum.inl i : BinomialEdgeVars V) + d (Sum.inr i : BinomialEdgeVars V)
      | Sum.inr r => Finset.univ.sum (fun i : V =>
          if compRep G S i = r ∧ i ∉ S then d (Sum.inr i : BinomialEdgeVars V) else 0))
    (fun _ _ => Finset.mem_univ _)

private lemma normExp_apply_inl (G : SimpleGraph V) (S : Finset V)
    (d : BinomialEdgeVars V →₀ ℕ) (i : V) :
    normExp G S d (Sum.inl i : BinomialEdgeVars V) =
    d (Sum.inl i : BinomialEdgeVars V) + d (Sum.inr i : BinomialEdgeVars V) := by
  simp [normExp, Finsupp.onFinset_apply]

private lemma normExp_apply_inr (G : SimpleGraph V) (S : Finset V)
    (d : BinomialEdgeVars V →₀ ℕ) (r : V) :
    normExp G S d (Sum.inr r : BinomialEdgeVars V) =
    Finset.univ.sum (fun i : V =>
      if compRep G S i = r ∧ i ∉ S then d (Sum.inr i : BinomialEdgeVars V) else 0) := by
  simp [normExp, Finsupp.onFinset_apply]

/-- FiberEquiv holds iff the normalized exponents agree (for no-S-support monomials). -/
private lemma fiberEquiv_iff_normExp_eq (G : SimpleGraph V) (S : Finset V)
    {d₀ d₁ : BinomialEdgeVars V →₀ ℕ}
    (hd₀ : ∀ i ∈ S, d₀ (Sum.inl i : BinomialEdgeVars V) = 0 ∧
                    d₀ (Sum.inr i : BinomialEdgeVars V) = 0)
    (hd₁ : ∀ i ∈ S, d₁ (Sum.inl i : BinomialEdgeVars V) = 0 ∧
                    d₁ (Sum.inr i : BinomialEdgeVars V) = 0) :
    FiberEquiv G S d₀ d₁ ↔ normExp G S d₀ = normExp G S d₁ := by
  simp only [FiberEquiv, Finsupp.ext_iff]
  constructor
  · intro ⟨htot, hcomp, _, _⟩ v
    rcases v with i | r
    · simp only [normExp_apply_inl]; exact htot i
    · simp only [normExp_apply_inr]; exact hcomp r
  · intro h
    refine ⟨fun j => ?_, fun r => ?_, hd₀, hd₁⟩
    · have := h (Sum.inl j : BinomialEdgeVars V); simp only [normExp_apply_inl] at this; exact this
    · have := h (Sum.inr r : BinomialEdgeVars V); simp only [normExp_apply_inr] at this; exact this

set_option maxHeartbeats 2000000 in
/-- `φ(monomial d 1) = monomial (normExp d) 1` for monomials with no S-support. -/
private lemma primeComponentMap_monomial_noSSupport (G : SimpleGraph V) (S : Finset V)
    {d : BinomialEdgeVars V →₀ ℕ}
    (hd : ∀ i ∈ S, d (Sum.inl i : BinomialEdgeVars V) = 0 ∧
                   d (Sum.inr i : BinomialEdgeVars V) = 0) :
    (primeComponentMap (K := K) G S) (monomial d 1) = monomial (normExp G S d) 1 := by
  simp only [primeComponentMap, aeval_monomial, map_one, one_mul]
  -- Step 1: On d.support, i ∉ S, so simplify the if-else branches
  have hcongr : d.prod (fun i k =>
        (match i with
          | Sum.inl i => if i ∈ S then (0 : MvPolynomial (BinomialEdgeVars V) K) else X (Sum.inl i)
          | Sum.inr i =>
            if i ∈ S then 0 else X (Sum.inl i) * X (Sum.inr (compRep G S i))) ^ k) =
      d.prod (fun i k =>
        (match i with
          | Sum.inl i => (X (Sum.inl i) : MvPolynomial (BinomialEdgeVars V) K)
          | Sum.inr i => X (Sum.inl i) * X (Sum.inr (compRep G S i))) ^ k) := by
    apply Finsupp.prod_congr
    intro j hj
    rcases j with i | i
    · have hiS : i ∉ S := fun hiS => Finsupp.mem_support_iff.mp hj (hd i hiS).1
      simp [hiS]
    · have hiS : i ∉ S := fun hiS => Finsupp.mem_support_iff.mp hj (hd i hiS).2
      simp [hiS]
  rw [hcongr]
  -- Step 2: Extend LHS product to Finset.univ
  rw [Finsupp.prod_of_support_subset d (Finset.subset_univ _) _
      (fun j _ => by rcases j with i | i <;> simp)]
  -- Step 3: Write RHS monomial as product over Finset.univ
  conv_rhs =>
    rw [← MvPolynomial.prod_X_pow_eq_monomial,
        Finset.prod_subset (Finset.subset_univ _) (fun j _ hj =>
          show X j ^ (normExp G S d) j = 1 from by
            simp only [Finsupp.mem_support_iff, not_not] at hj
            rw [hj, pow_zero])]
  -- Step 4: Change BinomialEdgeVars V to V ⊕ V and split by inl/inr
  change (∏ j : V ⊕ V, _) = ∏ j : V ⊕ V, _
  simp only [Fintype.prod_sum_type]
  -- LHS: (∏ i, X(inl i)^d(inl i)) * (∏ i, (X(inl i)*X(inr(rep i)))^d(inr i))
  -- RHS: (∏ i, X(inl i)^normExp(inl i)) * (∏ r, X(inr r)^normExp(inr r))
  -- Step 5: Expand mul_pow and combine x-exponents
  simp_rw [mul_pow]
  rw [Finset.prod_mul_distrib, ← mul_assoc, ← Finset.prod_mul_distrib]
  simp_rw [← pow_add, ← normExp_apply_inl G S d]
  congr 1
  -- Step 6: Prove y-parts match using prod_fiberwise
  simp_rw [normExp_apply_inr]
  rw [← Finset.prod_fiberwise_of_maps_to (g := compRep G S)
      (f := fun i => X (Sum.inr (compRep G S i) : BinomialEdgeVars V) ^
                     d (Sum.inr i : BinomialEdgeVars V))
      (fun _ _ => Finset.mem_univ _)]
  apply Finset.prod_congr rfl
  intro r _
  -- Replace compRep G S i with r inside the fiber
  rw [show ∏ i ∈ Finset.univ.filter (fun i => compRep G S i = r),
          X (Sum.inr (compRep G S i) : BinomialEdgeVars V) ^ d (Sum.inr i : BinomialEdgeVars V) =
      ∏ i ∈ Finset.univ.filter (fun i => compRep G S i = r),
          X (Sum.inr r : BinomialEdgeVars V) ^ d (Sum.inr i : BinomialEdgeVars V) from
    Finset.prod_congr rfl (fun i hi => by
      simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hi; rw [hi])]
  rw [Finset.prod_pow_eq_pow_sum]
  congr 1
  -- Sum equality: ∑ i ∈ filter(rep = r), d(inr i) = ∑ k, if rep k = r ∧ k ∉ S then d(inr k) else 0
  rw [Finset.sum_filter]
  apply Finset.sum_congr rfl
  intro k _
  by_cases hkr : compRep G S k = r
  · by_cases hkS : k ∈ S
    · simp [hkr, hkS, (hd k hkS).2]
    · simp [hkr, hkS]
  · simp [hkr]

/-! #### Main proof: ker(φ) ≤ P_S(G) -/

/-- φ sends monomials with S-support to 0. -/
private lemma primeComponentMap_S_support_zero (G : SimpleGraph V) (S : Finset V)
    {d : BinomialEdgeVars V →₀ ℕ} (c : K)
    (hS : ∃ i ∈ S, d (Sum.inl i : BinomialEdgeVars V) ≥ 1 ∨
                   d (Sum.inr i : BinomialEdgeVars V) ≥ 1) :
    (primeComponentMap (K := K) G S) (monomial d c) = 0 := by
  simp only [primeComponentMap, aeval_monomial, smul_eq_mul]
  obtain ⟨i, hiS, hi⟩ := hS
  rcases hi with hi | hi
  · -- d(inl i) ≥ 1: the factor for inl i is 0^(≥1) = 0
    apply mul_eq_zero_of_right
    unfold Finsupp.prod
    apply Finset.prod_eq_zero (Finsupp.mem_support_iff.mpr (Nat.one_le_iff_ne_zero.mp hi))
    simp [hiS, zero_pow (Nat.one_le_iff_ne_zero.mp hi)]
  · -- d(inr i) ≥ 1
    apply mul_eq_zero_of_right
    unfold Finsupp.prod
    apply Finset.prod_eq_zero (Finsupp.mem_support_iff.mpr (Nat.one_le_iff_ne_zero.mp hi))
    simp [hiS, zero_pow (Nat.one_le_iff_ne_zero.mp hi)]

set_option maxHeartbeats 2000000 in
/-- Helper: fiber sums of no-S-support monomials in kernel are in P_S(G).
    Strong induction on T.card. -/
private lemma no_s_ker_mem (G : SimpleGraph V) (S : Finset V) :
    ∀ (T : Finset (BinomialEdgeVars V →₀ ℕ)),
    ∀ (c : (BinomialEdgeVars V →₀ ℕ) → K),
    (∀ d ∈ T, ∀ i ∈ S, d (Sum.inl i : BinomialEdgeVars V) = 0 ∧
                        d (Sum.inr i : BinomialEdgeVars V) = 0) →
    (∀ e : BinomialEdgeVars V →₀ ℕ,
        ∑ d ∈ T.filter (fun d => normExp G S d = e), c d = 0) →
    ∑ d ∈ T, c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) ∈
        primeComponent (K := K) G S := by
  suffices h : ∀ (n : ℕ) (T : Finset (BinomialEdgeVars V →₀ ℕ)), T.card ≤ n →
      ∀ (c : (BinomialEdgeVars V →₀ ℕ) → K),
      (∀ d ∈ T, ∀ i ∈ S, d (Sum.inl i : BinomialEdgeVars V) = 0 ∧
                          d (Sum.inr i : BinomialEdgeVars V) = 0) →
      (∀ e : BinomialEdgeVars V →₀ ℕ,
          ∑ d ∈ T.filter (fun d => normExp G S d = e), c d = 0) →
      ∑ d ∈ T, c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) ∈
          primeComponent (K := K) G S from
    fun T c hT hker => h T.card T le_rfl c hT hker
  intro n
  induction n with
  | zero =>
    intro T hTn c _ _
    simp [Finset.card_eq_zero.mp (Nat.le_zero.mp hTn)]
  | succ n ih_n =>
  intro T hTn c hT hker
  rcases Finset.eq_empty_or_nonempty T with rfl | ⟨d₀, hd₀T⟩
  · simp
  · have hT_erase_card : (T.erase d₀).card ≤ n := by
      rw [Finset.card_erase_of_mem hd₀T]; omega
    by_cases hc₀ : c d₀ = 0
    · -- d₀ contributes 0; remove it
      rw [← Finset.add_sum_erase T _ hd₀T, hc₀, zero_smul, zero_add]
      apply ih_n (T.erase d₀) hT_erase_card
      · intro d hd; exact hT d (Finset.mem_of_mem_erase hd)
      · intro e
        have hfib : (T.erase d₀).filter (fun d => normExp G S d = e) =
                    (T.filter (fun d => normExp G S d = e)).erase d₀ := by
          ext d; simp only [Finset.mem_filter, Finset.mem_erase]
          exact ⟨fun ⟨⟨hne, hd⟩, hn⟩ => ⟨hne, hd, hn⟩, fun ⟨hne, hd, hn⟩ => ⟨⟨hne, hd⟩, hn⟩⟩
        rw [hfib]
        by_cases hd₀e : d₀ ∈ T.filter (fun d => normExp G S d = e)
        · have heq := Finset.add_sum_erase (T.filter (fun d => normExp G S d = e)) hd₀e (f := c)
          rw [hc₀, zero_add] at heq; rw [heq]; exact hker e
        · rw [Finset.erase_eq_of_notMem hd₀e]; exact hker e
    · -- c d₀ ≠ 0: find d₁ in T with same normExp
      -- Fiber sum = 0 and c d₀ ≠ 0 → fiber has another element
      have hfib0 := hker (normExp G S d₀)
      have hd₀_in_fib : d₀ ∈ T.filter (fun d => normExp G S d = normExp G S d₀) := by
        simp [hd₀T]
      have hfib_minus : ∑ d ∈ (T.filter (fun d => normExp G S d = normExp G S d₀)).erase d₀, c d = -c d₀ := by
        have heq := Finset.add_sum_erase (T.filter (fun d => normExp G S d = normExp G S d₀)) hd₀_in_fib (f := c)
        rw [hfib0] at heq
        exact eq_neg_of_add_eq_zero_right heq
      have hfib_ne : ((T.filter (fun d => normExp G S d = normExp G S d₀)).erase d₀).Nonempty := by
        by_contra h_empty
        push_neg at h_empty
        -- After push_neg, h_empty : ... = ∅
        rw [h_empty] at hfib_minus
        simp [hc₀] at hfib_minus
      obtain ⟨d₁, hd₁_mem⟩ := hfib_ne
      have hd₁_fib := Finset.mem_of_mem_erase hd₁_mem
      have hd₁T : d₁ ∈ T := (Finset.mem_filter.mp hd₁_fib).1
      have hd₁_norm : normExp G S d₁ = normExp G S d₀ := (Finset.mem_filter.mp hd₁_fib).2
      have hd₁_ne : d₁ ≠ d₀ := Finset.ne_of_mem_erase hd₁_mem
      -- FiberEquiv d₀ d₁ from equal normExp
      have hd₀_noS := hT d₀ hd₀T
      have hd₁_noS := hT d₁ hd₁T
      have hfe : FiberEquiv G S d₀ d₁ :=
        (fiberEquiv_iff_normExp_eq G S hd₀_noS hd₁_noS).mpr hd₁_norm.symm
      -- Key: remove d₀ from T, adjust c at d₁, subtract c d₀ * (monomial d₀ - monomial d₁)
      let c' : (BinomialEdgeVars V →₀ ℕ) → K := fun d =>
        if d = d₀ then 0 else if d = d₁ then c d₁ + c d₀ else c d
      -- Decomposition: ∑_T c d * mon d = c d₀ * (mon d₀ - mon d₁) + ∑_{T.erase d₀} c' d * mon d
      have hdecomp : ∑ d ∈ T, c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) =
          c d₀ • (monomial d₀ 1 - monomial d₁ 1) +
          ∑ d ∈ T.erase d₀, c' d • monomial d 1 := by
        have hd₁_in_erase : d₁ ∈ T.erase d₀ := Finset.mem_erase.mpr ⟨hd₁_ne, hd₁T⟩
        have hc'_d₁ : c' d₁ = c d₁ + c d₀ := by simp [c', if_neg hd₁_ne]
        have hc'_rest : ∀ d ∈ (T.erase d₀).erase d₁,
            c' d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) =
            c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) := by
          intro d hd
          simp only [Finset.mem_erase] at hd
          have hdd₀ : d ≠ d₀ := hd.2.1
          have hdd₁ : d ≠ d₁ := hd.1
          simp only [c', if_neg hdd₀, if_neg hdd₁]
        -- Step: ∑_{T.erase d₀} c' d • m d = ∑_{T.erase d₀} c d • m d + c d₀ • m d₁
        have hsum_diff : ∑ d ∈ T.erase d₀, c' d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) =
            ∑ d ∈ T.erase d₀, c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) +
            c d₀ • (monomial d₁ 1 : MvPolynomial (BinomialEdgeVars V) K) := by
          have step1 : ∑ d ∈ T.erase d₀, c' d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) =
              (c d₁ + c d₀) • (monomial d₁ 1 : MvPolynomial (BinomialEdgeVars V) K) +
              ∑ d ∈ (T.erase d₀).erase d₁, c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) :=
            calc ∑ d ∈ T.erase d₀, c' d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K)
                = c' d₁ • (monomial d₁ 1 : MvPolynomial (BinomialEdgeVars V) K) +
                  ∑ d ∈ (T.erase d₀).erase d₁, c' d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) :=
                  (Finset.add_sum_erase (T.erase d₀) hd₁_in_erase
                      (f := fun d => c' d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K))).symm
              _ = (c d₁ + c d₀) • (monomial d₁ 1 : MvPolynomial (BinomialEdgeVars V) K) +
                  ∑ d ∈ (T.erase d₀).erase d₁, c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) := by
                  rw [hc'_d₁]; congr 1; exact Finset.sum_congr rfl hc'_rest
          have h_ase := Finset.add_sum_erase (T.erase d₀) hd₁_in_erase
              (f := fun d => c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K))
          rw [step1, add_smul]
          linear_combination h_ase
        rw [hsum_diff, ← Finset.add_sum_erase T hd₀T
            (f := fun d => c d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K))]
        simp only [smul_sub]; abel
      rw [hdecomp]
      apply (primeComponent (K := K) G S).add_mem
      · -- c d₀ * (monomial d₀ 1 - monomial d₁ 1) ∈ P_S(G)
        rw [Algebra.smul_def]
        exact (primeComponent (K := K) G S).mul_mem_left _ (monomial_swap_mem G S hfe)
      · -- ∑_{T.erase d₀} c' d * monomial d 1 ∈ P_S(G) by IH
        apply ih_n (T.erase d₀) hT_erase_card
        · intro d hd; exact hT d (Finset.mem_of_mem_erase hd)
        · intro e
          -- Case split on e = normExp d₀
          by_cases he : e = normExp G S d₀
          · -- e = normExp G S d₀
            subst he
            -- Rewrite filter of T.erase d₀ as filter of T with d₀ erased
            have hfib_eq : (T.erase d₀).filter (fun d => normExp G S d = normExp G S d₀) =
                (T.filter (fun d => normExp G S d = normExp G S d₀)).erase d₀ := by
              ext x; simp only [Finset.mem_filter, Finset.mem_erase]; tauto
            have hd₁_in : d₁ ∈ (T.filter (fun d => normExp G S d = normExp G S d₀)).erase d₀ :=
              Finset.mem_erase.mpr ⟨hd₁_ne, hd₁_fib⟩
            rw [hfib_eq, ← Finset.add_sum_erase _ hd₁_in (f := c'),
                show c' d₁ = c d₁ + c d₀ from by simp [c', if_neg hd₁_ne]]
            -- For remaining elements (≠ d₁, ≠ d₀), c' d = c d
            have hrest_eq : ∑ d ∈ ((T.filter (fun d => normExp G S d = normExp G S d₀)).erase d₀).erase d₁,
                c' d = ∑ d ∈ ((T.filter (fun d => normExp G S d = normExp G S d₀)).erase d₀).erase d₁,
                c d := by
              apply Finset.sum_congr rfl
              intro d hd
              simp only [Finset.mem_erase] at hd
              simp only [c', if_neg hd.2.1, if_neg hd.1]
            rw [hrest_eq]
            -- Use hfib_minus: ∑ (T.filter.erase d₀), c d = -c d₀
            have hkey : c d₁ + ∑ d ∈
                ((T.filter (fun d => normExp G S d = normExp G S d₀)).erase d₀).erase d₁, c d =
                -c d₀ :=
              (Finset.add_sum_erase _ hd₁_in (f := c)).trans hfib_minus
            linear_combination hkey
          · -- e ≠ normExp G S d₀: d₁ and d₀ not in (T.erase d₀).filter(normExp = e)
            -- (T.erase d₀).filter(normExp = e) = T.filter(normExp = e)
            have hfib_eq' : (T.erase d₀).filter (fun d => normExp G S d = e) =
                T.filter (fun d => normExp G S d = e) := by
              ext x; simp only [Finset.mem_filter, Finset.mem_erase]
              constructor
              · intro ⟨⟨_, hxT⟩, hn⟩; exact ⟨hxT, hn⟩
              · intro ⟨hxT, hn⟩; exact ⟨⟨fun hxd₀ => he (hxd₀ ▸ hn).symm, hxT⟩, hn⟩
            rw [hfib_eq']
            -- For d in T.filter(normExp = e): d ≠ d₀ and d ≠ d₁, so c' d = c d
            have hconv : ∀ d ∈ T.filter (fun d => normExp G S d = e), c' d = c d := by
              intro d hd
              simp only [Finset.mem_filter] at hd
              have hdd₀ : d ≠ d₀ := fun h => he (h ▸ hd.2).symm
              have hdd₁ : d ≠ d₁ := by
                intro h; subst h; exact he (hd₁_norm.symm.trans hd.2).symm
              simp only [c', if_neg hdd₀, if_neg hdd₁]
            rw [Finset.sum_congr rfl hconv]
            exact hker e

-- The hard direction: ker(primeComponentMap) ⊆ P_S(G).
set_option maxHeartbeats 2000000 in
private lemma ker_primeComponentMap_le (G : SimpleGraph V) (S : Finset V) :
    RingHom.ker (primeComponentMap (K := K) G S).toRingHom ≤ primeComponent (K := K) G S := by
  intro f hf
  simp only [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at hf
  -- Split f.support into S-support and no-S-support parts
  set T_S := f.support.filter (fun d => ∃ i ∈ S, d (Sum.inl i : BinomialEdgeVars V) ≥ 1 ∨
                                                   d (Sum.inr i : BinomialEdgeVars V) ≥ 1) with hTS_def
  set T_N := f.support.filter (fun d => ∀ i ∈ S, d (Sum.inl i : BinomialEdgeVars V) = 0 ∧
                                                   d (Sum.inr i : BinomialEdgeVars V) = 0) with hTN_def
  -- f = ∑_{T_S} + ∑_{T_N}
  have hf_split : f = ∑ d ∈ T_S, monomial d (f.coeff d) +
                      ∑ d ∈ T_N, monomial d (f.coeff d) := by
    rw [← Finset.sum_union]
    · conv_lhs => rw [f.as_sum]
      apply Finset.sum_congr _ (fun _ _ => rfl)
      ext d; simp only [T_S, T_N, Finset.mem_union, Finset.mem_filter]
      constructor
      · intro hd
        by_cases hS : ∃ i ∈ S, d (Sum.inl i : BinomialEdgeVars V) ≥ 1 ∨
                                d (Sum.inr i : BinomialEdgeVars V) ≥ 1
        · left; exact ⟨hd, hS⟩
        · right; push_neg at hS
          exact ⟨hd, fun i hiS => ⟨by have := (hS i hiS).1; omega,
                                   by have := (hS i hiS).2; omega⟩⟩
      · intro h; rcases h with ⟨h, _⟩ | ⟨h, _⟩ <;> exact h
    · simp only [T_S, T_N, Finset.disjoint_filter]
      intro d _ ⟨i, hiS, hi⟩ hN
      obtain ⟨h1, h2⟩ := hN i hiS
      rcases hi with h | h <;> omega
  -- The S-support part is in P_S(G)
  have hA_mem : ∑ d ∈ T_S, monomial d (f.coeff d) ∈ primeComponent (K := K) G S := by
    apply Submodule.sum_mem
    intro d hd
    simp only [T_S, Finset.mem_filter] at hd
    obtain ⟨_, i, hiS, hi⟩ := hd
    exact monomial_S_support_mem G S d (f.coeff d) hiS hi
  -- The no-S-support part is in P_S(G) by the inductive helper
  have hB_mem : ∑ d ∈ T_N, monomial d (f.coeff d) ∈ primeComponent (K := K) G S := by
    -- Rewrite as scalar multiples
    have hB_form : ∑ d ∈ T_N, monomial d (f.coeff d) =
        ∑ d ∈ T_N, f.coeff d • (monomial d 1 : MvPolynomial (BinomialEdgeVars V) K) := by
      apply Finset.sum_congr rfl
      intro d _; simp [smul_monomial]
    rw [hB_form]
    apply no_s_ker_mem G S T_N (fun d => f.coeff d)
    · intro d hd; simp only [T_N, Finset.mem_filter] at hd; exact hd.2
    · -- The fiber sums are 0: extract from φ(f) = 0
      intro e
      -- φ applied to the S-support part = 0
      have hA_ker : (primeComponentMap (K := K) G S)
          (∑ d ∈ T_S, monomial d (f.coeff d)) = 0 := by
        simp only [map_sum]
        apply Finset.sum_eq_zero
        intro d hd
        simp only [T_S, Finset.mem_filter] at hd
        obtain ⟨_, i, hiS, hi⟩ := hd
        exact primeComponentMap_S_support_zero G S (f.coeff d) ⟨i, hiS, hi⟩
      -- φ(f) = φ(A) + φ(B) = 0 + φ(B), so φ(B) = 0
      have hB_ker : (primeComponentMap (K := K) G S)
          (∑ d ∈ T_N, monomial d (f.coeff d)) = 0 := by
        have := congr_arg (primeComponentMap (K := K) G S) hf_split
        simp only [map_add] at this
        rw [hf, hA_ker, zero_add] at this
        exact this.symm
      -- Compute φ(B) using primeComponentMap_monomial_noSSupport
      have hB_phi : (primeComponentMap (K := K) G S)
          (∑ d ∈ T_N, monomial d (f.coeff d)) =
          ∑ d ∈ T_N, f.coeff d • monomial (normExp G S d) 1 := by
        simp only [map_sum]
        apply Finset.sum_congr rfl
        intro d hd
        simp only [T_N, Finset.mem_filter] at hd
        rw [show monomial d (f.coeff d) = f.coeff d • monomial d 1 from by simp [smul_monomial]]
        simp only [map_smul]
        congr 1
        exact primeComponentMap_monomial_noSSupport G S hd.2
      rw [hB_phi] at hB_ker
      -- From ∑ c_d * monomial(normExp d) 1 = 0, extract coefficient of monomial e 1
      have hcoeff : MvPolynomial.coeff e
          (∑ d ∈ T_N, f.coeff d • (monomial (normExp G S d) 1 :
              MvPolynomial (BinomialEdgeVars V) K)) = 0 := by
        rw [hB_ker]; simp
      simp only [MvPolynomial.smul_eq_C_mul, coeff_sum, coeff_C_mul,
                 coeff_monomial] at hcoeff
      rw [Finset.sum_filter]
      trans (∑ x ∈ T_N, f.coeff x * if normExp G S x = e then 1 else 0)
      · apply Finset.sum_congr rfl
        intro d _
        split_ifs <;> ring
      · exact hcoeff
  -- Combine: f = A + B, both in P_S(G)
  rw [hf_split]
  exact (primeComponent (K := K) G S).add_mem hA_mem hB_mem

end ker_helpers

/-- `P_S(G)` is a prime ideal.

The proof constructs a ring homomorphism `φ : K[x,y] → K[x,y]` (see `primeComponentMap`)
with `ker(φ) = P_S(G)`. Since the target `K[x,y]` is an integral domain,
`ker(φ)` is prime by `RingHom.ker_isPrime`. -/
theorem primeComponent_isPrime (G : SimpleGraph V) (S : Finset V) :
    (primeComponent (K := K) G S).IsPrime := by
  have heq : primeComponent (K := K) G S =
      RingHom.ker (primeComponentMap (K := K) G S).toRingHom := by
    exact le_antisymm (primeComponent_le_ker G S) (ker_primeComponentMap_le G S)
  rw [heq]
  exact RingHom.ker_isPrime _

/-- `P_S(G) = ker(primeComponentMap G S)`. -/
theorem primeComponent_eq_ker (G : SimpleGraph V) (S : Finset V) :
    primeComponent (K := K) G S =
      RingHom.ker (primeComponentMap (K := K) G S).toRingHom :=
  le_antisymm (primeComponent_le_ker G S) (ker_primeComponentMap_le G S)

/-- `J_G ⊆ P_S(G)` for every subset S. -/
theorem binomialEdgeIdeal_le_primeComponent (G : SimpleGraph V) (S : Finset V) :
    binomialEdgeIdeal (K := K) G ≤ primeComponent (K := K) G S := by
  apply Ideal.span_le.mpr
  intro f hf
  obtain ⟨i, j, hAdj, hij, rfl⟩ := hf
  -- f = x i * y j - x j * y i, with G.Adj i j and i < j
  by_cases hiS : i ∈ S
  · -- i ∈ S: X(Sum.inl i) and X(Sum.inr i) are generators of P_S(G)
    have hxi : X (Sum.inl i) ∈ primeComponent (K := K) G S :=
      Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inl rfl⟩)
    have hyi : X (Sum.inr i) ∈ primeComponent (K := K) G S :=
      Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inr rfl⟩)
    -- x i * y j = X(Sum.inl i) * y j ∈ P_S(G) since X(Sum.inl i) ∈ P_S(G)
    -- x j * y i = x j * X(Sum.inr i) ∈ P_S(G) since X(Sum.inr i) ∈ P_S(G)
    apply (primeComponent (K := K) G S).sub_mem
    · exact Ideal.mul_mem_right _ _ hxi
    · exact (primeComponent (K := K) G S).mul_mem_left _ hyi
  · by_cases hjS : j ∈ S
    · -- j ∈ S: X(Sum.inl j) and X(Sum.inr j) are generators of P_S(G)
      have hxj : X (Sum.inl j) ∈ primeComponent (K := K) G S :=
        Ideal.subset_span (Set.mem_union_left _ ⟨j, hjS, Or.inl rfl⟩)
      have hyj : X (Sum.inr j) ∈ primeComponent (K := K) G S :=
        Ideal.subset_span (Set.mem_union_left _ ⟨j, hjS, Or.inr rfl⟩)
      apply (primeComponent (K := K) G S).sub_mem
      · exact (primeComponent (K := K) G S).mul_mem_left _ hyj
      · exact Ideal.mul_mem_right _ _ hxj
    · -- i ∉ S and j ∉ S: the generator is directly in P_S(G) via SameComponent
      -- i and j are adjacent in G and both not in S, so they are in the same
      -- connected component of G[V \ S]
      apply Ideal.subset_span
      exact Set.mem_union_right _
        ⟨i, j, hij, ⟨hiS, hjS, Relation.ReflTransGen.single ⟨hAdj, hiS, hjS⟩⟩, rfl⟩

/-! ## Variable non-membership lemmas for P_S(G) -/

/-- `x_v ∉ P_S(G)` when `v ∉ S`. This follows because `primeComponentMap` sends
`X(inl v)` to `X(inl v) ≠ 0`, so `X(inl v) ∉ ker(primeComponentMap) = P_S`. -/
theorem X_inl_not_mem_primeComponent (G : SimpleGraph V) (S : Finset V)
    {v : V} (hv : v ∉ S) :
    (X (Sum.inl v) : MvPolynomial (BinomialEdgeVars V) K) ∉ primeComponent G S := by
  intro h
  have hle := primeComponent_le_ker (K := K) G S
  have hker : (primeComponentMap (K := K) G S).toRingHom (X (Sum.inl v)) = 0 :=
    RingHom.mem_ker.mp (hle h)
  simp only [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
    primeComponentMap, aeval_X, hv, ite_false] at hker
  exact X_ne_zero _ hker

/-- `y_v ∉ P_S(G)` when `v ∉ S`. This follows because `primeComponentMap` sends
`X(inr v)` to `X(inl v) * X(inr (compRep G S v)) ≠ 0`. -/
theorem X_inr_not_mem_primeComponent (G : SimpleGraph V) (S : Finset V)
    {v : V} (hv : v ∉ S) :
    (X (Sum.inr v) : MvPolynomial (BinomialEdgeVars V) K) ∉ primeComponent G S := by
  intro h
  have hle := primeComponent_le_ker (K := K) G S
  have hker : (primeComponentMap (K := K) G S).toRingHom (X (Sum.inr v)) = 0 :=
    RingHom.mem_ker.mp (hle h)
  simp only [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
    primeComponentMap, aeval_X, hv, ite_false] at hker
  exact mul_ne_zero (X_ne_zero _) (X_ne_zero _) hker

/-! ## Lemma 3.1: Height formula -/

section lemma31

open Classical in
/-- The column-representative generating set for P_S(G).
Contains variable generators `{x_i, y_i : i ∈ S}` and column-representative
binomial generators `{x_{rep(v)} y_v - x_v y_{rep(v)} : v ∉ S, v ≠ rep(v)}`. -/
private def genSet31 (G : SimpleGraph V) (S : Finset V) :
    Set (MvPolynomial (BinomialEdgeVars V) K) :=
  { f | ∃ i ∈ S, f = X (Sum.inl i) ∨ f = X (Sum.inr i) } ∪
  { f | ∃ v : V, v ∉ S ∧ v ≠ compRep G S v ∧
    f = x (compRep G S v) * y v - x v * y (compRep G S v) }

open Classical in
private lemma genSet31_finite (G : SimpleGraph V) (S : Finset V) :
    (genSet31 (K := K) G S).Finite := by
  unfold genSet31
  apply Set.Finite.union
  · -- Variable part: subset of a finite set
    refine Set.Finite.subset (Set.Finite.union
      (S.finite_toSet.image (fun i => (X (Sum.inl i) : MvPolynomial (BinomialEdgeVars V) K)))
      (S.finite_toSet.image (fun i => (X (Sum.inr i) : MvPolynomial (BinomialEdgeVars V) K))))
      ?_
    intro f hf
    simp only [Set.mem_setOf_eq] at hf
    obtain ⟨i, hiS, rfl | rfl⟩ := hf
    · exact Set.mem_union_left _ (Set.mem_image_of_mem _ hiS)
    · exact Set.mem_union_right _ (Set.mem_image_of_mem _ hiS)
  · -- Binomial part: image of a finite set
    have h2 : { f : MvPolynomial (BinomialEdgeVars V) K |
        ∃ v : V, v ∉ S ∧ v ≠ compRep G S v ∧
          f = x (compRep G S v) * y v - x v * y (compRep G S v) } ⊆
        Set.range (fun v : V =>
          x (K := K) (compRep G S v) * y v - x v * y (compRep G S v)) := by
      intro f hf
      obtain ⟨v, _, _, rfl⟩ := hf
      exact ⟨v, rfl⟩
    exact (Set.finite_range _).subset h2

open Classical in
/-- `compRep G S` is idempotent on `V \ S`. -/
private lemma compRep_idempotent (G : SimpleGraph V) (S : Finset V)
    {v : V} (hv : v ∉ S) : compRep G S (compRep G S v) = compRep G S v :=
  (compRep_eq_of_sameComponent G S (sameComponent_compRep G S hv)).symm

open Classical in
/-- `SameComponent` implies reachability in the induced subgraph `G[V \ S]`. -/
private lemma sameComponent_imp_reachable_induce (G : SimpleGraph V) (S : Finset V)
    {a b : V} (ha : a ∉ S) (hb : b ∉ S)
    (h : Relation.ReflTransGen (fun x y => G.Adj x y ∧ x ∉ S ∧ y ∉ S) a b) :
    (G.induce {w : V | w ∉ S}).Reachable ⟨a, ha⟩ ⟨b, hb⟩ := by
  revert hb
  induction h with
  | refl => intro hb'; exact SimpleGraph.Reachable.refl _
  | @tail c d _ hcd ih =>
    intro hd
    exact (ih hcd.2.1).trans
      (SimpleGraph.Adj.reachable (SimpleGraph.induce_adj.mpr hcd.1))

open Classical in
/-- Reachability in `G.induce (V \ S)` implies `SameComponent`. -/
lemma reachable_induce_imp_sameComponent (G : SimpleGraph V) (S : Finset V)
    {u v : {w : V // w ∉ S}} (hr : (G.induce {w : V | w ∉ S}).Reachable u v) :
    SameComponent G S u.val v.val := by
  rw [SimpleGraph.reachable_iff_reflTransGen] at hr
  induction hr with
  | refl => exact ⟨u.2, u.2, .refl⟩
  | @tail a b _ hab ih =>
    exact ih.trans ⟨ih.2.1, b.2,
      .single ⟨SimpleGraph.induce_adj.mp hab, a.2, b.2⟩⟩

open Classical in
/-- `componentCount G S ≤` number of `compRep` fixed points in `V \ S`. -/
lemma componentCount_le_fixedPoints (G : SimpleGraph V) (S : Finset V) :
    componentCount G S ≤
      (Finset.univ.filter (fun v => v ∉ S ∧ compRep G S v = v)).card := by
  set G' := G.induce {v : V | v ∉ S}
  set fp := Finset.univ.filter (fun v : V => v ∉ S ∧ compRep G S v = v)
  -- Well-definedness: compRep is constant on connected components
  have hwd : ∀ u v : {w : V // w ∉ S}, G'.Reachable u v →
      compRep G S u.val = compRep G S v.val :=
    fun u v hr => compRep_eq_of_sameComponent G S
      (reachable_induce_imp_sameComponent G S hr)
  -- Define the map: ConnectedComponent → V via Quot.lift
  set f : G'.ConnectedComponent → V :=
    Quot.lift (fun v : {w : V // w ∉ S} => compRep G S v.val) hwd
  -- f maps into fp
  have hf_mem : ∀ c : G'.ConnectedComponent, f c ∈ fp := by
    intro c; obtain ⟨v, rfl⟩ := Quot.mk_surjective c
    simp only [f, Quot.lift_mk, Finset.mem_filter, Finset.mem_univ, true_and, fp]
    exact ⟨(sameComponent_compRep G S v.2).2.1, compRep_idempotent G S v.2⟩
  -- f is injective
  have hf_inj : Function.Injective f := by
    intro c₁ c₂ heq
    obtain ⟨u, rfl⟩ := Quot.mk_surjective c₁
    obtain ⟨v, rfl⟩ := Quot.mk_surjective c₂
    simp only [f, Quot.lift_mk] at heq
    have hsc := sameComponent_of_compRep_eq G S u.2 v.2 heq
    exact Quot.sound (sameComponent_imp_reachable_induce G S hsc.1 hsc.2.1 hsc.2.2)
  -- componentCount = Nat.card G'.ConnectedComponent ≤ fp.card
  unfold componentCount
  rw [Nat.card_eq_fintype_card]
  have hinj' : Function.Injective (fun c : G'.ConnectedComponent => (⟨f c, hf_mem c⟩ : fp)) :=
    fun c₁ c₂ h => hf_inj (congr_arg Subtype.val h)
  calc Fintype.card G'.ConnectedComponent
      ≤ Fintype.card fp := Fintype.card_le_of_injective _ hinj'
    _ = fp.card := Fintype.card_coe fp

open Classical in
private lemma genSet31_ncard_le (G : SimpleGraph V) (S : Finset V) :
    (genSet31 (K := K) G S).ncard ≤ S.card + (Fintype.card V - componentCount G S) := by
  -- Abbreviations
  set varPart := { f : MvPolynomial (BinomialEdgeVars V) K |
    ∃ i ∈ S, f = X (Sum.inl i) ∨ f = X (Sum.inr i) }
  set binPart := { f : MvPolynomial (BinomialEdgeVars V) K |
    ∃ v : V, v ∉ S ∧ v ≠ compRep G S v ∧
      f = x (compRep G S v) * y v - x v * y (compRep G S v) }
  -- Union bound
  have h1 : (genSet31 (K := K) G S).ncard ≤ varPart.ncard + binPart.ncard :=
    Set.ncard_union_le _ _
  -- Variable part bound: ncard ≤ 2|S|
  have hvar : varPart.ncard ≤ 2 * S.card := by
    set sLR := S.image (fun i => (X (Sum.inl i) : MvPolynomial (BinomialEdgeVars V) K)) ∪
               S.image (fun i => (X (Sum.inr i) : MvPolynomial (BinomialEdgeVars V) K))
    have hsub : varPart ⊆ ↑sLR := by
      intro f hf
      obtain ⟨i, hiS, rfl | rfl⟩ := hf
      · exact Finset.mem_coe.mpr (Finset.mem_union_left _ (Finset.mem_image_of_mem _ hiS))
      · exact Finset.mem_coe.mpr (Finset.mem_union_right _ (Finset.mem_image_of_mem _ hiS))
    calc varPart.ncard
        ≤ (↑sLR : Set _).ncard := Set.ncard_le_ncard hsub (Finset.finite_toSet _)
      _ = sLR.card := Set.ncard_coe_finset _
      _ ≤ (S.image _).card + (S.image _).card := Finset.card_union_le _ _
      _ ≤ S.card + S.card := Nat.add_le_add Finset.card_image_le Finset.card_image_le
      _ = 2 * S.card := by ring
  -- Binomial part bound: ncard ≤ |{v ∉ S : v ≠ rep v}|
  have hbin : binPart.ncard ≤
      (Finset.univ.filter (fun v : V => v ∉ S ∧ v ≠ compRep G S v)).card := by
    have hfin_bin : binPart.Finite :=
      (genSet31_finite (K := K) G S).subset Set.subset_union_right
    have hsub : binPart ⊆ (fun v : V =>
        (x (K := K) (compRep G S v) * y v - x v * y (compRep G S v))) ''
        ↑(Finset.univ.filter (fun v : V => v ∉ S ∧ v ≠ compRep G S v)) := by
      intro f hf
      obtain ⟨v, hvS, hvr, rfl⟩ := hf
      exact ⟨v, Finset.mem_coe.mpr (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hvS, hvr⟩), rfl⟩
    calc binPart.ncard
        ≤ ((fun v : V =>
            (x (K := K) (compRep G S v) * y v - x v * y (compRep G S v))) ''
            ↑(Finset.univ.filter (fun v => v ∉ S ∧ v ≠ compRep G S v))).ncard :=
          Set.ncard_le_ncard hsub (Set.Finite.image _ (Finset.finite_toSet _))
      _ ≤ (↑(Finset.univ.filter (fun v => v ∉ S ∧ v ≠ compRep G S v)) : Set V).ncard :=
          Set.ncard_image_le (Finset.finite_toSet _)
      _ = (Finset.univ.filter (fun v => v ∉ S ∧ v ≠ compRep G S v)).card :=
          Set.ncard_coe_finset _
  -- Finset arithmetic: partition V\S into fixed and non-fixed points
  set nonFixed := Finset.univ.filter (fun v : V => v ∉ S ∧ v ≠ compRep G S v)
  set fixedPts := Finset.univ.filter (fun v : V => v ∉ S ∧ compRep G S v = v)
  have hsplit : nonFixed.card + fixedPts.card = Fintype.card V - S.card := by
    have hpart : Finset.univ.filter (fun v : V => v ∉ S) = nonFixed ∪ fixedPts := by
      ext v; simp only [Finset.mem_filter, Finset.mem_univ, true_and,
        Finset.mem_union, nonFixed, fixedPts]
      constructor
      · intro hv
        by_cases h : compRep G S v = v
        · exact Or.inr ⟨hv, h⟩
        · exact Or.inl ⟨hv, Ne.symm h⟩
      · rintro (⟨hv, _⟩ | ⟨hv, _⟩) <;> exact hv
    have hdisj : Disjoint nonFixed fixedPts := by
      rw [Finset.disjoint_filter]; intro v _ ⟨_, hne⟩ ⟨_, heq⟩; exact hne heq.symm
    rw [← Finset.card_union_of_disjoint hdisj, ← hpart]
    rw [show Finset.univ.filter (fun v : V => v ∉ S) = Sᶜ from by
      ext v; simp [Finset.mem_compl]]
    exact Finset.card_compl S
  have hcc_le : componentCount G S ≤ fixedPts.card :=
    componentCount_le_fixedPoints G S
  have hS_le_V : S.card ≤ Fintype.card V := S.card_le_univ
  -- Chain: genSet31.ncard ≤ 2|S| + nonFixed.card
  -- nonFixed.card = |V| - |S| - fixedPts.card, componentCount ≤ fixedPts.card
  -- So genSet31.ncard ≤ 2|S| + |V| - |S| - fixedPts.card ≤ |S| + |V| - componentCount
  omega

open Classical in
private lemma span_genSet31_le (G : SimpleGraph V) (S : Finset V) :
    Ideal.span (genSet31 (K := K) G S) ≤ primeComponent (K := K) G S := by
  apply Ideal.span_le.mpr
  intro f hf
  rcases hf with ⟨i, hiS, rfl | rfl⟩ | ⟨v, hvS, hvr, rfl⟩
  · exact Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inl rfl⟩)
  · exact Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inr rfl⟩)
  · -- x_{rep(v)} y_v - x_v y_{rep(v)} ∈ P_S, since v and rep(v) are in the same component
    have hsc := sameComponent_compRep G S hvS
    exact minor_mem_primeComponent (K := K) G S (Ne.symm hvr) hsc.symm

open Classical in
set_option maxHeartbeats 800000 in
/-- P_S(G) is a minimal prime of span(genSet31). The key step uses the
Plücker identity: for j,k in the same component with representative r,
`x_r * (x_j y_k - x_k y_j) = x_j * (x_r y_k - x_k y_r) - x_k * (x_r y_j - x_j y_r)`
and `x_r ∉ P_S` (since r ∉ S) to force `x_j y_k - x_k y_j ∈ Q` for any
prime Q with `span(genSet31) ⊆ Q ⊆ P_S`. -/
private lemma primeComponent_mem_minimalPrimes_genSet31 (G : SimpleGraph V) (S : Finset V) :
    primeComponent (K := K) G S ∈ (Ideal.span (genSet31 (K := K) G S)).minimalPrimes := by
  haveI := primeComponent_isPrime (K := K) G S
  refine ⟨⟨‹_›, span_genSet31_le G S⟩, fun Q ⟨hQprime, hgenQ⟩ hQP => ?_⟩
  -- Show all generators of P_S are in Q
  apply Ideal.span_le.mpr
  intro f hf
  rcases hf with ⟨i, hiS, rfl | rfl⟩ | ⟨j, k, hjk, hsc, rfl⟩
  · -- Variable generator x_i ∈ Q: it's in genSet31
    exact hgenQ (Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inl rfl⟩))
  · -- Variable generator y_i ∈ Q: it's in genSet31
    exact hgenQ (Ideal.subset_span (Set.mem_union_left _ ⟨i, hiS, Or.inr rfl⟩))
  · -- Binomial generator x_j y_k - x_k y_j ∈ Q via Plücker identity
    set r := compRep G S j
    -- r ∉ S (since j ∉ S and r = compRep G S j is in the same component)
    have hjS := hsc.1
    have hkS := hsc.2.1
    have hrS : r ∉ S := (sameComponent_compRep G S hjS).2.1
    -- x_r ∉ P_S, hence x_r ∉ Q
    have hxr_not_P : (x (K := K) r : MvPolynomial _ K) ∉ primeComponent G S :=
      X_inl_not_mem_primeComponent G S hrS
    have hxr_not_Q : (x (K := K) r : MvPolynomial _ K) ∉ Q :=
      fun h => hxr_not_P (hQP h)
    -- Column-rep generators for j and k are in Q (via genSet31 or trivially)
    -- Helper: x_r y_v - x_v y_r ∈ Q for any v ∉ S with compRep v = r and v ≠ r
    have col_rep_mem_Q : ∀ v : V, v ∉ S → compRep G S v = r → v ≠ r →
        x (K := K) r * y v - x v * y r ∈ Q := by
      intro v hvS hvr hvne
      apply hgenQ; apply Ideal.subset_span
      refine Set.mem_union_right _ ⟨v, hvS, fun h => hvne (h ▸ hvr), by rw [hvr]⟩
    -- compRep k = compRep j = r (since j,k are in the same component)
    have hrep_k : compRep G S k = r :=
      (compRep_eq_of_sameComponent G S hsc).symm
    -- Plücker identity: x_r * (x_j y_k - x_k y_j) =
    --   x_j * (x_r y_k - x_k y_r) - x_k * (x_r y_j - x_j y_r)
    have hplucker : x (K := K) r * (x j * y k - x k * y j) =
        x j * (x r * y k - x k * y r) - x k * (x r * y j - x j * y r) := by ring
    have hxr_prod_mem : x (K := K) r * (x j * y k - x k * y j) ∈ Q := by
      rw [hplucker]
      apply Q.sub_mem
      · apply Q.mul_mem_left
        -- x_r y_k - x_k y_r ∈ Q
        by_cases hkr : k = r
        · rw [hkr, sub_self]; exact Q.zero_mem
        · exact col_rep_mem_Q k hkS hrep_k hkr
      · apply Q.mul_mem_left
        -- x_r y_j - x_j y_r ∈ Q
        by_cases hjr : j = r
        · rw [hjr, sub_self]; exact Q.zero_mem
        · exact col_rep_mem_Q j hjS rfl hjr
    -- By primality: x_r ∈ Q or (x_j y_k - x_k y_j) ∈ Q
    exact hQprime.mem_or_mem hxr_prod_mem |>.resolve_left hxr_not_Q

/-! ### Lower bound infrastructure: chain of prime kernels -/

open Classical in
private noncomputable def lbMap (G : SimpleGraph V) (S : Finset V)
    (T Ux Uy : Finset V) :
    MvPolynomial (BinomialEdgeVars V) K →ₐ[K] MvPolynomial (BinomialEdgeVars V) K :=
  MvPolynomial.aeval (fun v : BinomialEdgeVars V =>
    match v with
    | Sum.inl i => if i ∈ Ux then 0 else X (Sum.inl i)
    | Sum.inr i =>
      if i ∈ Uy then 0
      else if i ∈ T then X (Sum.inl i) * X (Sum.inr (compRep G S i))
      else X (Sum.inr i))

open Classical in
private lemma lbMap_full_eq (G : SimpleGraph V) (S : Finset V) :
    lbMap (K := K) G S (Finset.univ.filter (· ∉ S)) S S = primeComponentMap G S := by
  apply MvPolynomial.algHom_ext; intro v
  cases v with
  | inl i => simp [lbMap, primeComponentMap]
  | inr i =>
    simp only [lbMap, primeComponentMap, MvPolynomial.aeval_X]
    by_cases h1 : i ∈ S
    · simp [h1]
    · have h2 : i ∈ Finset.univ.filter (· ∉ S) := Finset.mem_filter.mpr ⟨Finset.mem_univ _, h1⟩
      simp [h1, h2]

open Classical in
set_option maxHeartbeats 800000 in
private lemma ker_lbMap_insert_Ux (G : SimpleGraph V) (S : Finset V)
    (T Ux Uy : Finset V) (i : V) (hiT : i ∉ T) :
    RingHom.ker (lbMap (K := K) G S T Ux Uy).toRingHom ≤
      RingHom.ker (lbMap (K := K) G S T (insert i Ux) Uy).toRingHom := by
  -- Factor: lbMap T (insert i Ux) Uy = killStep ∘ lbMap T Ux Uy
  let killStep := MvPolynomial.aeval (R := K) (fun v : BinomialEdgeVars V =>
    match v with
    | Sum.inl j => if j = i then (0 : MvPolynomial (BinomialEdgeVars V) K) else X (Sum.inl j)
    | Sum.inr j => X (Sum.inr j))
  have hcomp : lbMap (K := K) G S T (insert i Ux) Uy = killStep.comp (lbMap G S T Ux Uy) := by
    apply MvPolynomial.algHom_ext; intro v; cases v with
    | inl j =>
      simp only [lbMap, killStep, AlgHom.comp_apply, MvPolynomial.aeval_X]
      by_cases hjUx : j ∈ Ux
      · simp [hjUx, Finset.mem_insert.mpr (Or.inr hjUx)]
      · by_cases hji : j = i
        · subst hji; simp [hjUx, Finset.mem_insert]
        · have : j ∉ insert i Ux := by rw [Finset.mem_insert, not_or]; exact ⟨hji, hjUx⟩
          simp [this, hjUx, hji]
    | inr j =>
      simp only [lbMap, killStep, AlgHom.comp_apply, MvPolynomial.aeval_X]
      by_cases hjUy : j ∈ Uy
      · simp [hjUy]
      · by_cases hjT : j ∈ T
        · have : j ≠ i := fun h => hiT (h ▸ hjT)
          simp [hjUy, hjT, map_mul, MvPolynomial.aeval_X, this]
        · simp [hjUy, hjT]
  intro f hf; rw [RingHom.mem_ker] at hf ⊢
  have hf' : (lbMap (K := K) G S T Ux Uy) f = 0 := by
    rwa [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at hf
  have hstep := AlgHom.congr_fun hcomp f
  simp only [AlgHom.comp_apply] at hstep
  rw [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, hstep, hf', map_zero]

open Classical in
set_option maxHeartbeats 800000 in
private lemma ker_lbMap_insert_Uy (G : SimpleGraph V) (S : Finset V)
    (T Ux Uy : Finset V) (i : V) (hiT : i ∉ T)
    (hrep_ne : ∀ j ∈ T, compRep G S j ≠ i) :
    RingHom.ker (lbMap (K := K) G S T Ux Uy).toRingHom ≤
      RingHom.ker (lbMap (K := K) G S T Ux (insert i Uy)).toRingHom := by
  let killStep := MvPolynomial.aeval (R := K) (fun v : BinomialEdgeVars V =>
    match v with
    | Sum.inl j => (X (Sum.inl j) : MvPolynomial (BinomialEdgeVars V) K)
    | Sum.inr j => if j = i then 0 else X (Sum.inr j))
  have hcomp : lbMap (K := K) G S T Ux (insert i Uy) = killStep.comp (lbMap G S T Ux Uy) := by
    apply MvPolynomial.algHom_ext; intro v; cases v with
    | inl j =>
      simp only [lbMap, killStep, AlgHom.comp_apply, MvPolynomial.aeval_X]
      by_cases hjUx : j ∈ Ux <;> simp [hjUx]
    | inr j =>
      simp only [lbMap, killStep, AlgHom.comp_apply, MvPolynomial.aeval_X]
      by_cases hjUy : j ∈ Uy
      · simp [hjUy, Finset.mem_insert.mpr (Or.inr hjUy)]
      · by_cases hjT : j ∈ T
        · have hjne : j ≠ i := fun h => hiT (h ▸ hjT)
          have : j ∉ insert i Uy := by rw [Finset.mem_insert, not_or]; exact ⟨hjne, hjUy⟩
          simp [hjUy, hjT, this, map_mul, MvPolynomial.aeval_X, hjne, hrep_ne j hjT]
        · by_cases hji : j = i
          · subst hji; simp [hjUy, hjT, Finset.mem_insert]
          · have : j ∉ insert i Uy := by rw [Finset.mem_insert, not_or]; exact ⟨hji, hjUy⟩
            simp [hjUy, hjT, this, hji]
  intro f hf; rw [RingHom.mem_ker] at hf ⊢
  have hf' : (lbMap (K := K) G S T Ux Uy) f = 0 := by
    rwa [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at hf
  have hstep := AlgHom.congr_fun hcomp f
  simp only [AlgHom.comp_apply] at hstep
  rw [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, hstep, hf', map_zero]

open Classical in
set_option maxHeartbeats 800000 in
private lemma ker_lbMap_insert_T (G : SimpleGraph V) (S : Finset V)
    (T : Finset V) (v : V) (hvT : v ∉ T)
    (no_rep_v : ∀ w ∈ T, compRep G S w ≠ v) :
    RingHom.ker (lbMap (K := K) G S T ∅ ∅).toRingHom ≤
      RingHom.ker (lbMap (K := K) G S (insert v T) ∅ ∅).toRingHom := by
  let segreStep := MvPolynomial.aeval (R := K) (fun u : BinomialEdgeVars V =>
    match u with
    | Sum.inl j => (X (Sum.inl j) : MvPolynomial (BinomialEdgeVars V) K)
    | Sum.inr j => if j = v then X (Sum.inl v) * X (Sum.inr (compRep G S v))
                    else X (Sum.inr j))
  have hcomp : lbMap (K := K) G S (insert v T) ∅ ∅ = segreStep.comp (lbMap G S T ∅ ∅) := by
    apply MvPolynomial.algHom_ext; intro u; cases u with
    | inl j => simp [lbMap, segreStep, AlgHom.comp_apply, MvPolynomial.aeval_X]
    | inr j =>
      simp only [lbMap, segreStep, AlgHom.comp_apply, MvPolynomial.aeval_X, ite_false]
      by_cases hjT : j ∈ T
      · have hjv : j ≠ v := fun h => hvT (h ▸ hjT)
        simp [hjT, Finset.mem_insert.mpr (Or.inr hjT), hjv, map_mul,
          MvPolynomial.aeval_X, no_rep_v j hjT]
      · by_cases hjv : j = v
        · subst hjv; simp [hjT, Finset.mem_insert, MvPolynomial.aeval_X]
        · have : j ∉ insert v T := by rw [Finset.mem_insert, not_or]; exact ⟨hjv, hjT⟩
          simp [hjT, this, hjv]
  intro f hf; rw [RingHom.mem_ker] at hf ⊢
  have hf' : (lbMap (K := K) G S T ∅ ∅) f = 0 := by
    rwa [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at hf
  have hstep := AlgHom.congr_fun hcomp f
  simp only [AlgHom.comp_apply] at hstep
  rw [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, hstep, hf', map_zero]

open Classical in
private lemma fixedPoints_card_eq_componentCount (G : SimpleGraph V) (S : Finset V) :
    (Finset.univ.filter (fun v => v ∉ S ∧ compRep G S v = v)).card = componentCount G S := by
  apply le_antisymm
  · -- ≤ : injection from fixed points to components
    set G' := G.induce {v : V | v ∉ S}
    set fp := Finset.univ.filter (fun v : V => v ∉ S ∧ compRep G S v = v)
    unfold componentCount; rw [Nat.card_eq_fintype_card]
    let f : fp → G'.ConnectedComponent := fun ⟨v, hv⟩ =>
      G'.connectedComponentMk ⟨v, (Finset.mem_filter.mp hv).2.1⟩
    have hf_inj : Function.Injective f := by
      intro ⟨v₁, hv₁⟩ ⟨v₂, hv₂⟩ heq
      have h₁ := (Finset.mem_filter.mp hv₁).2
      have h₂ := (Finset.mem_filter.mp hv₂).2
      simp only [f] at heq
      have hreach := SimpleGraph.ConnectedComponent.exact heq
      have hsc := reachable_induce_imp_sameComponent G S hreach
      have hrep := compRep_eq_of_sameComponent G S hsc
      rw [h₁.2, h₂.2] at hrep; exact Subtype.ext hrep
    calc fp.card = Fintype.card fp := (Fintype.card_coe fp).symm
      _ ≤ Fintype.card G'.ConnectedComponent := Fintype.card_le_of_injective f hf_inj
  · exact componentCount_le_fixedPoints G S

/--
**Lemma 3.1** (Herzog et al. 2010):
  `height(P_S(G)) = |S| + (|V| - c(S))`

**Upper bound** (`≤`): The column-representative generating set `genSet31` has
`|S| + |V| - c(S)` elements, and P_S is a minimal prime over it. Krull's height
theorem gives `height(P_S) ≤ |S| + |V| - c(S)`.

**Lower bound** (`≥`): Requires height additivity for ideals in disjoint variable
sets (see `toMathlib/HeightAdditivity.lean`), plus the height computations for
variable ideals (`toMathlib/HeightVariableIdeal.lean`) and determinantal ideals
(`toMathlib/HeightDeterminantal.lean`).

Reference: Herzog et al. (2010), Lemma 3.1.
-/
theorem lemma_3_1 (G : SimpleGraph V) (S : Finset V) :
    Ideal.height (primeComponent (K := K) G S) =
      (S.card + (Fintype.card V - componentCount G S) : ℕ) := by
  apply le_antisymm
  · -- Upper bound: height ≤ |S| + |V| - c(S), by Krull's height theorem
    calc Ideal.height (primeComponent (K := K) G S)
        _ ≤ (genSet31 (K := K) G S).ncard :=
            Ideal.height_le_card_of_mem_minimalPrimes_span
              (genSet31_finite G S)
              (primeComponent_mem_minimalPrimes_genSet31 G S)
        _ ≤ S.card + (Fintype.card V - componentCount G S) := by
            exact_mod_cast genSet31_ncard_le G S
  · -- Lower bound: height ≥ |S| + |V| - c(S)
    -- Chain of strict prime inclusions via lbMap kernels.
    haveI hPS := primeComponent_isPrime (K := K) G S
    rw [Ideal.height_eq_primeHeight]
    set reps := Finset.univ.filter (fun v => v ∉ S ∧ compRep G S v = v)
    set nonReps := Finset.univ.filter (fun v => v ∉ S ∧ compRep G S v ≠ v)
    set compS := Finset.univ.filter (fun v : V => v ∉ S)
    have hreps_eq : reps.card = componentCount G S :=
      fixedPoints_card_eq_componentCount G S
    have hpartition : nonReps.card + reps.card = Fintype.card V - S.card := by
      have hunion : nonReps ∪ reps = compS := by
        ext v; simp only [Finset.mem_union, Finset.mem_filter, Finset.mem_univ, true_and,
          nonReps, reps, compS]
        constructor
        · rintro (⟨h, _⟩ | ⟨h, _⟩) <;> exact h
        · intro h; by_cases heq : compRep G S v = v
          · exact Or.inr ⟨h, heq⟩
          · exact Or.inl ⟨h, heq⟩
      have hdisj : Disjoint nonReps reps := by
        rw [Finset.disjoint_filter]; intro v _ ⟨_, hne⟩ ⟨_, heq⟩; exact hne heq
      rw [← Finset.card_union_of_disjoint hdisj, hunion]
      rw [show compS = Sᶜ from by ext v; simp [compS, Finset.mem_compl]]
      exact Finset.card_compl S
    have hT_sub : ∀ v ∈ compS, v ∉ S := fun v hv => (Finset.mem_filter.mp hv).2
    have hT_full : reps ∪ nonReps = compS := by
      ext v; simp only [Finset.mem_union, Finset.mem_filter, Finset.mem_univ, true_and,
        reps, nonReps, compS]
      constructor
      · rintro (⟨h, _⟩ | ⟨h, _⟩) <;> exact h
      · intro h; by_cases heq : compRep G S v = v
        · exact Or.inl ⟨h, heq⟩
        · exact Or.inr ⟨h, heq⟩
    -- The final kernel equals P_S
    have hker_eq : RingHom.ker (lbMap (K := K) G S compS S S).toRingHom =
        primeComponent (K := K) G S := by
      conv_lhs =>
        rw [show compS = Finset.univ.filter (· ∉ S) from rfl,
          show (lbMap (K := K) G S (Finset.univ.filter (· ∉ S)) S S).toRingHom =
            (primeComponentMap (K := K) G S).toRingHom from
            congr_arg AlgHom.toRingHom (lbMap_full_eq G S)]
      exact (primeComponent_eq_ker (K := K) G S).symm
    -- Phase 1: Segre chain gives primeHeight(ker(lbMap compS ∅ ∅)) ≥ nonReps.card
    -- Phase 2: x-kill chain gives ≥ nonReps.card + S.card
    -- Phase 3: y-kill chain gives ≥ nonReps.card + 2*S.card = N
    -- Then convert using hker_eq.
    -- Each phase uses Finset.induction with primeHeight_add_one_le_of_lt.
    -- For compactness we sorry the inductive chain argument; the key ingredients
    -- (kernel inclusion, witness membership/non-membership) are all proved above.
    have hS_le : S.card ≤ Fintype.card V := S.card_le_univ
    have hN_eq : S.card + (Fintype.card V - componentCount G S) =
        nonReps.card + 2 * S.card := by
      rw [← hreps_eq]; omega
    haveI hker_prime : (RingHom.ker (lbMap (K := K) G S compS S S).toRingHom).IsPrime :=
      RingHom.ker_isPrime _
    rw [hN_eq]
    -- The kernel of lbMap with full parameters equals P_S, so their heights are equal
    have hheight_eq : Ideal.primeHeight (RingHom.ker (lbMap (K := K) G S compS S S).toRingHom) =
        Ideal.primeHeight (primeComponent (K := K) G S) := by
      unfold Ideal.primeHeight; congr 1; exact PrimeSpectrum.ext hker_eq
    rw [← hheight_eq]
    push_cast
    -- Three-phase chain: Segre, x-kill, y-kill
    -- Each phase proved by Finset.induction with primeHeight_add_one_le_of_lt.
    -- Phase 1: Segre chain
    -- All lbMap kernels are prime (kernel of AlgHom to a domain)
    have lbMap_prime : ∀ T' Ux' Uy',
        (RingHom.ker (lbMap (K := K) G S T' Ux' Uy').toRingHom).IsPrime :=
      fun _ _ _ => RingHom.ker_isPrime _
    -- Phase 1: Segre chain
    have phase1 : ∀ F, F ⊆ nonReps →
        (F.card : ℕ∞) ≤ Ideal.height (RingHom.ker (lbMap (K := K) G S (reps ∪ F) ∅ ∅).toRingHom) := by
      intro F hF; induction F using Finset.induction with
      | empty => simp
      | @insert a F' haF' ihF =>
        have haF'Sub : F' ⊆ nonReps := (Finset.insert_subset_iff.mp hF).2
        have haInNonReps : a ∈ nonReps := hF (Finset.mem_insert_self a F')
        have haNotS : a ∉ S := (Finset.mem_filter.mp haInNonReps).2.1
        have ha_compRep_ne : compRep G S a ≠ a :=
          (Finset.mem_filter.mp haInNonReps).2.2
        have haNotReps : a ∉ reps := by
          intro h; exact (Finset.mem_filter.mp haInNonReps).2.2
            (Finset.mem_filter.mp h).2.2
        have haNotT : a ∉ reps ∪ F' := by
          rw [Finset.mem_union, not_or]; exact ⟨haNotReps, haF'⟩
        set r := compRep G S a with hr_def
        have hr_in_reps : r ∈ reps := by
          rw [Finset.mem_filter]; exact ⟨Finset.mem_univ _,
            (sameComponent_compRep G S haNotS).2.1,
            compRep_idempotent G S haNotS⟩
        have hno_rep : ∀ w ∈ reps ∪ F', compRep G S w ≠ a := by
          intro w hw heq
          rcases Finset.mem_union.mp hw with hw_r | hw_F
          · -- w ∈ reps: compRep w = w, so w = a, contradicts a ∉ reps
            have h1 : compRep G S w = w := (Finset.mem_filter.mp hw_r).2.2
            rw [h1] at heq; exact haNotReps (heq ▸ hw_r)
          · -- w ∈ F' ⊆ nonReps: compRep w ∈ reps, so a ∈ reps, contradiction
            have hwNR := haF'Sub hw_F
            have hwNotS := (Finset.mem_filter.mp hwNR).2.1
            have hcr_reps : compRep G S w ∈ reps := by
              rw [Finset.mem_filter]; exact ⟨Finset.mem_univ _,
                (sameComponent_compRep G S hwNotS).2.1,
                compRep_idempotent G S hwNotS⟩
            exact haNotReps (heq ▸ hcr_reps)
        have hle := ker_lbMap_insert_T (K := K) G S (reps ∪ F') a haNotT hno_rep
        have hinsert_eq : insert a (reps ∪ F') = reps ∪ insert a F' := by
          ext v; simp only [Finset.mem_insert, Finset.mem_union]
          tauto
        -- Witness: x_r * y_a - x_a * y_r is in the larger kernel but not the smaller
        set witness : MvPolynomial (BinomialEdgeVars V) K :=
          X (Sum.inr a) * X (Sum.inl r) - X (Sum.inl a) * X (Sum.inr r)
        have hr_in_T : r ∈ reps ∪ F' :=
          Finset.mem_union.mpr (Or.inl hr_in_reps)
        have ha_in_insertT : a ∈ insert a (reps ∪ F') :=
          Finset.mem_insert_self a _
        have hr_in_insertT : r ∈ insert a (reps ∪ F') :=
          Finset.mem_insert.mpr (Or.inr hr_in_T)
        have hr_compRep : compRep G S r = r :=
          compRep_idempotent G S haNotS
        have hwitness_mem : witness ∈
            RingHom.ker (lbMap (K := K) G S (insert a (reps ∪ F')) ∅ ∅).toRingHom := by
          rw [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom]
          change (lbMap (K := K) G S (insert a (reps ∪ F')) ∅ ∅) witness = 0
          simp only [witness, map_sub, map_mul]
          unfold lbMap
          simp only [MvPolynomial.aeval_X, Finset.notMem_empty, ↓reduceIte,
            ha_in_insertT, hr_in_insertT, hr_compRep]
          ring
        have hwitness_nmem : witness ∉
            RingHom.ker (lbMap (K := K) G S (reps ∪ F') ∅ ∅).toRingHom := by
          intro h
          rw [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at h
          change (lbMap (K := K) G S (reps ∪ F') ∅ ∅) witness = 0 at h
          simp only [witness, map_sub, map_mul] at h
          unfold lbMap at h
          simp only [MvPolynomial.aeval_X, Finset.notMem_empty, ↓reduceIte,
            haNotT, hr_in_T, hr_compRep] at h
          -- h : X (inr a) * X (inl r) - X (inl a) * (X (inl r) * X (inr r)) = 0
          -- Evaluate at a point to get contradiction: set x_r = 1, y_a = 1, rest = 0
          let f : BinomialEdgeVars V → K := fun v =>
            if v = Sum.inr a then 1 else if v = Sum.inl r then 1 else 0
          have heval := congr_arg (MvPolynomial.eval f) h
          simp only [map_sub, map_mul, MvPolynomial.eval_X, map_zero, f] at heval
          simp only [reduceCtorEq, ↓reduceIte, mul_one] at heval
          rw [if_neg (show Sum.inl a ≠ Sum.inl (compRep G S a) from
            fun h => ha_compRep_ne.symm (Sum.inl_injective h)),
            if_neg (show Sum.inr (compRep G S a) ≠ Sum.inr a from
            fun h => ha_compRep_ne (Sum.inr_injective h))] at heval
          simp at heval
        have hlt : RingHom.ker (lbMap (K := K) G S (reps ∪ F') ∅ ∅).toRingHom <
            RingHom.ker (lbMap (K := K) G S (reps ∪ insert a F') ∅ ∅).toRingHom := by
          rw [← hinsert_eq]
          exact lt_of_le_of_ne hle (fun heq => hwitness_nmem (heq ▸ hwitness_mem))
        haveI := lbMap_prime (reps ∪ F') ∅ ∅
        haveI := lbMap_prime (reps ∪ insert a F') ∅ ∅
        have hn := ihF haF'Sub
        rw [Ideal.height_eq_primeHeight] at hn
        rw [Finset.card_insert_of_notMem haF', Ideal.height_eq_primeHeight]
        push_cast
        calc (↑F'.card + 1 : ℕ∞)
            ≤ (RingHom.ker (lbMap (K := K) G S (reps ∪ F') ∅ ∅).toRingHom).primeHeight + 1 := by
              gcongr
          _ ≤ (RingHom.ker (lbMap (K := K) G S (reps ∪ insert a F') ∅ ∅).toRingHom).primeHeight :=
              Ideal.primeHeight_add_one_le_of_lt hlt
    -- Phase 2: x-kill chain
    have phase2 : ∀ Ux, Ux ⊆ S →
        (nonReps.card + Ux.card : ℕ∞) ≤
          Ideal.height (RingHom.ker (lbMap (K := K) G S compS Ux ∅).toRingHom) := by
      intro Ux hUx; induction Ux using Finset.induction with
      | empty =>
        simp only [Finset.card_empty, Nat.cast_zero, add_zero]
        rw [show compS = reps ∪ nonReps from hT_full.symm]; exact phase1 nonReps Finset.Subset.rfl
      | @insert a Ux' haUx' ihUx =>
        have haS : a ∈ S := hUx (Finset.mem_insert_self a Ux')
        have hUx'S : Ux' ⊆ S := (Finset.insert_subset_iff.mp hUx).2
        have haCompS : a ∉ compS := fun h => (Finset.mem_filter.mp h).2 haS
        have hle := ker_lbMap_insert_Ux (K := K) G S compS Ux' ∅ a haCompS
        have hwitness_mem : X (Sum.inl a) ∈
            RingHom.ker (lbMap (K := K) G S compS (insert a Ux') ∅).toRingHom := by
          rw [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom]
          change (lbMap (K := K) G S compS (insert a Ux') ∅) (X (Sum.inl a)) = 0
          unfold lbMap; rw [MvPolynomial.aeval_X]; exact if_pos (Finset.mem_insert_self a Ux')
        have hwitness_nmem : X (Sum.inl a) ∉
            RingHom.ker (lbMap (K := K) G S compS Ux' ∅).toRingHom := by
          intro h
          rw [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at h
          change (lbMap (K := K) G S compS Ux' ∅) (X (Sum.inl a)) = 0 at h
          unfold lbMap at h; rw [MvPolynomial.aeval_X] at h; dsimp only [] at h
          rw [if_neg haUx'] at h; exact MvPolynomial.X_ne_zero _ h
        have hlt : RingHom.ker (lbMap (K := K) G S compS Ux' ∅).toRingHom <
            RingHom.ker (lbMap (K := K) G S compS (insert a Ux') ∅).toRingHom :=
          lt_of_le_of_ne hle (fun heq => hwitness_nmem (heq ▸ hwitness_mem))
        haveI := lbMap_prime compS Ux' ∅
        haveI := lbMap_prime compS (insert a Ux') ∅
        have hn := ihUx hUx'S
        rw [Ideal.height_eq_primeHeight] at hn
        rw [Finset.card_insert_of_notMem haUx', Ideal.height_eq_primeHeight]
        push_cast
        calc (↑nonReps.card + ↑Ux'.card + 1 : ℕ∞)
            ≤ (RingHom.ker (lbMap (K := K) G S compS Ux' ∅).toRingHom).primeHeight + 1 := by
              gcongr
          _ ≤ (RingHom.ker (lbMap (K := K) G S compS (insert a Ux') ∅).toRingHom).primeHeight :=
              Ideal.primeHeight_add_one_le_of_lt hlt
    -- Phase 3: y-kill chain
    have phase3 : ∀ Uy, Uy ⊆ S →
        (nonReps.card + S.card + Uy.card : ℕ∞) ≤
          Ideal.height (RingHom.ker (lbMap (K := K) G S compS S Uy).toRingHom) := by
      intro Uy hUy; induction Uy using Finset.induction with
      | empty =>
        simp only [Finset.card_empty, Nat.cast_zero, add_zero]
        exact phase2 S Finset.Subset.rfl
      | @insert a Uy' haUy' ihUy =>
        have haS : a ∈ S := hUy (Finset.mem_insert_self a Uy')
        have hUy'S : Uy' ⊆ S := (Finset.insert_subset_iff.mp hUy).2
        have haCompS : a ∉ compS := fun h => (Finset.mem_filter.mp h).2 haS
        have hrep_ne : ∀ j ∈ compS, compRep G S j ≠ a := by
          intro j hj heq
          have hjNotS := (Finset.mem_filter.mp hj).2
          exact (sameComponent_compRep G S hjNotS).2.1 (heq ▸ haS)
        have hle := ker_lbMap_insert_Uy (K := K) G S compS S Uy' a haCompS hrep_ne
        have hwitness_mem : X (Sum.inr a) ∈
            RingHom.ker (lbMap (K := K) G S compS S (insert a Uy')).toRingHom := by
          rw [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom]
          change (lbMap (K := K) G S compS S (insert a Uy')) (X (Sum.inr a)) = 0
          unfold lbMap; rw [MvPolynomial.aeval_X]
          exact if_pos (Finset.mem_insert_self a Uy')
        have hwitness_nmem : X (Sum.inr a) ∉
            RingHom.ker (lbMap (K := K) G S compS S Uy').toRingHom := by
          intro h
          rw [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at h
          change (lbMap (K := K) G S compS S Uy') (X (Sum.inr a)) = 0 at h
          unfold lbMap at h; rw [MvPolynomial.aeval_X] at h; dsimp only [] at h
          rw [if_neg haUy', if_neg haCompS] at h; exact MvPolynomial.X_ne_zero _ h
        have hlt : RingHom.ker (lbMap (K := K) G S compS S Uy').toRingHom <
            RingHom.ker (lbMap (K := K) G S compS S (insert a Uy')).toRingHom :=
          lt_of_le_of_ne hle (fun heq => hwitness_nmem (heq ▸ hwitness_mem))
        haveI := lbMap_prime compS S Uy'
        haveI := lbMap_prime compS S (insert a Uy')
        have hn := ihUy hUy'S
        rw [Ideal.height_eq_primeHeight] at hn
        rw [Finset.card_insert_of_notMem haUy', Ideal.height_eq_primeHeight]
        push_cast
        calc (↑nonReps.card + ↑S.card + ↑Uy'.card + 1 : ℕ∞)
            ≤ (RingHom.ker (lbMap (K := K) G S compS S Uy').toRingHom).primeHeight + 1 := by
              gcongr
          _ ≤ (RingHom.ker (lbMap (K := K) G S compS S (insert a Uy')).toRingHom).primeHeight :=
              Ideal.primeHeight_add_one_le_of_lt hlt
    -- Combine: phase3 gives height(ker(lbMap compS S S)) ≥ nonReps.card + 2*S.card
    -- ker(lbMap compS S S) = P_S by hker_eq, so height(P_S) ≥ N.
    have hfinal := phase3 S Finset.Subset.rfl
    calc (↑(nonReps.card + 2 * S.card) : ℕ∞)
        = ↑nonReps.card + ↑S.card + ↑S.card := by push_cast; ring
      _ ≤ (RingHom.ker (lbMap (K := K) G S compS S S).toRingHom).height := hfinal
      _ = _ := by
          rw [show (RingHom.ker (lbMap (K := K) G S compS S S).toRingHom).height =
                (primeComponent (K := K) G S).height from congr_arg _ hker_eq,
              @Ideal.height_eq_primeHeight _ _ _ hPS]
          exact hheight_eq.symm

end lemma31

/--
For connected G, `P_∅(G)` equals the binomial edge ideal of the **complete graph** on V.
Every pair j < k has `SameComponent G ∅ j k` (since G is connected and S = ∅),
so the generators of P_∅(G) are all `x_j y_k - x_k y_j` for j < k,
which is exactly `J_{K_V} = binomialEdgeIdeal ⊤`.

Note: the statement `P_∅(G) = J_G` would only hold if G were itself complete.
-/
theorem primeComponent_empty_connected (G : SimpleGraph V) (hConn : G.Connected) :
    primeComponent (K := K) G ∅ = binomialEdgeIdeal (K := K) (⊤ : SimpleGraph V) := by
  apply le_antisymm
  · -- P_∅(G) ≤ J_{K_V}: every generator x_j y_k - x_k y_j is in J_{K_V}
    -- since (⊤ : SimpleGraph V).Adj j k = j ≠ k, and j < k implies j ≠ k
    apply Ideal.span_le.mpr
    intro f hf
    simp only [Set.mem_union, Set.mem_setOf_eq] at hf
    rcases hf with ⟨i, hiS, _⟩ | ⟨j, k, hjk, _, rfl⟩
    · exact absurd hiS (Finset.notMem_empty i)
    · exact Ideal.subset_span ⟨j, k, (SimpleGraph.top_adj j k).mpr (ne_of_lt hjk), hjk, rfl⟩
  · -- J_{K_V} ≤ P_∅(G): every generator x_i y_j - x_j y_i is in P_∅(G)
    -- because G.Connected gives G.Reachable i j, hence SameComponent G ∅ i j
    apply Ideal.span_le.mpr
    intro f hf
    obtain ⟨i, j, _, hij, rfl⟩ := hf
    apply Ideal.subset_span
    refine Set.mem_union_right _ ⟨i, j, hij, ?_, rfl⟩
    -- Prove SameComponent G ∅ i j
    refine ⟨Finset.notMem_empty _, Finset.notMem_empty _, ?_⟩
    -- G.Reachable i j ↔ Relation.ReflTransGen G.Adj i j; then strengthen to include ∉ ∅
    apply Relation.ReflTransGen.mono
      (fun a b h => ⟨h, Finset.notMem_empty _, Finset.notMem_empty _⟩)
    exact (SimpleGraph.reachable_iff_reflTransGen i j).mp (hConn.preconnected i j)

-- Proposition 3.6 is proved in PrimeDecomposition.lean (needs primeComponent_le_prime).

end
