import BEI.Definitions
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected

variable {K : Type*} [Field K]
variable {V : Type*} [LinearOrder V] [DecidableEq V] [Fintype V]

/-!
# Prime ideals P_S(G) and their basic properties (Section 3)

For each subset `S ⊆ V`, we define the prime ideal `P_S(G)` and establish
its basic properties (primeness, containment in J_G, height formula).

## Definition of P_S(G)
For `S ⊆ V`, let `T = V \ S`. The connected components of `G[T]` are
`G₁, ..., G_c`. Then:
  `P_S(G) = ({xᵢ, yᵢ | i ∈ S}, J_{G̃₁}, ..., J_{G̃_c})`
where `G̃ₖ` is the complete graph on the vertex set of `Gₖ`.

## Reference: Herzog et al. (2010), Section 3
-/

noncomputable section

open MvPolynomial SimpleGraph

/-! ## Connected component count -/

/--
The number of connected components of the induced subgraph on `V \ S`.
This is `c(S)` in the paper's notation.

We define this as a sorry for now; the correct definition uses
`Fintype.card (inducedSubgraph.ConnectedComponent)`.
-/
noncomputable def componentCount (G : SimpleGraph V) (S : Finset V) : ℕ := sorry

/-- c(∅) equals the number of connected components of G. -/
theorem componentCount_empty (G : SimpleGraph V) :
    componentCount G ∅ = sorry := sorry

/-! ## The prime ideal P_S(G) -/

/--
Two vertices `u v : V` lie in the same connected component of `G[V \ S]`.
-/
def SameComponent (G : SimpleGraph V) (S : Finset V) (u v : V) : Prop :=
  u ∉ S ∧ v ∉ S ∧
  Relation.ReflTransGen (fun a b => G.Adj a b ∧ a ∉ S ∧ b ∉ S) u v

/--
The prime ideal `P_S(G)` is generated by:
- `X (Sum.inl i)` and `X (Sum.inr i)` for each `i ∈ S`, and
- `x_j * y_k - x_k * y_j` for all j < k in the same component of `G[V \ S]`.

Reference: Herzog et al. (2010), Section 3.
-/
noncomputable def primeComponent (G : SimpleGraph V) (S : Finset V) :
    Ideal (MvPolynomial (BinomialEdgeVars V) K) :=
  Ideal.span
    ({ f : MvPolynomial (BinomialEdgeVars V) K |
        ∃ i ∈ S, f = X (Sum.inl i) ∨ f = X (Sum.inr i) } ∪
     { f : MvPolynomial (BinomialEdgeVars V) K |
        ∃ j k : V, j < k ∧ SameComponent G S j k ∧
             f = x j * y k - x k * y j })

/-! ## Basic properties -/

/-- `P_S(G)` is a prime ideal. -/
theorem primeComponent_isPrime (G : SimpleGraph V) (S : Finset V) :
    (primeComponent (K := K) G S).IsPrime := by
  sorry

/-- `J_G ⊆ P_S(G)` for every subset S. -/
theorem binomialEdgeIdeal_le_primeComponent (G : SimpleGraph V) (S : Finset V) :
    binomialEdgeIdeal (K := K) G ≤ primeComponent (K := K) G S := by
  sorry

/-! ## Lemma 3.1: Height formula -/

/--
Placeholder for ideal height (Krull height of a prime ideal).
The correct Mathlib API is `Ideal.primeHeight` or similar.
-/
noncomputable def idealHeight (I : Ideal (MvPolynomial (BinomialEdgeVars V) K)) : ℕ := sorry

/--
**Lemma 3.1** (Herzog et al. 2010):
  `height(P_S(G)) = |S| + (|V| - c(S))`

Reference: Herzog et al. (2010), Lemma 3.1.
-/
theorem lemma_3_1 (G : SimpleGraph V) (S : Finset V) :
    idealHeight (primeComponent (K := K) G S) =
      S.card + (Fintype.card V - componentCount G S) := by
  sorry

/--
For connected G, `P_∅(G)` equals `J_G`.
(The only component of `G[V]` is G itself, and the complete graph on V(G) is J_G.)
-/
theorem primeComponent_empty_connected (G : SimpleGraph V) (hConn : G.Connected) :
    primeComponent (K := K) G ∅ = binomialEdgeIdeal (K := K) G := by
  sorry

/-! ## Proposition 3.6: When J_G is prime -/

/--
**Proposition 3.6** (Herzog et al. 2010): `J_G` is a prime ideal if and only if
every connected component of G is a complete graph.

Reference: Herzog et al. (2010), Proposition 3.6.
-/
theorem prop_3_6 (G : SimpleGraph V) :
    (binomialEdgeIdeal (K := K) G).IsPrime ↔
    ∀ u w : V, G.Reachable u w → G.Adj u w ∨ u = w := by
  sorry

end
