/-
Copyright (c) 2026 Thomas Kahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Kahle
-/
import BEI.Definitions
import toMathlib.SquarefreeMonomialPrimes

/-!
# The reduced Herzog–Hibi ring of an HH graph

Given `r : ℕ` and a simple graph `G'` on `Fin (r + 1)`, the **reduced HH ring**
is

    K[x'_0, …, x'_{r-1}, y'_0, …, y'_{r-1}] / I^red(G')

where `I^red(G') := ⟨ x'_a · y'_b : 0 ≤ a ≤ b < r, {a, b+1} ∈ E(G') ⟩`.

The index type is `BinomialEdgeVars (Fin r)` — i.e. `2r` variables, not
`2(r+1)`. The trailing isolated pair `x'_r, y'_r` that would appear in the
full HH ring on `Fin (r+1)` is NOT present: it is the "reduced" variant in
the sense of the F2 route of Proposition 1.6 in Herzog–Hibi–Hreinsdóttir–
Kahle–Rauh (2010).

This file provides the abstract definition. The combinatorial construction
of `G'` from an "original" HH graph `G` and a paired-survivor index set is
in `BEI/Equidim.lean` (see `smallerHHGraph`).
-/

noncomputable section

open MvPolynomial

namespace BEI

variable {K : Type*} [Field K]

/-- The edge set of the reduced HH ring of an HH graph `G'` on `Fin (r + 1)`.

Pairs `(Sum.inl a, Sum.inr b)` with `0 ≤ a ≤ b < r` and
`{a, b+1} ∈ E(G')`. Range is `BinomialEdgeVars (Fin r)`. -/
def reducedHHEdgeSet {r : ℕ} (G' : SimpleGraph (Fin (r + 1))) :
    Set (BinomialEdgeVars (Fin r) × BinomialEdgeVars (Fin r)) :=
  { e | ∃ (a : Fin r) (b : Fin r) (hb : b.val + 1 < r + 1),
      G'.Adj a.castSucc ⟨b.val + 1, hb⟩ ∧
      a ≤ b ∧
      e = (Sum.inl a, Sum.inr b) }

/-- The reduced HH ideal of `G'`: generated by `X(inl a) * X(inr b)` for each
edge `(a, b)` in `reducedHHEdgeSet G'`. -/
def reducedHHIdeal {r : ℕ} (G' : SimpleGraph (Fin (r + 1))) :
    Ideal (MvPolynomial (BinomialEdgeVars (Fin r)) K) :=
  MvPolynomial.variablePairIdeal (R := K) (reducedHHEdgeSet G')

/-- The reduced HH ring `A^red_{G'}`. -/
abbrev reducedHHRing {r : ℕ} (G' : SimpleGraph (Fin (r + 1))) : Type _ :=
  MvPolynomial (BinomialEdgeVars (Fin r)) K ⧸ reducedHHIdeal (K := K) G'

/-- `reducedHHIdeal G' = variablePairIdeal (reducedHHEdgeSet G')` by definition. -/
theorem reducedHHIdeal_eq_variablePairIdeal {r : ℕ}
    (G' : SimpleGraph (Fin (r + 1))) :
    reducedHHIdeal (K := K) G' =
      MvPolynomial.variablePairIdeal (R := K) (reducedHHEdgeSet G') := rfl

/-- Each reduced HH generator lies in `reducedHHIdeal`. -/
theorem X_mul_X_mem_reducedHHIdeal {r : ℕ}
    {G' : SimpleGraph (Fin (r + 1))}
    {a b : BinomialEdgeVars (Fin r)}
    (hab : (a, b) ∈ reducedHHEdgeSet G') :
    (X a : MvPolynomial (BinomialEdgeVars (Fin r)) K) * X b ∈
      reducedHHIdeal (K := K) G' := by
  refine Ideal.subset_span ?_
  exact ⟨a, b, hab, rfl⟩

/-- Specific generator: for paired-survivor indices `a ≤ b < r` with
`{a, b+1} ∈ E(G')`, the generator `X(inl a) * X(inr b)` lies in the ideal. -/
theorem X_inl_mul_X_inr_mem_reducedHHIdeal {r : ℕ}
    {G' : SimpleGraph (Fin (r + 1))} {a b : Fin r}
    (hab : a ≤ b) (hb : b.val + 1 < r + 1)
    (hadj : G'.Adj a.castSucc ⟨b.val + 1, hb⟩) :
    (X (Sum.inl a) * X (Sum.inr b) :
        MvPolynomial (BinomialEdgeVars (Fin r)) K) ∈
      reducedHHIdeal (K := K) G' :=
  X_mul_X_mem_reducedHHIdeal (K := K) ⟨a, b, hb, hadj, hab, rfl⟩

end BEI

end
