import BEI.AdmissiblePaths
import BEI.MonomialOrder
import BEI.GroebnerAPI
import BEI.ClosedGraphs
import Mathlib.RingTheory.MvPolynomial.MonomialOrder
import Mathlib.RingTheory.MvPolynomial.Groebner
import Mathlib.RingTheory.Ideal.Operations

variable {K : Type*} [Field K]
variable {V : Type*} [LinearOrder V] [DecidableEq V] [Fintype V]

noncomputable section

open MvPolynomial MonomialOrder

-- Define the "collapsing" map φ : K[BinomialEdgeVars V] → K[V]
-- sending x_v ↦ X v and y_v ↦ X v
private noncomputable def collapseMap (K : Type*) [Field K] (V : Type*) :
    MvPolynomial (BinomialEdgeVars V) K →ₐ[K] MvPolynomial V K :=
  MvPolynomial.aeval (fun v : BinomialEdgeVars V =>
    match v with
    | Sum.inl w => (X w : MvPolynomial V K)
    | Sum.inr w => (X w : MvPolynomial V K))

-- Helper: the collapsed function
private def collapseFunc (V : Type*) : BinomialEdgeVars V → MvPolynomial V K :=
  fun v => match v with
    | Sum.inl w => X w
    | Sum.inr w => X w

-- φ(fij i j) = X i * X j - X j * X i = 0
private lemma collapseMap_fij (i j : V) :
    collapseMap K V (fij (K := K) i j) = 0 := by
  simp [collapseMap, fij, x, y, MvPolynomial.aeval_X]
  ring

-- φ(monomial s c) ≠ 0 when c ≠ 0
private lemma collapseMap_monomial_ne_zero (s : BinomialEdgeVars V →₀ ℕ) (c : K) (hc : c ≠ 0) :
    collapseMap K V (monomial s c) ≠ 0 := by
  simp only [collapseMap, aeval_monomial, algebraMap_eq]
  -- C c * ∏ (collapseFunc v) ^ s v ≠ 0
  -- Use: C c ≠ 0 and monomial products of X's are nonzero
  intro h
  -- The product is a monomial with coefficient 1
  -- First show C c ≠ 0
  have hCc : (C c : MvPolynomial V K) ≠ 0 := C_ne_zero.mpr hc
  -- The product of X^k terms is nonzero
  have hprod : s.prod (fun (v : BinomialEdgeVars V) k =>
      (match v with
       | Sum.inl w => (X w : MvPolynomial V K)
       | Sum.inr w => X w) ^ k) ≠ 0 := by
    apply Finsupp.prod_ne_zero
    intro v k _
    cases v with
    | inl w => exact pow_ne_zero _ (X_ne_zero w)
    | inr w => exact pow_ne_zero _ (X_ne_zero w)
  exact mul_ne_zero hCc hprod h

-- The ideal generated by fij's maps to 0
private lemma binomialEdgeIdeal_le_ker (G : SimpleGraph V) :
    binomialEdgeIdeal (K := K) G ≤
    RingHom.ker (collapseMap K V).toRingHom := by
  apply Ideal.span_le.mpr
  intro f hf
  obtain ⟨i, j, hAdj, hij, rfl⟩ := hf
  simp only [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom]
  -- f = x i * y j - x j * y i = fij i j
  change collapseMap K V (x i * y j - x j * y i) = 0
  simp [collapseMap, x, y, MvPolynomial.aeval_X]
  ring

-- No nonzero monomial in J_G
private lemma binomialEdgeIdeal_no_monomial (G : SimpleGraph V)
    (s : BinomialEdgeVars V →₀ ℕ) (c : K) (hc : c ≠ 0) :
    monomial s c ∉ binomialEdgeIdeal (K := K) G := by
  intro hmem
  have hle := binomialEdgeIdeal_le_ker (K := K) G hmem
  simp only [RingHom.mem_ker, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom] at hle
  exact collapseMap_monomial_ne_zero s c hc hle

end
