/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.Ideal.Height
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.MvPolynomial.Basic

/-!
# Height of variable-generated ideals in MvPolynomial

In `MvPolynomial σ K`, the ideal generated by a set of distinct variables
has height equal to the cardinality of the set. This is a fundamental
computation in commutative algebra that is not yet in Mathlib.

## Main results

- `MvPolynomial.height_span_X_image`: `height(⟨X i : i ∈ s⟩) = |s|`
- `MvPolynomial.isPrime_span_X_image`: the ideal is prime
- `MvPolynomial.height_span_X_le`: upper bound via Krull's height theorem

## Proof strategy

**Upper bound** (`height ≤ |s|`): By Krull's height theorem, since the ideal
is generated by `|s|` elements and is its own minimal prime (being prime).
Uses `Ideal.height_le_card_of_mem_minimalPrimes_span_finset`.

**Lower bound** (`height ≥ |s|`): Construct the explicit chain of primes
`(X i₁) ⊊ (X i₁, X i₂) ⊊ ... ⊊ (X i₁, ..., X i_{|s|})`.
Each intermediate ideal is prime (quotient is a polynomial ring in remaining
variables). This requires showing that variable ideals in `MvPolynomial` are
prime, and that adding one more variable strictly increases the ideal.

## Mathlib prerequisites (available)
- `Ideal.height` and `Ideal.primeHeight` (`Mathlib.RingTheory.Ideal.Height`)
- Krull's height theorem (`Mathlib.RingTheory.Ideal.KrullsHeightTheorem`)
- `MvPolynomial` basics (`Mathlib.RingTheory.MvPolynomial.Basic`)
-/

variable {K : Type*} [Field K] {σ : Type*} [Fintype σ] [DecidableEq σ]

noncomputable section

open MvPolynomial

/-- The ideal generated by variables `{X i : i ∈ s}` is prime in `MvPolynomial σ K`.
The quotient `MvPolynomial σ K / ⟨X i : i ∈ s⟩` is isomorphic to `MvPolynomial (σ \ s) K`,
a polynomial ring in the remaining variables. -/
theorem MvPolynomial.isPrime_span_X_image (s : Finset σ) :
    (Ideal.span ((↑s : Set σ).image (X : σ → MvPolynomial σ K))).IsPrime := by
  sorry

/-- Upper bound: the height of a variable ideal is at most `|s|`.
Follows from Krull's height theorem since the ideal is generated by `|s|` elements
and is prime. -/
theorem MvPolynomial.height_span_X_le (s : Finset σ) :
    (Ideal.span ((↑s : Set σ).image (X : σ → MvPolynomial σ K))).height ≤ s.card := by
  sorry

/-- Lower bound: the height of a variable ideal is at least `|s|`.
Proved by exhibiting a chain of primes of length `|s|`. -/
theorem MvPolynomial.height_span_X_ge (s : Finset σ) :
    s.card ≤ (Ideal.span ((↑s : Set σ).image (X : σ → MvPolynomial σ K))).height := by
  sorry

/-- The ideal generated by variables `{X i : i ∈ s}` in `MvPolynomial σ K` has
height equal to `|s|`. -/
theorem MvPolynomial.height_span_X_image (s : Finset σ) :
    (Ideal.span ((↑s : Set σ).image (X : σ → MvPolynomial σ K))).height = s.card := by
  exact le_antisymm (MvPolynomial.height_span_X_le s) (MvPolynomial.height_span_X_ge s)

end
