/-
Copyright (c) 2026 Thomas Kahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Kahle
-/
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.Algebra.MvPolynomial.Rename

/-!
# Primality of variable-generated ideals in `MvPolynomial`

The ideal generated by a set of variables `{X i | i in s}` in `MvPolynomial sigma R`
is prime when `R` is an integral domain. The proof uses `MvPolynomial.killCompl` to
construct a surjection onto a polynomial ring in the complement variables, whose kernel
is exactly the variable ideal.

## Main results

* `MvPolynomial.isPrime_span_X_image`: the ideal `span (X '' s)` is prime

## Tags

multivariate polynomial, prime ideal, variable ideal
-/

variable {R : Type*} [CommRing R] [IsDomain R] {σ : Type*}

namespace MvPolynomial

open Ideal

private noncomputable abbrev killVars (s : Finset σ) :
    MvPolynomial σ R →ₐ[R] MvPolynomial {j : σ // j ∉ s} R :=
  killCompl (R := R) (f := (Subtype.val : {j : σ // j ∉ s} → σ)) Subtype.val_injective

omit [IsDomain R] in
/-- `killVars s` sends a monomial `m` with `m i = 0` for all `i ∈ s` to
the corresponding restricted monomial. -/
private lemma killVars_monomial_eq (s : Finset σ) (m : σ →₀ ℕ) (c : R)
    (hm : ∀ i ∈ (s : Set σ), m i = 0) :
    killVars (R := R) s (monomial m c) =
      monomial (m.comapDomain Subtype.val Subtype.val_injective.injOn) c := by
  have hsupp : (↑m.support : Set σ) ⊆
      Set.range (Subtype.val : {j : σ // j ∉ s} → σ) := by
    intro i hi
    have : i ∉ s := fun his => absurd (hm i his) (Finsupp.mem_support_iff.mp hi)
    exact ⟨⟨i, this⟩, rfl⟩
  have hmap : (m.comapDomain Subtype.val Subtype.val_injective.injOn).mapDomain
      Subtype.val = m :=
    Finsupp.mapDomain_comapDomain Subtype.val Subtype.val_injective m hsupp
  rw [show monomial m c =
      rename Subtype.val (monomial (m.comapDomain Subtype.val
        Subtype.val_injective.injOn) c) from by rw [rename_monomial, hmap]]
  exact killCompl_rename_app Subtype.val_injective _

omit [IsDomain R] in
/-- The projection `killCompl` (restricting to complement variables) kills exactly
the variables in `s`: `span (X '' s) ≤ ker(killVars s)`. -/
theorem span_X_image_le_ker_killCompl (s : Finset σ) :
    span ((↑s : Set σ).image (X : σ → MvPolynomial σ R)) ≤
      RingHom.ker (killVars (R := R) s).toRingHom := by
  apply span_le.mpr
  intro p hp
  obtain ⟨i, hi, rfl⟩ := hp
  rw [SetLike.mem_coe, RingHom.mem_ker]
  change killVars s (X i) = 0
  simp only [killVars, killCompl, aeval_X]
  rw [dif_neg]
  intro ⟨⟨j, hj⟩, (hjval : j = i)⟩
  exact hj (hjval ▸ hi)

omit [IsDomain R] in
/-- If a polynomial `p` is not in `span (X '' s)`, then `killVars s` does not kill it. -/
theorem killCompl_ne_zero_of_not_mem_span (s : Finset σ) (p : MvPolynomial σ R)
    (hp : p ∉ span ((↑s : Set σ).image (X : σ → MvPolynomial σ R))) :
    killVars (R := R) s p ≠ 0 := by
  classical
  rw [mem_ideal_span_X_image] at hp
  push_neg at hp
  obtain ⟨m, hm, hall⟩ := hp
  set m' := m.comapDomain Subtype.val Subtype.val_injective.injOn
  intro heq
  have hmc : p.coeff m ≠ 0 := Finsupp.mem_support_iff.mp hm
  apply hmc
  have hsupp : (↑m.support : Set σ) ⊆
      Set.range (Subtype.val : {j : σ // j ∉ s} → σ) := by
    intro i hi
    have : i ∉ s := fun his => by
      have := Finsupp.mem_support_iff.mp hi
      exact this (hall i his)
    exact ⟨⟨i, this⟩, rfl⟩
  have hmap : m'.mapDomain Subtype.val = m :=
    Finsupp.mapDomain_comapDomain Subtype.val Subtype.val_injective m hsupp
  -- The coefficient of m' in killVars s p is p.coeff m
  have hzero : (killVars (R := R) s p).coeff m' = 0 := by rw [heq]; simp
  rw [p.as_sum, map_sum, coeff_sum] at hzero
  have hterm : ∀ d ∈ p.support,
      (killVars (R := R) s (monomial d (p.coeff d))).coeff m' =
        if d = m then p.coeff m else 0 := by
    intro d hd
    by_cases hds : ∃ i ∈ (s : Set σ), d i ≠ 0
    · obtain ⟨i, his, hdi⟩ := hds
      have hmem : monomial d (p.coeff d) ∈
          span ((↑s : Set σ).image (X : σ → MvPolynomial σ R)) := by
        rw [mem_ideal_span_X_image]
        intro d' hd'
        have hd'_eq : d' = d := by
          have := support_monomial_subset (s := d) (a := p.coeff d) hd'
          exact Finset.mem_singleton.mp this
        exact ⟨i, his, hd'_eq ▸ hdi⟩
      have hk : killVars (R := R) s (monomial d (p.coeff d)) = 0 := by
        have := span_X_image_le_ker_killCompl (R := R) s hmem
        rwa [RingHom.mem_ker] at this
      simp only [hk, coeff_zero]
      split_ifs with heqm
      · subst heqm; exact absurd (hall i his) hdi
      · rfl
    · push_neg at hds
      rw [killVars_monomial_eq s d _ hds, coeff_monomial]
      have hiff : d.comapDomain Subtype.val
          Subtype.val_injective.injOn = m' ↔ d = m := by
        constructor
        · intro heq'
          ext i
          by_cases his : i ∈ s
          · rw [hds i his, hall i his]
          · have : d.comapDomain Subtype.val Subtype.val_injective.injOn
                ⟨i, his⟩ = m' ⟨i, his⟩ :=
              congr_fun (congr_arg DFunLike.coe heq') ⟨i, his⟩
            simp only [Finsupp.comapDomain_apply, m'] at this
            exact this
        · intro heq'; subst heq'; rfl
      split_ifs with h1 h2 h2
      · subst h2; rfl
      · exact absurd (hiff.mp h1) h2
      · exact absurd (hiff.mpr h2) h1
      · rfl
  rw [Finset.sum_congr rfl hterm] at hzero
  simp only [Finset.sum_ite_eq', hm, ↓reduceIte] at hzero
  exact hzero

/-- The ideal generated by variables `{X i | i in s}` is prime in `MvPolynomial sigma R`
when `R` is an integral domain.

The quotient `MvPolynomial sigma R / span(X '' s)` is isomorphic to
`MvPolynomial {j // j notin s} R`, a polynomial ring in the remaining variables,
which is a domain. The proof uses `killCompl` as a surjection with kernel
`span(X '' s)`. -/
theorem isPrime_span_X_image (s : Finset σ) :
    (span ((↑s : Set σ).image (X : σ → MvPolynomial σ R))).IsPrime := by
  rw [isPrime_iff]
  constructor
  · intro h
    have h1 : (1 : MvPolynomial σ R) ∈
        span ((↑s : Set σ).image X) := h ▸ Submodule.mem_top
    rw [mem_ideal_span_X_image] at h1
    obtain ⟨i, _, hi⟩ := h1 0 (by simp)
    exact hi (by simp)
  · intro a b hab
    by_contra! h
    obtain ⟨ha, hb⟩ := h
    have ha' := killCompl_ne_zero_of_not_mem_span s a ha
    have hb' := killCompl_ne_zero_of_not_mem_span s b hb
    have hab' : killVars (R := R) s (a * b) ≠ 0 := by
      rw [map_mul]; exact mul_ne_zero ha' hb'
    have hmem := span_X_image_le_ker_killCompl (R := R) s hab
    rw [RingHom.mem_ker] at hmem
    exact hab' hmem

end MvPolynomial
