/-
Copyright (c) 2026 Thomas Kahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Kahle
-/
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.Algebra.MvPolynomial.Rename

/-!
# Monomial ideals and prime classification in `MvPolynomial`

A monomial ideal in `MvPolynomial σ R` is one that, whenever it contains a polynomial,
also contains each of the polynomial's support monomials (with coefficient 1).

## Main results

* `Ideal.IsMonomial`: predicate for monomial ideals
* `MvPolynomial.isPrime_span_X_image_set`: the ideal `span (X '' s)` is prime
  for any `s : Set σ`
* `Ideal.exists_variable_mem_of_monomial_mem_prime`: if a monomial lies in a
  prime ideal, some variable factor lies in the ideal
* `Ideal.IsMonomial.isPrime_iff_eq_span_X_image`: a monomial ideal is prime
  iff it is generated by a set of variables

## Tags

multivariate polynomial, monomial ideal, prime ideal, variable ideal
-/

noncomputable section

variable {R : Type*} [CommRing R] [IsDomain R] {σ : Type*}

/-! ### Primality of `span (X '' s)` for `s : Set σ`

Generalization of `MvPolynomial.isPrime_span_X_image` from `Finset σ` to `Set σ`,
using the same `killCompl` strategy. -/

namespace MvPolynomial

open Ideal

/-- The projection killing variables in a set `s`. -/
private abbrev killVarsSet (s : Set σ) :
    MvPolynomial σ R →ₐ[R] MvPolynomial {j : σ // j ∉ s} R :=
  killCompl (R := R) (f := Subtype.val) Subtype.val_injective

omit [IsDomain R] in
/-- `span (X '' s) ≤ ker(killVarsSet s)` for `s : Set σ`. -/
private theorem span_X_image_set_le_ker (s : Set σ) :
    span (X '' s : Set (MvPolynomial σ R)) ≤
      RingHom.ker (killVarsSet (R := R) s).toRingHom := by
  apply span_le.mpr
  intro p hp
  obtain ⟨i, hi, rfl⟩ := hp
  rw [SetLike.mem_coe, RingHom.mem_ker]
  change killVarsSet s (X i) = 0
  simp only [killVarsSet, killCompl, aeval_X]
  rw [dif_neg]
  intro ⟨⟨j, hj⟩, (hjval : j = i)⟩
  exact hj (hjval ▸ hi)

omit [IsDomain R] in
/-- `killVarsSet s` sends a monomial supported away from `s` to
the corresponding restricted monomial. -/
private lemma killVarsSet_monomial_eq (s : Set σ) (m : σ →₀ ℕ) (c : R)
    (hm : ∀ i ∈ s, m i = 0) :
    killVarsSet (R := R) s (monomial m c) =
      monomial (m.comapDomain Subtype.val Subtype.val_injective.injOn) c := by
  have hsupp : (↑m.support : Set σ) ⊆
      Set.range (Subtype.val : {j : σ // j ∉ s} → σ) := by
    intro i hi
    have : i ∉ s := fun his => absurd (hm i his) (Finsupp.mem_support_iff.mp hi)
    exact ⟨⟨i, this⟩, rfl⟩
  have hmap : (m.comapDomain Subtype.val Subtype.val_injective.injOn).mapDomain
      Subtype.val = m :=
    Finsupp.mapDomain_comapDomain Subtype.val Subtype.val_injective m hsupp
  rw [show monomial m c =
      rename Subtype.val (monomial (m.comapDomain Subtype.val
        Subtype.val_injective.injOn) c) from by rw [rename_monomial, hmap]]
  exact killCompl_rename_app Subtype.val_injective _

omit [IsDomain R] in
/-- If `p ∉ span (X '' s)` then `killVarsSet s p ≠ 0`. -/
private theorem killVarsSet_ne_zero (s : Set σ) (p : MvPolynomial σ R)
    (hp : p ∉ span (X '' s : Set (MvPolynomial σ R))) :
    killVarsSet (R := R) s p ≠ 0 := by
  classical
  rw [mem_ideal_span_X_image] at hp
  push_neg at hp
  obtain ⟨m, hm, hall⟩ := hp
  set m' := m.comapDomain Subtype.val Subtype.val_injective.injOn
  intro heq
  have hmc : p.coeff m ≠ 0 := Finsupp.mem_support_iff.mp hm
  apply hmc
  have hzero : (killVarsSet (R := R) s p).coeff m' = 0 := by rw [heq]; simp
  rw [p.as_sum, map_sum, coeff_sum] at hzero
  have hterm : ∀ d ∈ p.support,
      (killVarsSet (R := R) s (monomial d (p.coeff d))).coeff m' =
        if d = m then p.coeff m else 0 := by
    intro d _hd
    by_cases hds : ∃ i ∈ s, d i ≠ 0
    · obtain ⟨i, his, hdi⟩ := hds
      have hmem : monomial d (p.coeff d) ∈
          span (X '' s : Set (MvPolynomial σ R)) := by
        rw [mem_ideal_span_X_image]
        intro d' hd'
        exact ⟨i, his, (Finset.mem_singleton.mp (support_monomial_subset hd')) ▸ hdi⟩
      have hk : killVarsSet (R := R) s (monomial d (p.coeff d)) = 0 := by
        have := span_X_image_set_le_ker (R := R) s hmem
        rwa [RingHom.mem_ker] at this
      simp only [hk, coeff_zero]
      split_ifs with heqm
      · subst heqm; exact absurd (hall i his) hdi
      · rfl
    · push_neg at hds
      rw [killVarsSet_monomial_eq s d _ hds, coeff_monomial]
      have hiff : d.comapDomain Subtype.val
          Subtype.val_injective.injOn = m' ↔ d = m := by
        constructor
        · intro heq'
          ext i
          by_cases his : i ∈ s
          · rw [hds i his, hall i his]
          · have : d.comapDomain Subtype.val Subtype.val_injective.injOn
                ⟨i, his⟩ = m' ⟨i, his⟩ :=
              congr_fun (congr_arg DFunLike.coe heq') ⟨i, his⟩
            simp only [Finsupp.comapDomain_apply, m'] at this
            exact this
        · intro heq'; subst heq'; rfl
      split_ifs with h1 h2 h2
      · subst h2; rfl
      · exact absurd (hiff.mp h1) h2
      · exact absurd (hiff.mpr h2) h1
      · rfl
  rw [Finset.sum_congr rfl hterm] at hzero
  simp only [Finset.sum_ite_eq', hm, ↓reduceIte] at hzero
  exact hzero

/-- The ideal `span (X '' s)` is prime in `MvPolynomial σ R` for any `s : Set σ`
when `R` is an integral domain.

Generalizes `MvPolynomial.isPrime_span_X_image` from `Finset σ` to `Set σ`.
The proof uses `killCompl` to exhibit the quotient as a polynomial ring
in the complement variables. -/
theorem isPrime_span_X_image_set (s : Set σ) :
    (span (X '' s : Set (MvPolynomial σ R))).IsPrime := by
  rw [isPrime_iff]
  constructor
  · intro h
    have h1 : (1 : MvPolynomial σ R) ∈ span (X '' s) := h ▸ Submodule.mem_top
    rw [mem_ideal_span_X_image] at h1
    obtain ⟨i, _, hi⟩ := h1 0 (by simp)
    exact hi (by simp)
  · intro a b hab
    by_contra! h
    obtain ⟨ha, hb⟩ := h
    have ha' := killVarsSet_ne_zero s a ha
    have hb' := killVarsSet_ne_zero s b hb
    have hab' : killVarsSet (R := R) s (a * b) ≠ 0 := by
      rw [map_mul]; exact mul_ne_zero ha' hb'
    have hmem := span_X_image_set_le_ker (R := R) s hab
    rw [RingHom.mem_ker] at hmem
    exact hab' hmem

end MvPolynomial

/-! ### Monomial ideals and prime classification -/

namespace Ideal

/-- An ideal `I` in `MvPolynomial σ R` is *monomial* if for every polynomial
in `I`, each support monomial (with coefficient 1) also belongs to `I`. -/
def IsMonomial {σ R : Type*} [CommSemiring R] (I : Ideal (MvPolynomial σ R)) : Prop :=
  ∀ p ∈ I, ∀ d ∈ p.support, MvPolynomial.monomial d (1 : R) ∈ I

variable {σ R : Type*} [CommRing R] [IsDomain R]

omit [IsDomain R] in
theorem exists_variable_mem_of_monomial_mem_prime
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsPrime)
    {d : σ →₀ ℕ} (hmem : MvPolynomial.monomial d (1 : R) ∈ I) :
    ∃ i ∈ d.support, MvPolynomial.X i ∈ I := by
  rw [show MvPolynomial.monomial d (1 : R) =
    ∏ x ∈ d.support, MvPolynomial.X x ^ d x
    from MvPolynomial.prod_X_pow_eq_monomial.symm] at hmem
  haveI := hI
  obtain ⟨i, hi, hpow⟩ := IsPrime.prod_mem_iff.mp hmem
  exact ⟨i, hi, hI.mem_of_pow_mem _ hpow⟩

/-- A monomial ideal in `MvPolynomial σ R` (with `R` a domain) is prime if and
only if it is generated by a set of variables. -/
theorem IsMonomial.isPrime_iff_eq_span_X_image
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsMonomial) :
    I.IsPrime ↔ ∃ s : Set σ, I = Ideal.span (MvPolynomial.X '' s) := by
  constructor
  · intro hprime
    refine ⟨{i | MvPolynomial.X i ∈ I}, le_antisymm ?_ ?_⟩
    · -- I ≤ span (X '' s): every polynomial in I has its support in span
      intro p hp
      rw [MvPolynomial.mem_ideal_span_X_image]
      intro m hm
      have hmono := hI p hp m hm
      by_cases hd : m = 0
      · -- monomial 0 1 = 1 ∈ I contradicts primeness
        subst hd
        exact absurd (eq_top_of_isUnit_mem I hmono
          (by simp [MvPolynomial.monomial_zero'])) hprime.ne_top
      · obtain ⟨i, hi, hxi⟩ := exists_variable_mem_of_monomial_mem_prime hprime hmono
        exact ⟨i, hxi, Finsupp.mem_support_iff.mp hi⟩
    · -- span (X '' s) ≤ I: immediate from the definition of s
      apply span_le.mpr
      rintro q ⟨i, hi, rfl⟩
      exact hi
  · -- variable-generated ideals are prime
    rintro ⟨s, rfl⟩
    exact MvPolynomial.isPrime_span_X_image_set s

end Ideal

end
