/-
Copyright (c) 2026 Thomas Kahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Kahle
-/
import Mathlib.RingTheory.Ideal.IsPrimary
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.Algebra.MvPolynomial.Rename

/-!
# Monomial ideals and prime classification in `MvPolynomial`

A monomial ideal in `MvPolynomial σ R` is one that, whenever it contains a polynomial,
also contains each of the polynomial's support monomials (with coefficient 1).

## Main results

* `Ideal.not_mem_exists_monomial_notMem`: if `p ∉ I`, some support monomial
  of `p` (with coefficient 1) is not in `I` — a general support extraction fact
* `Ideal.IsMonomial`: predicate for monomial ideals
* `MvPolynomial.isPrime_span_X_image_set`: the ideal `span (X '' s)` is prime
  for any `s : Set σ`
* `Ideal.exists_variable_mem_of_monomial_mem_prime`: if a monomial lies in a
  prime ideal, some variable factor lies in the ideal
* `Ideal.IsMonomial.isPrime_iff_eq_span_X_image`: a monomial ideal is prime
  iff it is generated by a set of variables

## Tags

multivariate polynomial, monomial ideal, prime ideal, variable ideal
-/

noncomputable section

variable {R : Type*} [CommRing R] [IsDomain R] {σ : Type*}

/-! ### Primality of `span (X '' s)` for `s : Set σ`

Generalization of `MvPolynomial.isPrime_span_X_image` from `Finset σ` to `Set σ`,
using the same `killCompl` strategy. -/

namespace MvPolynomial

open Ideal

/-- The projection killing variables in a set `s`. -/
private abbrev killVarsSet (s : Set σ) :
    MvPolynomial σ R →ₐ[R] MvPolynomial {j : σ // j ∉ s} R :=
  killCompl (R := R) (f := Subtype.val) Subtype.val_injective

omit [IsDomain R] in
/-- `span (X '' s) ≤ ker(killVarsSet s)` for `s : Set σ`. -/
private theorem span_X_image_set_le_ker (s : Set σ) :
    span (X '' s : Set (MvPolynomial σ R)) ≤
      RingHom.ker (killVarsSet (R := R) s).toRingHom := by
  apply span_le.mpr
  intro p hp
  obtain ⟨i, hi, rfl⟩ := hp
  rw [SetLike.mem_coe, RingHom.mem_ker]
  change killVarsSet s (X i) = 0
  simp only [killVarsSet, killCompl, aeval_X]
  rw [dif_neg]
  intro ⟨⟨j, hj⟩, (hjval : j = i)⟩
  exact hj (hjval ▸ hi)

omit [IsDomain R] in
/-- `killVarsSet s` sends a monomial supported away from `s` to
the corresponding restricted monomial. -/
private lemma killVarsSet_monomial_eq (s : Set σ) (m : σ →₀ ℕ) (c : R)
    (hm : ∀ i ∈ s, m i = 0) :
    killVarsSet (R := R) s (monomial m c) =
      monomial (m.comapDomain Subtype.val Subtype.val_injective.injOn) c := by
  have hsupp : (↑m.support : Set σ) ⊆
      Set.range (Subtype.val : {j : σ // j ∉ s} → σ) := by
    intro i hi
    have : i ∉ s := fun his => absurd (hm i his) (Finsupp.mem_support_iff.mp hi)
    exact ⟨⟨i, this⟩, rfl⟩
  have hmap : (m.comapDomain Subtype.val Subtype.val_injective.injOn).mapDomain
      Subtype.val = m :=
    Finsupp.mapDomain_comapDomain Subtype.val Subtype.val_injective m hsupp
  rw [show monomial m c =
      rename Subtype.val (monomial (m.comapDomain Subtype.val
        Subtype.val_injective.injOn) c) from by rw [rename_monomial, hmap]]
  exact killCompl_rename_app Subtype.val_injective _

omit [IsDomain R] in
/-- If `p ∉ span (X '' s)` then `killVarsSet s p ≠ 0`. -/
private theorem killVarsSet_ne_zero (s : Set σ) (p : MvPolynomial σ R)
    (hp : p ∉ span (X '' s : Set (MvPolynomial σ R))) :
    killVarsSet (R := R) s p ≠ 0 := by
  classical
  rw [mem_ideal_span_X_image] at hp
  push_neg at hp
  obtain ⟨m, hm, hall⟩ := hp
  set m' := m.comapDomain Subtype.val Subtype.val_injective.injOn
  intro heq
  have hmc : p.coeff m ≠ 0 := Finsupp.mem_support_iff.mp hm
  apply hmc
  have hzero : (killVarsSet (R := R) s p).coeff m' = 0 := by rw [heq]; simp
  rw [p.as_sum, map_sum, coeff_sum] at hzero
  have hterm : ∀ d ∈ p.support,
      (killVarsSet (R := R) s (monomial d (p.coeff d))).coeff m' =
        if d = m then p.coeff m else 0 := by
    intro d _hd
    by_cases hds : ∃ i ∈ s, d i ≠ 0
    · obtain ⟨i, his, hdi⟩ := hds
      have hmem : monomial d (p.coeff d) ∈
          span (X '' s : Set (MvPolynomial σ R)) := by
        rw [mem_ideal_span_X_image]
        intro d' hd'
        exact ⟨i, his, (Finset.mem_singleton.mp (support_monomial_subset hd')) ▸ hdi⟩
      have hk : killVarsSet (R := R) s (monomial d (p.coeff d)) = 0 := by
        have := span_X_image_set_le_ker (R := R) s hmem
        rwa [RingHom.mem_ker] at this
      simp only [hk, coeff_zero]
      split_ifs with heqm
      · subst heqm; exact absurd (hall i his) hdi
      · rfl
    · push_neg at hds
      rw [killVarsSet_monomial_eq s d _ hds, coeff_monomial]
      have hiff : d.comapDomain Subtype.val
          Subtype.val_injective.injOn = m' ↔ d = m := by
        constructor
        · intro heq'
          ext i
          by_cases his : i ∈ s
          · rw [hds i his, hall i his]
          · have : d.comapDomain Subtype.val Subtype.val_injective.injOn
                ⟨i, his⟩ = m' ⟨i, his⟩ :=
              congr_fun (congr_arg DFunLike.coe heq') ⟨i, his⟩
            simp only [Finsupp.comapDomain_apply, m'] at this
            exact this
        · intro heq'; subst heq'; rfl
      split_ifs with h1 h2 h2
      · subst h2; rfl
      · exact absurd (hiff.mp h1) h2
      · exact absurd (hiff.mpr h2) h1
      · rfl
  rw [Finset.sum_congr rfl hterm] at hzero
  simp only [Finset.sum_ite_eq', hm, ↓reduceIte] at hzero
  exact hzero

/-- The ideal `span (X '' s)` is prime in `MvPolynomial σ R` for any `s : Set σ`
when `R` is an integral domain.

Generalizes `MvPolynomial.isPrime_span_X_image` from `Finset σ` to `Set σ`.
The proof uses `killCompl` to exhibit the quotient as a polynomial ring
in the complement variables. -/
theorem isPrime_span_X_image_set (s : Set σ) :
    (span (X '' s : Set (MvPolynomial σ R))).IsPrime := by
  rw [isPrime_iff]
  constructor
  · intro h
    have h1 : (1 : MvPolynomial σ R) ∈ span (X '' s) := h ▸ Submodule.mem_top
    rw [mem_ideal_span_X_image] at h1
    obtain ⟨i, _, hi⟩ := h1 0 (by simp)
    exact hi (by simp)
  · intro a b hab
    by_contra! h
    obtain ⟨ha, hb⟩ := h
    have ha' := killVarsSet_ne_zero s a ha
    have hb' := killVarsSet_ne_zero s b hb
    have hab' : killVarsSet (R := R) s (a * b) ≠ 0 := by
      rw [map_mul]; exact mul_ne_zero ha' hb'
    have hmem := span_X_image_set_le_ker (R := R) s hab
    rw [RingHom.mem_ker] at hmem
    exact hab' hmem

end MvPolynomial

/-! ### Monomial ideals and prime classification -/

namespace Ideal

/-- An ideal `I` in `MvPolynomial σ R` is *monomial* if for every polynomial
in `I`, each support monomial (with coefficient 1) also belongs to `I`. -/
def IsMonomial {σ R : Type*} [CommSemiring R] (I : Ideal (MvPolynomial σ R)) : Prop :=
  ∀ p ∈ I, ∀ d ∈ p.support, MvPolynomial.monomial d (1 : R) ∈ I

variable {σ R : Type*} [CommRing R] [IsDomain R]

omit [IsDomain R] in
theorem exists_variable_mem_of_monomial_mem_prime
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsPrime)
    {d : σ →₀ ℕ} (hmem : MvPolynomial.monomial d (1 : R) ∈ I) :
    ∃ i ∈ d.support, MvPolynomial.X i ∈ I := by
  rw [show MvPolynomial.monomial d (1 : R) =
    ∏ x ∈ d.support, MvPolynomial.X x ^ d x
    from MvPolynomial.prod_X_pow_eq_monomial.symm] at hmem
  haveI := hI
  obtain ⟨i, hi, hpow⟩ := IsPrime.prod_mem_iff.mp hmem
  exact ⟨i, hi, hI.mem_of_pow_mem _ hpow⟩

/-- A monomial ideal in `MvPolynomial σ R` (with `R` a domain) is prime if and
only if it is generated by a set of variables. -/
theorem IsMonomial.isPrime_iff_eq_span_X_image
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsMonomial) :
    I.IsPrime ↔ ∃ s : Set σ, I = Ideal.span (MvPolynomial.X '' s) := by
  constructor
  · intro hprime
    refine ⟨{i | MvPolynomial.X i ∈ I}, le_antisymm ?_ ?_⟩
    · -- I ≤ span (X '' s): every polynomial in I has its support in span
      intro p hp
      rw [MvPolynomial.mem_ideal_span_X_image]
      intro m hm
      have hmono := hI p hp m hm
      by_cases hd : m = 0
      · -- monomial 0 1 = 1 ∈ I contradicts primeness
        subst hd
        exact absurd (eq_top_of_isUnit_mem I hmono
          (by simp [MvPolynomial.monomial_zero'])) hprime.ne_top
      · obtain ⟨i, hi, hxi⟩ := exists_variable_mem_of_monomial_mem_prime hprime hmono
        exact ⟨i, hxi, Finsupp.mem_support_iff.mp hi⟩
    · -- span (X '' s) ≤ I: immediate from the definition of s
      apply span_le.mpr
      rintro q ⟨i, hi, rfl⟩
      exact hi
  · -- variable-generated ideals are prime
    rintro ⟨s, rfl⟩
    exact MvPolynomial.isPrime_span_X_image_set s

/-! ### Basic `IsMonomial` API -/

omit [IsDomain R] in
theorem IsMonomial.span_X_image (s : Set σ) :
    IsMonomial (span (MvPolynomial.X '' s : Set (MvPolynomial σ R))) := by
  intro p hp d hd
  rw [MvPolynomial.mem_ideal_span_X_image] at hp ⊢
  intro m hm
  have hm_eq : m = d :=
    Finset.mem_singleton.mp (MvPolynomial.support_monomial_subset hm)
  exact hm_eq ▸ hp d hd

/-! ### Support extraction lemma

If a polynomial does not belong to an ideal, then at least one of its support
monomials (with coefficient 1) is not in the ideal. This is the contrapositive of
the fact that any polynomial equals `∑ d in p.support, C (coeff d p) * monomial d 1`,
so if every such monomial were in `I`, the polynomial would be too.

This requires only `CommRing R` — no domain, ordering, or monomial-ideal hypotheses. -/

open MvPolynomial in
omit [IsDomain R] in
/-- If a polynomial `p` is not in an ideal `I`, then some support monomial of `p`
(with coefficient 1) is not in `I`. -/
lemma not_mem_exists_monomial_notMem
    {I : Ideal (MvPolynomial σ R)}
    {p : MvPolynomial σ R} (hp : p ∉ I) :
    ∃ d ∈ p.support, monomial d (1 : R) ∉ I := by
  by_contra h; push_neg at h; apply hp
  conv => rw [p.as_sum]
  exact Submodule.sum_mem I fun d hd => by
    rw [show monomial d (coeff d p) = C (coeff d p) * monomial d 1 from by
      rw [C_mul_monomial, mul_one]]
    exact I.mul_mem_left _ (h d hd)

/-! ### Primary monomial ideal criterion -/

theorem isPrimary_monomial_criterion
    {I : Ideal (MvPolynomial σ R)}
    (hprim : I.IsPrimary)
    {s : Set σ} (hrad : I.radical = span (MvPolynomial.X '' s))
    {d : σ →₀ ℕ} (hd : MvPolynomial.monomial d (1 : R) ∉ I)
    {i : σ} (hi : i ∉ s) :
    MvPolynomial.monomial (d + Finsupp.single i 1) (1 : R) ∉ I := by
  intro hmem
  have heq : MvPolynomial.monomial (d + Finsupp.single i 1) (1 : R) =
      MvPolynomial.X i * MvPolynomial.monomial d 1 := by
    simp only [MvPolynomial.X, MvPolynomial.monomial_mul, one_mul, add_comm]
  rw [heq] at hmem
  have h := hprim.mem_or_mem (show MvPolynomial.X i • MvPolynomial.monomial d 1 ∈ I
    from by rwa [smul_eq_mul])
  rw [show Submodule.colon I ⊤ = I from by ext; simp] at h
  rcases h with h1 | h2
  · exact hd h1
  · rw [hrad, MvPolynomial.mem_ideal_span_X_image] at h2
    have his : i ∈ s := by
      obtain ⟨j, hj, hne⟩ := h2 (Finsupp.single i 1) (by simp)
      have : j = i := by
        by_contra hji
        exact hne (Finsupp.single_eq_of_ne hji)
      rwa [← this]
    exact hi his

end Ideal

/-- An ideal spanned by polynomials with at-most-singleton support is monomial:
for every `f ∈ span S` and `d ∈ f.support`, `monomial d 1 ∈ span S`. -/
theorem isMonomial_span_of_support_singleton {σ : Type*} {K : Type*} [Field K]
    {S : Set (MvPolynomial σ K)}
    (hS : ∀ s ∈ S, ∃ d, s.support ⊆ {d}) :
    (Ideal.span S).IsMonomial := by
  classical
  intro f hf
  induction hf using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨e, he⟩ := hS x hx
    intro d hd
    have hde : d = e := Finset.mem_singleton.mp (he hd)
    have hc_ne : x.coeff e ≠ 0 :=
      MvPolynomial.mem_support_iff.mp (hde ▸ hd)
    rw [hde]
    have heq : MvPolynomial.monomial e (1 : K) =
        MvPolynomial.C (x.coeff e)⁻¹ * x := by
      set c := x.coeff e with hc_def
      have hx_eq : x = MvPolynomial.monomial e c := by
        ext m
        simp only [MvPolynomial.coeff_monomial]
        by_cases hme : e = m
        · simp [hme, hc_def]
        · rw [if_neg hme]
          exact MvPolynomial.notMem_support_iff.mp
            (fun hm => hme (Finset.mem_singleton.mp (he hm)).symm)
      rw [hx_eq, MvPolynomial.C_mul_monomial, inv_mul_cancel₀ hc_ne]
    rw [heq]
    exact (Ideal.span S).mul_mem_left _ (Ideal.subset_span hx)
  | zero =>
    intro d hd; simp at hd
  | add x y _ _ ihx ihy =>
    intro d hd
    rcases Finset.mem_union.mp (Finset.mem_of_subset MvPolynomial.support_add hd) with h | h
    · exact ihx d h
    · exact ihy d h
  | smul a x _ ihx =>
    intro d hd
    simp only [smul_eq_mul] at hd
    have hd_mem := Finset.mem_of_subset (MvPolynomial.support_mul a x) hd
    rw [Finset.mem_add] at hd_mem
    obtain ⟨da, hda, df, hdf, rfl⟩ := hd_mem
    have hdf_mem := ihx df hdf
    rw [show MvPolynomial.monomial (da + df) (1 : K) =
      MvPolynomial.monomial da (1 : K) * MvPolynomial.monomial df 1 from by
        rw [MvPolynomial.monomial_mul, one_mul]]
    exact (Ideal.span S).mul_mem_left _ hdf_mem

/-! ### Radical of a monomial ideal is monomial -/

section RadicalMonomial

open MvPolynomial Finsupp

variable {R : Type*} [CommRing R] [IsDomain R] {σ : Type*} [LinearOrder σ]

/-- Auxiliary: the lex-maximal exponent in the support of a nonzero polynomial,
viewed in `Lex (σ →₀ ℕ)`. -/
private noncomputable def lexMaxSupport (p : MvPolynomial σ R) (hp : p ≠ 0) : σ →₀ ℕ :=
  ofLex ((p.support.image toLex).max' (by
    rw [Finset.image_nonempty]
    exact MvPolynomial.support_nonempty.mpr hp))

omit [IsDomain R] in
private theorem lexMaxSupport_mem_support (p : MvPolynomial σ R) (hp : p ≠ 0) :
    lexMaxSupport p hp ∈ p.support := by
  simp only [lexMaxSupport]
  have hne : (p.support.image toLex).Nonempty := by
    rw [Finset.image_nonempty]; exact MvPolynomial.support_nonempty.mpr hp
  have hmem := (p.support.image toLex).max'_mem hne
  rw [Finset.mem_image] at hmem
  obtain ⟨d, hd, hdeq⟩ := hmem
  convert hd
  change ofLex ((p.support.image toLex).max' hne) = d
  rw [← hdeq, ofLex_toLex]

omit [IsDomain R] in
private theorem lexMaxSupport_le (p : MvPolynomial σ R) (hp : p ≠ 0) (d : σ →₀ ℕ)
    (hd : d ∈ p.support) : toLex d ≤ toLex (lexMaxSupport p hp) := by
  simp only [lexMaxSupport, toLex_ofLex]
  exact Finset.le_max' _ _ (Finset.mem_image.mpr ⟨d, hd, rfl⟩)

omit [IsDomain R] in
/-- All elements of `(p ^ n).support` are lex-bounded by `n • d` where `d` is the
lex-maximum of `p.support`. -/
private theorem support_pow_le_lex (p : MvPolynomial σ R) (hp : p ≠ 0) (n : ℕ)
    (e : σ →₀ ℕ) (he : e ∈ (p ^ n).support) :
    toLex e ≤ toLex (n • lexMaxSupport p hp) := by
  classical
  set d := lexMaxSupport p hp
  induction n generalizing e with
  | zero =>
    simp only [pow_zero, zero_smul] at he ⊢
    have h1 : (1 : MvPolynomial σ R) = MvPolynomial.monomial 0 1 := by
      rw [MvPolynomial.monomial_zero', map_one]
    rw [h1, MvPolynomial.mem_support_iff, MvPolynomial.coeff_monomial] at he
    split_ifs at he with heq
    · rw [heq]
    · exact absurd rfl he
  | succ n ihn =>
    rw [pow_succ] at he
    have hsub := MvPolynomial.support_mul (p ^ n) p
    have he' := Finset.mem_of_subset hsub he
    rw [Finset.mem_add] at he'
    obtain ⟨u, hu, v, hv, huv⟩ := he'
    rw [show (n + 1) • d = n • d + d from by rw [add_smul, one_smul], ← huv]
    exact add_le_add (ihn u hu) (lexMaxSupport_le p hp v hv)

/-- Key lemma: for a nonzero polynomial over a domain with `d_max` the lex-maximal
exponent in the support, we have `coeff (n • d_max) (p ^ n) = (coeff d_max p) ^ n`.

This is essentially `MonomialOrder.coeff_pow_nsmul_degree` but proved directly
from the lex order without requiring `WellFoundedGT`. -/
private theorem coeff_pow_lexMax (p : MvPolynomial σ R) (hp : p ≠ 0) (n : ℕ) :
    (p ^ n).coeff (n • lexMaxSupport p hp) = (p.coeff (lexMaxSupport p hp)) ^ n := by
  classical
  set d := lexMaxSupport p hp with hd_def
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, add_smul, one_smul, coeff_mul]
    -- The only contributing antidiagonal term is (n • d, d)
    rw [Finset.sum_eq_single (n • d, d)]
    · rw [ih, pow_succ]
    · -- Other terms contribute 0
      rintro ⟨a, b⟩ hab hne
      rw [Finset.mem_antidiagonal] at hab
      by_cases hbs : b ∈ p.support
      · -- b is in support, so toLex b ≤ toLex d; if b ≠ d then toLex b < toLex d
        have hble : toLex b ≤ toLex d := lexMaxSupport_le p hp b hbs
        by_cases hbd : b = d
        · -- b = d, so a = n • d, and the pair is (n • d, d) — contradicts hne
          subst hbd
          have ha_eq : a = n • d := add_right_cancel hab
          exact absurd (by rw [ha_eq] : (a, d) = (n • d, d)) hne
        · -- b ≠ d so toLex b < toLex d
          have hblt : toLex b < toLex d := lt_of_le_of_ne hble (fun h => hbd (toLex.injective h))
          -- Then a + b = (n+1) • d implies a > n • d, so coeff a (p^n) = 0
          -- because all elements of (p^n).support are ≤ n • d (in lex)
          suffices ha : a ∉ (p ^ n).support by
            rw [MvPolynomial.notMem_support_iff.mp ha, zero_mul]
          intro ha_mem
          have hale : toLex a ≤ toLex (n • d) := support_pow_le_lex p hp n a ha_mem
          have hlt : toLex a + toLex b < toLex (n • d) + toLex d :=
            add_lt_add_of_le_of_lt hale hblt
          change toLex (a + b) < toLex (n • d + d) at hlt
          rw [hab] at hlt
          exact lt_irrefl _ hlt
      · -- b ∉ p.support means coeff b p = 0
        rw [MvPolynomial.notMem_support_iff.mp hbs, mul_zero]
    · -- (n • d, d) ∉ antidiagonal is impossible
      simp [Finset.mem_antidiagonal]

/-- The coefficient of `d_max + e_max` in `p * q` equals
`coeff d_max p * coeff e_max q` where these are the respective lex-maximal
support elements. No cancellation occurs at the leading position. -/
private theorem coeff_mul_lexMax (p q : MvPolynomial σ R) (hp : p ≠ 0) (hq : q ≠ 0) :
    (p * q).coeff (lexMaxSupport p hp + lexMaxSupport q hq) =
      p.coeff (lexMaxSupport p hp) * q.coeff (lexMaxSupport q hq) := by
  classical
  set d := lexMaxSupport p hp; set e := lexMaxSupport q hq
  rw [coeff_mul, Finset.sum_eq_single (d, e)]
  · rintro ⟨a, b⟩ hab hne
    rw [Finset.mem_antidiagonal] at hab
    by_cases hbs : b ∈ q.support
    · have hble := lexMaxSupport_le q hq b hbs
      by_cases hbd : b = e
      · subst hbd
        exact absurd
          (show (a, e) = (d, e) from Prod.ext (add_right_cancel hab) rfl) hne
      · have hblt := lt_of_le_of_ne hble (fun h => hbd (toLex.injective h))
        by_cases has : a ∈ p.support
        · have hlt := add_lt_add_of_le_of_lt (lexMaxSupport_le p hp a has) hblt
          change toLex (a + b) < toLex (d + e) at hlt
          rw [hab] at hlt; exact absurd hlt (lt_irrefl _)
        · rw [MvPolynomial.notMem_support_iff.mp has, zero_mul]
    · rw [MvPolynomial.notMem_support_iff.mp hbs, mul_zero]
  · simp [Finset.mem_antidiagonal]

/-- The sum of lex-maximal exponents lies in the support of the product. -/
private theorem lexMax_add_mem_mul_support
    (p q : MvPolynomial σ R) (hp : p ≠ 0) (hq : q ≠ 0) :
    lexMaxSupport p hp + lexMaxSupport q hq ∈ (p * q).support := by
  rw [MvPolynomial.mem_support_iff, coeff_mul_lexMax]
  exact mul_ne_zero
    (MvPolynomial.mem_support_iff.mp (lexMaxSupport_mem_support p hp))
    (MvPolynomial.mem_support_iff.mp (lexMaxSupport_mem_support q hq))

namespace Ideal

/-- The radical of a monomial ideal is monomial. -/
theorem IsMonomial.radical_isMonomial
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsMonomial) :
    I.radical.IsMonomial := by
  classical
  intro p hp
  -- Strong induction on the support size
  suffices ∀ k (q : MvPolynomial σ R), q ∈ I.radical → q.support.card ≤ k →
      ∀ d ∈ q.support, MvPolynomial.monomial d 1 ∈ I.radical by
    exact this p.support.card p hp le_rfl
  intro k
  induction k with
  | zero =>
    intro q _ hq d hd
    simp only [Nat.le_zero, Finset.card_eq_zero] at hq
    simp [hq] at hd
  | succ k ih =>
    intro q hq hcard d hd
    by_cases hq0 : q = 0
    · exact absurd (hq0 ▸ hd) (by simp)
    -- Get d_max = lex maximum of q.support
    set d_max := lexMaxSupport q hq0
    -- Step 1: Show monomial d_max 1 ∈ I.radical
    have hd_max_rad : MvPolynomial.monomial d_max 1 ∈ I.radical := by
      rw [mem_radical_iff] at hq ⊢
      obtain ⟨n, hn⟩ := hq
      refine ⟨n, ?_⟩
      rw [MvPolynomial.monomial_pow, one_pow]
      -- n • d_max ∈ (q^n).support because coeff is nonzero
      have hcoeff := coeff_pow_lexMax q hq0 n
      have hcoeff_ne : q.coeff d_max ≠ 0 :=
        MvPolynomial.mem_support_iff.mp (lexMaxSupport_mem_support q hq0)
      have hpow_ne : (q.coeff d_max) ^ n ≠ 0 := pow_ne_zero n hcoeff_ne
      have hcoeff_ne' : (q ^ n).coeff (n • d_max) ≠ 0 := by rw [hcoeff]; exact hpow_ne
      have hmem : n • d_max ∈ (q ^ n).support := MvPolynomial.mem_support_iff.mpr hcoeff_ne'
      exact hI (q ^ n) hn (n • d_max) hmem
    -- Step 2: q' = q - monomial d_max (coeff d_max q) ∈ I.radical
    set c := q.coeff d_max
    set lt := MvPolynomial.monomial d_max c with hlt_def
    have hlt_rad : lt ∈ I.radical := by
      rw [hlt_def]
      have : MvPolynomial.monomial d_max c =
          MvPolynomial.C c * MvPolynomial.monomial d_max 1 := by
        rw [MvPolynomial.C_mul_monomial, mul_one]
      rw [this]
      exact I.radical.mul_mem_left _ hd_max_rad
    set q' := q - lt
    have hq'_rad : q' ∈ I.radical := I.radical.sub_mem hq hlt_rad
    -- Step 3: q'.support.card < q.support.card (since d_max is removed)
    have hd_max_not_supp : d_max ∉ q'.support := by
      rw [MvPolynomial.mem_support_iff, not_not]
      simp only [q', lt]
      simp [c]
    have hq'_sub : q'.support ⊆ q.support.erase d_max := by
      intro e he
      rw [Finset.mem_erase]
      constructor
      · intro heq
        exact hd_max_not_supp (heq ▸ he)
      · rw [MvPolynomial.mem_support_iff] at he ⊢
        intro heq
        apply he
        simp only [q', lt, MvPolynomial.coeff_sub, MvPolynomial.coeff_monomial]
        split_ifs with h
        · simp [c, ← h]
        · simp [heq]
    have hq'_card : q'.support.card ≤ k := by
      calc q'.support.card
          ≤ (q.support.erase d_max).card := Finset.card_le_card hq'_sub
        _ = q.support.card - 1 := Finset.card_erase_of_mem (lexMaxSupport_mem_support q hq0)
        _ ≤ k := by omega
    -- Step 4: By induction, all monomials of q' are in I.radical
    -- Now handle d: either d = d_max or d ∈ q'.support
    by_cases hdd : d = d_max
    · exact hdd ▸ hd_max_rad
    · -- d ≠ d_max, so d ∈ q'.support
      have hd_q' : d ∈ q'.support := by
        rw [MvPolynomial.mem_support_iff] at hd ⊢
        simp only [q', lt, MvPolynomial.coeff_sub, MvPolynomial.coeff_monomial,
          if_neg (Ne.symm hdd), sub_zero]
        exact hd
      exact ih q' hq'_rad hq'_card d hd_q'

end Ideal

end RadicalMonomial

/-! ### Primary monomial ideal: forward direction -/

section PrimaryForward

variable {R : Type*} [CommRing R] [IsDomain R] {σ : Type*} [LinearOrder σ]

namespace Ideal

/-- The forward direction of the primary monomial ideal characterization:
if a monomial ideal is primary, then its radical is generated by variables
and the monomial criterion holds. -/
theorem IsMonomial.isPrimary_radical_eq_span_X
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsMonomial) (hprim : I.IsPrimary) :
    ∃ s : Set σ,
      I.radical = span (MvPolynomial.X '' s) ∧
      ∀ d : σ →₀ ℕ, MvPolynomial.monomial d (1 : R) ∉ I →
        ∀ i, i ∉ s →
          MvPolynomial.monomial (d + Finsupp.single i 1) (1 : R) ∉ I := by
  have hrad_mono := hI.radical_isMonomial
  have hrad_prime : I.radical.IsPrime := by
    have := hprim.isPrime_radical_colon
    rwa [show Submodule.colon I Set.univ = I from by ext; simp] at this
  obtain ⟨s, hs⟩ := hrad_mono.isPrime_iff_eq_span_X_image.mp hrad_prime
  exact ⟨s, hs, fun d hd i hi hmem => isPrimary_monomial_criterion hprim hs hd hi hmem⟩

end Ideal

end PrimaryForward

/-! ### Primary converse helpers: exponent-outside-radical invariance

These lemmas show that, given the monomial criterion from the primary
characterization, monomial membership depends only on the `s`-part
of the exponent. -/

section PrimaryConverseHelpers

variable {R : Type*} [CommRing R] {σ : Type*}

open MvPolynomial Finsupp

namespace Ideal

/-- Adding `single i n` for `i ∉ s` preserves monomial non-membership,
by iterating the single-step primary criterion. -/
private theorem monomial_notMem_add_single
    {I : Ideal (MvPolynomial σ R)} {s : Set σ}
    (hcrit : ∀ d : σ →₀ ℕ, monomial d (1 : R) ∉ I →
      ∀ j, j ∉ s → monomial (d + single j 1) (1 : R) ∉ I)
    {d : σ →₀ ℕ} {i : σ} (hi : i ∉ s)
    (n : ℕ) (hd : monomial d (1 : R) ∉ I) :
    monomial (d + single i n) (1 : R) ∉ I := by
  induction n with
  | zero => simpa [single_zero] using hd
  | succ k ih =>
    rw [Finsupp.single_add, ← add_assoc]
    exact hcrit _ ih i hi

/-- Adding any exponent supported outside `s` preserves monomial non-membership.
Iterates the single-step primary criterion over `Finsupp.induction`. -/
theorem monomial_notMem_add_outside
    {I : Ideal (MvPolynomial σ R)} {s : Set σ}
    (hcrit : ∀ d : σ →₀ ℕ, monomial d (1 : R) ∉ I →
      ∀ j, j ∉ s → monomial (d + single j 1) (1 : R) ∉ I)
    {d e : σ →₀ ℕ} (he : ∀ i ∈ s, e i = 0)
    (hd : monomial d (1 : R) ∉ I) :
    monomial (d + e) (1 : R) ∉ I := by
  suffices ∀ (e d : σ →₀ ℕ),
      (∀ i ∈ s, e i = 0) → monomial d (1 : R) ∉ I →
        monomial (d + e) (1 : R) ∉ I from this e d he hd
  intro e
  induction e using Finsupp.induction with
  | zero => intro d _ hd'; simpa
  | single_add a b f haf hb ih =>
    intro d he' hd'
    have ha_s : a ∉ s := fun has => hb <| by
      have := he' a has
      rw [Finsupp.add_apply, Finsupp.single_eq_same,
        Finsupp.notMem_support_iff.mp haf, add_zero] at this
      exact this
    have hf_s : ∀ i ∈ s, f i = 0 := by
      intro i his
      have := he' i his
      rw [Finsupp.add_apply,
        Finsupp.single_eq_of_ne' (show a ≠ i from fun h => ha_s (h ▸ his)),
        zero_add] at this
      exact this
    rw [add_comm (Finsupp.single a b) f, ← add_assoc]
    exact monomial_notMem_add_single hcrit ha_s b (ih d hf_s hd')

/-- Monomial membership is invariant under adding exponents outside `s`. -/
theorem monomial_mem_iff_add_outside
    {I : Ideal (MvPolynomial σ R)} {s : Set σ}
    (hcrit : ∀ d : σ →₀ ℕ, monomial d (1 : R) ∉ I →
      ∀ j, j ∉ s → monomial (d + single j 1) (1 : R) ∉ I)
    {d e : σ →₀ ℕ} (he : ∀ i ∈ s, e i = 0) :
    monomial d (1 : R) ∈ I ↔ monomial (d + e) (1 : R) ∈ I := by
  constructor
  · intro h
    have hmul : monomial e (1 : R) * monomial d 1 ∈ I := I.mul_mem_left _ h
    rwa [monomial_mul, one_mul, add_comm e d] at hmul
  · exact fun h => by_contra fun hd => monomial_notMem_add_outside hcrit he hd h

/-- Monomial membership depends only on the `s`-part of the exponent:
coordinates outside `s` can be zeroed out without changing membership. -/
theorem monomial_mem_iff_filter
    {I : Ideal (MvPolynomial σ R)} {s : Set σ} [DecidablePred (· ∈ s)]
    (hcrit : ∀ d : σ →₀ ℕ, monomial d (1 : R) ∉ I →
      ∀ j, j ∉ s → monomial (d + single j 1) (1 : R) ∉ I)
    (d : σ →₀ ℕ) :
    monomial d (1 : R) ∈ I ↔
      monomial (d.filter (· ∈ s)) (1 : R) ∈ I := by
  have hdecomp : d = d.filter (· ∈ s) + d.filter (fun i => ¬ i ∈ s) := by
    ext i; simp only [Finsupp.add_apply, Finsupp.filter_apply]
    split_ifs <;> omega
  have he : ∀ i ∈ s, (d.filter (fun i => ¬ i ∈ s)) i = 0 := fun i his => by
    simp [his]
  conv_lhs => rw [hdecomp]
  exact (monomial_mem_iff_add_outside hcrit he).symm

end Ideal

end PrimaryConverseHelpers

/-! ### Primary monomial ideal: converse direction -/

section PrimaryConverse

variable {R : Type*} [CommRing R] [IsDomain R] {σ : Type*} [LinearOrder σ]

open MvPolynomial Finsupp

namespace Ideal

/-- If `x * y ∈ I` and the lex-max support element of `y` is outside `s`,
then `x ∈ I`. This is proved by peeling off the leading term of `x`
using the structural invariance lemma. -/
private theorem mem_of_mul_mem_of_lexMax_outside
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsMonomial)
    {s : Set σ}
    (hcrit : ∀ d : σ →₀ ℕ, monomial d (1 : R) ∉ I →
      ∀ j, j ∉ s → monomial (d + single j 1) (1 : R) ∉ I)
    {x y : MvPolynomial σ R} (hxy : x * y ∈ I) (hy0 : y ≠ 0)
    (hm_out : ∀ j ∈ s, (lexMaxSupport y hy0) j = 0) :
    x ∈ I := by
  by_cases hx0 : x = 0
  · exact hx0 ▸ I.zero_mem
  -- Strong induction on x.support.card
  suffices ∀ (n : ℕ) (x : MvPolynomial σ R), x.support.card ≤ n →
      x ≠ 0 → x * y ∈ I → x ∈ I from
    this x.support.card x le_rfl hx0 hxy
  intro n
  induction n with
  | zero =>
    intro x hx hx0
    exact absurd (MvPolynomial.support_eq_empty.mp
      (Finset.card_eq_zero.mp (Nat.le_zero.mp hx))) hx0
  | succ k ih =>
    intro x hcard hx0 hxy_mem
    set e := lexMaxSupport y hy0
    set d := lexMaxSupport x hx0
    -- d + e ∈ (x * y).support by coeff_mul_lexMax
    have hde_I : monomial (d + e) (1 : R) ∈ I :=
      hI _ hxy_mem _ (lexMax_add_mem_mul_support x y hx0 hy0)
    -- Since e is outside s, monomial d 1 ∈ I
    have hd_I : monomial d (1 : R) ∈ I :=
      (monomial_mem_iff_add_outside hcrit hm_out).mpr hde_I
    -- Subtract leading term
    set c := coeff d x
    set lt := monomial d c
    have hlt_I : lt ∈ I := by
      change monomial d c ∈ I
      rw [show monomial d c = C c * monomial d 1 from by rw [C_mul_monomial, mul_one]]
      exact I.mul_mem_left _ hd_I
    set x' := x - lt
    have hx'_mem : x' * y ∈ I := by
      have : x' * y = x * y - lt * y := by ring
      rw [this]; exact I.sub_mem hxy_mem (I.mul_mem_right y hlt_I)
    -- x' has smaller support
    have hd_not_x' : d ∉ x'.support := by
      rw [MvPolynomial.mem_support_iff, not_not]; simp [x', lt, c]
    have hx'_sub : x'.support ⊆ x.support.erase d := by
      intro e' he'
      rw [Finset.mem_erase]; constructor
      · intro heq; exact hd_not_x' (heq ▸ he')
      · rw [MvPolynomial.mem_support_iff] at he' ⊢; intro h; apply he'
        simp only [x', lt, MvPolynomial.coeff_sub, MvPolynomial.coeff_monomial]
        split_ifs with heq
        · subst heq; simp [c]
        · simp [h]
    have hx'_card : x'.support.card ≤ k := by
      calc x'.support.card
          ≤ (x.support.erase d).card := Finset.card_le_card hx'_sub
        _ = x.support.card - 1 :=
            Finset.card_erase_of_mem (lexMaxSupport_mem_support x hx0)
        _ ≤ k := by omega
    by_cases hx'0 : x' = 0
    · -- x = lt ∈ I
      have : x = lt := sub_eq_zero.mp hx'0
      rw [this]; exact hlt_I
    · -- By IH, x' ∈ I, so x = x' + lt ∈ I
      have hx'_I := ih x' hx'_card hx'0 hx'_mem
      have : x = x' + lt := by simp [x', lt]
      rw [this]; exact I.add_mem hx'_I hlt_I

omit [LinearOrder σ] in
/-- Auxiliary: filter of sum equals sum of filters. -/
private lemma filter_add_eq {s : Set σ} [DecidablePred (· ∈ s)]
    (u v : σ →₀ ℕ) (hv : ∀ i ∈ s, v i = 0) :
    (u + v).filter (· ∈ s) = u.filter (· ∈ s) := by
  ext i
  simp only [Finsupp.filter_apply, Finsupp.add_apply]
  split_ifs with hi
  · rw [hv i hi, add_zero]
  · rfl

omit [LinearOrder σ] in
/-- Auxiliary: if u_s + v_s = γ then u_s ≤ γ (componentwise). -/
private lemma filter_le_of_add_filter_eq {s : Set σ} [DecidablePred (· ∈ s)]
    {u v : σ →₀ ℕ} {γ : σ →₀ ℕ}
    (hfilt : (u + v).filter (· ∈ s) = γ) :
    u.filter (· ∈ s) ≤ γ := by
  rw [← hfilt, Finsupp.filter_add]
  exact le_add_right le_rfl

omit [IsDomain R] in
/-- Coefficient of a filtered monomial sum: extract one term by matching exponent. -/
private lemma coeff_filtered_sum {S : Finset (σ →₀ ℕ)} {P : (σ →₀ ℕ) → Prop}
    [DecidablePred P] {c : (σ →₀ ℕ) → R} {u : σ →₀ ℕ} :
    coeff u (S.sum fun d => if P d then monomial d (c d) else 0) =
      if P u ∧ u ∈ S then c u else 0 := by
  trans ∑ d ∈ S, coeff u (if P d then monomial d (c d) else 0)
  · exact MvPolynomial.coeff_sum S _ u
  split_ifs with h
  · obtain ⟨hp, hu⟩ := h
    rw [Finset.sum_eq_single u]
    · simp [hp]
    · intro d _ hne; split_ifs with hp'
      · rw [coeff_monomial, if_neg hne]
      · simp
    · intro h; exact absurd hu h
  · push_neg at h
    apply Finset.sum_eq_zero
    intro d hd
    by_cases hp : P d
    · simp only [if_pos hp, coeff_monomial]
      split_ifs with heq
      · subst heq; exact absurd hd (h hp)
      · rfl
    · rw [if_neg hp]; simp

/-- The converse direction: the monomial criterion implies primary. -/
theorem IsMonomial.isPrimary_of_criterion
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsMonomial) (hne : I ≠ ⊤)
    {s : Set σ} (hrad : I.radical = Ideal.span (X '' s))
    (hcrit : ∀ d : σ →₀ ℕ, monomial d (1 : R) ∉ I →
      ∀ j, j ∉ s → monomial (d + single j 1) (1 : R) ∉ I) :
    I.IsPrimary := by
  classical
  rw [Ideal.isPrimary_iff]
  refine ⟨hne, fun {a b} hab => ?_⟩
  -- Goal: a * b ∈ I → a ∈ I ∨ b ∈ I.radical
  -- Reduce via primality of span(X '' s)
  have hs_prime := MvPolynomial.isPrime_span_X_image_set (R := R) s
  have hab_rad : a * b ∈ span (X '' s) := hrad ▸ Ideal.le_radical hab
  -- If b ∈ span(X '' s) = I.radical, we're done
  rcases hs_prime.mem_or_mem hab_rad with ha_s | hb_s
  · -- a ∈ span(X '' s), need a ∈ I ∨ b ∈ I.radical
    by_cases hb_s' : b ∈ span (X '' s)
    · exact Or.inr (hrad ▸ hb_s')
    · -- b ∉ span(X '' s), must show a ∈ I
      left
      -- Derive contradiction from a ∉ I
      by_contra ha_nI
      -- a ∉ I → ∃ bad monomial
      obtain ⟨d₀, hd₀_supp, hd₀_nI⟩ := Ideal.not_mem_exists_monomial_notMem ha_nI
      -- d₀.filter (· ∈ s) ≠ 0 since a ∈ span(X '' s)
      have hd₀_filt_ne : d₀.filter (· ∈ s) ≠ 0 := by
        rw [MvPolynomial.mem_ideal_span_X_image] at ha_s
        obtain ⟨i, hi, hdi⟩ := ha_s d₀ hd₀_supp
        intro h
        have : (d₀.filter (· ∈ s)) i = 0 := by
          rw [h]; simp
        rw [Finsupp.filter_apply_pos (· ∈ s) d₀ hi] at this
        exact hdi this
      -- The set of "bad s-exponents" is nonempty
      let badExps : Set (σ →₀ ℕ) :=
        {γ | ∃ d ∈ a.support, d.filter (· ∈ s) = γ ∧ monomial d (1 : R) ∉ I}
      have hbad_ne : badExps.Nonempty :=
        ⟨d₀.filter (· ∈ s), ⟨d₀, hd₀_supp, rfl, hd₀_nI⟩⟩
      -- Choose γ minimal in componentwise order (wellFoundedLT on σ →₀ ℕ)
      have hwf : WellFounded ((· < ·) : (σ →₀ ℕ) → (σ →₀ ℕ) → Prop) :=
        IsWellFounded.wf
      set γ := hwf.min badExps hbad_ne
      have hγ_mem : γ ∈ badExps := hwf.min_mem badExps hbad_ne
      obtain ⟨d₁, hd₁_supp, hd₁_eq, hd₁_nI⟩ := hγ_mem
      have hγ_nI : monomial γ (1 : R) ∉ I := by
        rwa [← hd₁_eq, ← monomial_mem_iff_filter hcrit d₁]
      -- Minimality: no bad s-exponent is strictly less than γ
      have hγ_min : ∀ γ' ∈ badExps, ¬(γ' < γ) :=
        fun γ' hγ' => hwf.not_lt_min badExps hbad_ne hγ'
      -- Key: any d ∈ a.support with d.filter(·∈s) < γ has monomial d 1 ∈ I
      have hsmall_in_I : ∀ d ∈ a.support, d.filter (· ∈ s) < γ →
          monomial d (1 : R) ∈ I := by
        intro d hd hlt
        by_contra hd_nI
        exact hγ_min (d.filter (· ∈ s)) ⟨d, hd, rfl, hd_nI⟩ hlt
      -- b ∉ span(X '' s): some monomial of b is entirely outside s
      rw [MvPolynomial.mem_ideal_span_X_image] at hb_s'
      push_neg at hb_s'
      obtain ⟨e₀, he₀_supp, he₀_s⟩ := hb_s'
      -- Define sub-polynomials:
      -- a_γ: monomials of a with s-part = γ
      -- a_small: monomials of a with s-part < γ (componentwise)
      -- b_out: monomials of b entirely outside s
      set a_γ : MvPolynomial σ R := a.support.sum fun d =>
        if d.filter (· ∈ s) = γ then monomial d (coeff d a) else 0
      set a_small : MvPolynomial σ R := a.support.sum fun d =>
        if d.filter (· ∈ s) < γ then monomial d (coeff d a) else 0
      set b_out : MvPolynomial σ R := b.support.sum fun d =>
        if d.filter (· ∈ s) = 0 then monomial d (coeff d b) else 0
      -- a_small ∈ I (by minimality, each contributing monomial is in I)
      have ha_small_I : a_small ∈ I := by
        apply Submodule.sum_mem
        intro d hd
        split_ifs with h
        · have := hsmall_in_I d hd h
          rw [show monomial d (coeff d a) = C (coeff d a) * monomial d 1 from
            by rw [C_mul_monomial, mul_one]]
          exact I.mul_mem_left _ this
        · exact I.zero_mem
      -- a_γ ≠ 0 (contains d₁)
      have ha_γ_ne : a_γ ≠ 0 := by
        intro h
        have : coeff d₁ a_γ = 0 := by rw [h]; simp
        rw [coeff_filtered_sum, if_pos ⟨hd₁_eq, hd₁_supp⟩] at this
        exact MvPolynomial.mem_support_iff.mp hd₁_supp this
      -- b_out ≠ 0 (contains e₀)
      have he₀_filt : e₀.filter (· ∈ s) = 0 := by
        ext i; simp only [Finsupp.filter_apply, Finsupp.zero_apply]
        split_ifs with hi
        · exact he₀_s i hi
        · rfl
      have hb_out_ne : b_out ≠ 0 := by
        intro h
        have : coeff e₀ b_out = 0 := by rw [h]; simp
        rw [coeff_filtered_sum, if_pos ⟨he₀_filt, he₀_supp⟩] at this
        exact MvPolynomial.mem_support_iff.mp he₀_supp this
      -- Show a_γ * b_out = 0 (contradiction with domain since both ≠ 0)
      -- Strategy: show every coefficient of a_γ * b_out is zero
      suffices h_zero : a_γ * b_out = 0 from
        absurd h_zero (mul_ne_zero ha_γ_ne hb_out_ne)
      ext f
      simp only [coeff_zero]
      -- Show coeff f (a_γ * b_out) = 0
      -- Case 1: f.filter (· ∈ s) ≠ γ
      -- Every contributing pair (u,v) to a_γ * b_out has u_s = γ and v_s = 0,
      -- so f_s = γ. If f_s ≠ γ, no pair contributes.
      -- Case 2: f.filter (· ∈ s) = γ
      -- coeff f (a_γ * b_out) = coeff f (a*b - a_small*b) - coeff f (R)
      -- where R = a*b - a_small*b - a_γ*b_out has no γ-slice contribution.
      -- And a*b - a_small*b ∈ I, so its γ-slice coefficients are 0.
      -- We prove: coeff f (a_γ * b_out) = coeff f (a*b) - coeff f (a_small * b)
      -- by showing the remaining terms contribute 0 at f_s = γ.
      -- Combined proof: coeff f (a_γ * b_out) = coeff f (a*b - a_small * b)
      -- for f with f_s = γ; and coeff f (a*b - a_small * b) = 0 since p ∈ I is monomial.
      -- For f with f_s ≠ γ: the sum over antidiagonal is directly 0.
      -- Coefficient-level argument: show ∀ f, coeff f (a_γ * b_out) = 0
      -- For (u,v) in antidiag f with coeff u a_γ ≠ 0 and coeff v b_out ≠ 0:
      --   u_s = γ and v_s = 0, hence f_s = γ and monomial f 1 ∉ I.
      -- Then coeff f (a*b) = coeff f (a_small*b) + coeff f (a_γ*b_out) (pairwise).
      -- Since a*b - a_small*b ∈ I and monomial f 1 ∉ I: coeff f (a*b - a_small*b) = 0.
      -- Hence coeff f (a_γ * b_out) = 0.
      -- Split into two cases based on f_s = γ or not.
      rw [MvPolynomial.coeff_mul]
      simp only [a_γ, b_out]
      simp_rw [coeff_filtered_sum]
      -- Case 1: f_s ≠ γ → every antidiag summand is 0
      -- Case 2: f_s = γ → relate to coeff f (a*b - a_small*b) = 0
      by_cases hf_eq : f.filter (· ∈ s) = γ; swap
      · -- f_s ≠ γ: every summand is 0
        apply Finset.sum_eq_zero
        intro ⟨u', v'⟩ huv'
        rw [Finset.mem_antidiagonal] at huv'
        -- If either condition in the `if` fails, the product is 0
        by_cases h₁ : u'.filter (· ∈ s) = γ ∧ u' ∈ a.support <;>
          by_cases h₂ : v'.filter (· ∈ s) = 0 ∧ v' ∈ b.support
        · -- Both conditions hold → f_s = γ, contradiction
          obtain ⟨hu'_eq, _⟩ := h₁
          obtain ⟨hv'_zero, _⟩ := h₂
          have hv'_s : ∀ i ∈ s, v' i = 0 := by
            intro i hi
            have := congr_fun (congr_arg DFunLike.coe hv'_zero) i
            simp only [Finsupp.filter_apply, if_pos hi, Finsupp.zero_apply] at this
            exact this
          exact absurd (show f.filter (· ∈ s) = γ by
            rw [← huv', filter_add_eq u' v' hv'_s, hu'_eq]) hf_eq
        · rw [if_pos h₁, if_neg h₂, mul_zero]
        · rw [if_neg h₁, zero_mul]
        · rw [if_neg h₁, zero_mul]
      · -- f_s = γ: show coeff f (a_γ * b_out) = 0
        have hf_nI : monomial f (1 : R) ∉ I := by
          rwa [monomial_mem_iff_filter hcrit f, hf_eq]
        have hab_sm_I : a * b - a_small * b ∈ I :=
          I.sub_mem hab (I.mul_mem_right b ha_small_I)
        have hcoeff_zero : coeff f (a * b - a_small * b) = 0 := by
          by_contra h
          exact hf_nI (hI _ hab_sm_I f (MvPolynomial.mem_support_iff.mpr h))
        -- The sum equals coeff f (a*b) - coeff f (a_small * b) = 0
        -- To show this, we prove the pairwise equality for (u',v') ∈ antidiag f.
        -- Key: since f_s = γ, for each (u',v'), u'_s + v'_s = γ, so u'_s ≤ γ.
        -- Either u'_s = γ (then v'_s = 0, a_small coeff = 0, matching) or
        -- u'_s < γ (then a_γ coeff = 0, a_small coeff = coeff u' a, matching).
        -- First show: sum = coeff f (a*b) - coeff f (a_small*b)
        suffices hrel : ∑ x ∈ Finset.antidiagonal f,
            (if x.1.filter (· ∈ s) = γ ∧ x.1 ∈ a.support then coeff x.1 a else 0) *
            (if x.2.filter (· ∈ s) = 0 ∧ x.2 ∈ b.support then coeff x.2 b else 0) =
            coeff f (a * b) - coeff f (a_small * b) by
          rw [hrel, ← MvPolynomial.coeff_sub]; exact hcoeff_zero
        rw [MvPolynomial.coeff_mul]
        conv_rhs => rw [MvPolynomial.coeff_mul]
        simp only [a_small]; simp_rw [coeff_filtered_sum]
        rw [← Finset.sum_sub_distrib]
        apply Finset.sum_congr rfl
        intro ⟨u', v'⟩ huv'
        rw [Finset.mem_antidiagonal] at huv'
        have hu'_le : u'.filter (· ∈ s) ≤ γ :=
          filter_le_of_add_filter_eq (huv' ▸ hf_eq)
        by_cases hu'_eq : u'.filter (· ∈ s) = γ
        · -- u'_s = γ
          have hv'_filt : v'.filter (· ∈ s) = 0 := by
            have h := huv' ▸ hf_eq; rw [Finsupp.filter_add] at h; ext i
            have hi := congr_fun (congr_arg DFunLike.coe h) i
            have hj := congr_fun (congr_arg DFunLike.coe hu'_eq) i
            simp only [Finsupp.add_apply, Finsupp.zero_apply] at hi hj ⊢; omega
          have hlt_neg : ¬(u'.filter (· ∈ s) < γ) := by rw [hu'_eq]; exact lt_irrefl _
          by_cases hu_supp : u' ∈ a.support <;> by_cases hv_supp : v' ∈ b.support
          · rw [if_pos ⟨hu'_eq, hu_supp⟩, if_pos ⟨hv'_filt, hv_supp⟩,
                if_neg (not_and_of_not_left _ hlt_neg), zero_mul, sub_zero]
          · simp [MvPolynomial.notMem_support_iff.mp hv_supp, hv_supp]
          · simp [MvPolynomial.notMem_support_iff.mp hu_supp, hu_supp]
          · simp [MvPolynomial.notMem_support_iff.mp hu_supp, hu_supp]
        · -- u'_s < γ
          have hu'_lt := lt_of_le_of_ne hu'_le hu'_eq
          rw [if_neg (not_and_of_not_left _ hu'_eq)]
          by_cases hu_supp : u' ∈ a.support
          · simp only [zero_mul]
            split_ifs with h
            · ring
            · exact absurd ⟨hu'_lt, hu_supp⟩ h
          · simp [MvPolynomial.notMem_support_iff.mp hu_supp, hu_supp]
  · -- b ∈ span(X '' s) = I.radical
    exact Or.inr (hrad ▸ hb_s)

/-- A monomial ideal in `MvPolynomial σ R` (with `R` a domain) is primary if and
only if its radical is generated by a set of variables and the monomial
non-zero-divisor criterion holds outside that set. -/
theorem IsMonomial.isPrimary_iff
    {I : Ideal (MvPolynomial σ R)} (hI : I.IsMonomial) (hne : I ≠ ⊤) :
    I.IsPrimary ↔
      ∃ s : Set σ,
        I.radical = span (MvPolynomial.X '' s) ∧
        ∀ d : σ →₀ ℕ, MvPolynomial.monomial d (1 : R) ∉ I →
          ∀ i, i ∉ s →
            MvPolynomial.monomial (d + Finsupp.single i 1) (1 : R) ∉ I := by
  constructor
  · exact hI.isPrimary_radical_eq_span_X
  · rintro ⟨s, hrad, hcrit⟩
    exact hI.isPrimary_of_criterion hne hrad hcrit

end Ideal

end PrimaryConverse

end
