/-
Copyright (c) 2026 Thomas Kahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Kahle
-/
import toMathlib.MonomialIdeal
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic

/-!
# Minimal primes of variable-pair ideals and vertex covers

Given a set `edges` of pairs of variable indices `(a, b)`, the *variable-pair ideal*
is `⟨X a * X b : (a, b) ∈ edges⟩`.  When the pairs come from a graph this is the
classical *edge ideal* (also called the *Stanley–Reisner ideal of the complement*).

## Main results

* `MvPolynomial.variablePairIdeal_le_span_X_iff`:
  `variablePairIdeal edges ≤ span (X '' S)` if and only if `S` is a vertex cover of `edges`.
* `MvPolynomial.X_mem_span_X_image_iff`:
  `X i ∈ span (X '' S)` if and only if `i ∈ S` (over a nontrivial commutative semiring).
* `MvPolynomial.minimalPrime_variablePairIdeal_iff`:
  `P ∈ Ideal.minimalPrimes (variablePairIdeal edges)` if and only if
  `P = span (X '' S)` for a minimal vertex cover `S`.

## Tags

edge ideal, monomial ideal, vertex cover, minimal prime
-/

noncomputable section

open MvPolynomial Ideal

variable {R : Type*} [CommRing R] [IsDomain R] {σ : Type*}

namespace MvPolynomial

/-! ### Variable-pair ideal and vertex covers -/

/-- The *variable-pair ideal* (edge ideal) of a set of variable pairs:
the ideal generated by products `X a * X b` for each `(a, b) ∈ edges`. -/
def variablePairIdeal (edges : Set (σ × σ)) : Ideal (MvPolynomial σ R) :=
  span { m : MvPolynomial σ R | ∃ a b, (a, b) ∈ edges ∧ m = X a * X b }

/-- A set `S` of variable indices is a *vertex cover* of `edges` if every edge
has at least one endpoint in `S`. -/
def IsVertexCover (edges : Set (σ × σ)) (S : Set σ) : Prop :=
  ∀ a b, (a, b) ∈ edges → a ∈ S ∨ b ∈ S

/-- A vertex cover is *minimal* if no proper subset is also a vertex cover. -/
def IsMinimalVertexCover (edges : Set (σ × σ)) (S : Set σ) : Prop :=
  IsVertexCover edges S ∧ ∀ T : Set σ, IsVertexCover edges T → T ⊆ S → S ⊆ T

/-! ### Key lemma: membership of `X i` in `span (X '' S)` -/

omit [IsDomain R] in
/-- `X i ∈ span (X '' S)` if and only if `i ∈ S`, over a nontrivial commutative semiring. -/
theorem X_mem_span_X_image_iff [Nontrivial R] {S : Set σ} {i : σ} :
    X i ∈ span (X '' S : Set (MvPolynomial σ R)) ↔ i ∈ S := by
  constructor
  · intro h
    rw [mem_ideal_span_X_image] at h
    obtain ⟨j, hj, hjne⟩ := h (Finsupp.single i 1) (by simp [support_X])
    have : j = i := by
      by_contra hne; apply hjne; simp [hne]
    exact this ▸ hj
  · exact fun hi => subset_span ⟨i, hi, rfl⟩

/-! ### Containment ↔ vertex cover -/

/-- `variablePairIdeal edges ≤ span (X '' S)` if and only if `S` is a vertex cover. -/
theorem variablePairIdeal_le_span_X_iff {edges : Set (σ × σ)} {S : Set σ} :
    variablePairIdeal (R := R) edges ≤ span (X '' S) ↔ IsVertexCover edges S := by
  constructor
  · intro hle a b hab
    have hgen : X a * X b ∈ variablePairIdeal (R := R) edges :=
      subset_span ⟨a, b, hab, rfl⟩
    have hmem := hle hgen
    have hprime := isPrime_span_X_image_set (R := R) S
    rcases hprime.mem_or_mem hmem with ha | hb
    · left; exact X_mem_span_X_image_iff.mp ha
    · right; exact X_mem_span_X_image_iff.mp hb
  · intro hcover
    change variablePairIdeal edges ≤ span (X '' S)
    unfold variablePairIdeal
    rw [span_le]
    rintro _ ⟨a, b, hab, rfl⟩
    rcases hcover a b hab with ha | hb
    · exact mul_mem_right _ _ (subset_span ⟨a, ha, rfl⟩)
    · exact mul_mem_left _ _ (subset_span ⟨b, hb, rfl⟩)

/-! ### Minimal primes ↔ minimal vertex covers -/

omit [IsDomain R] in
/-- Every prime containing the variable-pair ideal arises from a vertex cover:
there is a vertex cover `S ⊆ {i | X i ∈ P}` such that `span (X '' S) ≤ P`. -/
private theorem vertexCover_of_prime_ge {edges : Set (σ × σ)}
    {P : Ideal (MvPolynomial σ R)} (hP : P.IsPrime)
    (hle : variablePairIdeal edges ≤ P) :
    IsVertexCover edges {i | X i ∈ P} ∧ span (X '' {i : σ | X i ∈ P}) ≤ P := by
  refine ⟨fun a b hab => ?_, ?_⟩
  · have hgen : X a * X b ∈ variablePairIdeal (R := R) edges :=
      subset_span ⟨a, b, hab, rfl⟩
    exact hP.mem_or_mem (hle hgen)
  · rw [span_le]; rintro _ ⟨i, hi, rfl⟩; exact hi

/-- A minimal prime of the variable-pair ideal is `span (X '' S)` for some
minimal vertex cover `S`. -/
theorem minimalPrime_variablePairIdeal_eq_span
    {edges : Set (σ × σ)}
    {P : Ideal (MvPolynomial σ R)}
    (hP : P ∈ Ideal.minimalPrimes (variablePairIdeal edges)) :
    ∃ S : Set σ, IsMinimalVertexCover edges S ∧ P = span (X '' S) := by
  obtain ⟨⟨hPprime, hPge⟩, hPmin⟩ := hP
  set S := {i : σ | X i ∈ P}
  obtain ⟨hcover, hspan_le⟩ := vertexCover_of_prime_ge hPprime hPge
  -- span(X '' S) is prime, contains the pair ideal, and ≤ P
  have hS_prime : (span (X '' S : Set (MvPolynomial σ R))).IsPrime :=
    isPrime_span_X_image_set S
  have hS_ge : variablePairIdeal (R := R) edges ≤ span (X '' S) :=
    variablePairIdeal_le_span_X_iff.mpr hcover
  -- By minimality, P ≤ span(X '' S)
  have hP_le : P ≤ span (X '' S : Set (MvPolynomial σ R)) :=
    hPmin ⟨hS_prime, hS_ge⟩ hspan_le
  -- So P = span(X '' S)
  have hP_eq : P = span (X '' S : Set (MvPolynomial σ R)) := le_antisymm hP_le hspan_le
  -- S is a minimal vertex cover
  refine ⟨S, ⟨hcover, fun T hT hTS => ?_⟩, hP_eq⟩
  -- T ⊆ S is a vertex cover, so span(X '' T) contains the pair ideal
  have hT_ge : variablePairIdeal (R := R) edges ≤ span (X '' T) :=
    variablePairIdeal_le_span_X_iff.mpr hT
  have hT_prime : (span (X '' T : Set (MvPolynomial σ R))).IsPrime :=
    isPrime_span_X_image_set T
  have hT_le_S : span (X '' T : Set (MvPolynomial σ R)) ≤ span (X '' S) :=
    span_mono (Set.image_mono hTS)
  -- By minimality (via hP_eq), span(X '' S) ≤ span(X '' T)
  have hS_le_T : span (X '' S : Set (MvPolynomial σ R)) ≤ span (X '' T) := by
    rw [← hP_eq]
    exact hPmin ⟨hT_prime, hT_ge⟩ (hT_le_S.trans (hP_eq ▸ le_refl _))
  -- So span(X '' S) = span(X '' T), which gives S ⊆ T
  intro i hi
  have : X i ∈ span (X '' S : Set (MvPolynomial σ R)) := subset_span ⟨i, hi, rfl⟩
  exact X_mem_span_X_image_iff.mp (hS_le_T this)

/-- `span (X '' S)` for a minimal vertex cover `S` is a minimal prime of the
variable-pair ideal. -/
theorem span_minimalVertexCover_minimalPrime
    {edges : Set (σ × σ)} {S : Set σ}
    (hS : IsMinimalVertexCover edges S) :
    span (X '' S : Set (MvPolynomial σ R)) ∈ Ideal.minimalPrimes (variablePairIdeal edges) := by
  refine ⟨⟨isPrime_span_X_image_set S,
    variablePairIdeal_le_span_X_iff.mpr hS.1⟩, fun Q ⟨hQp, hQge⟩ hQle => ?_⟩
  -- Q is prime, Q ⊇ pair ideal, Q ≤ span(X '' S). Show span(X '' S) ≤ Q.
  -- Define T = {i | X i ∈ Q}
  set T := {i : σ | X i ∈ Q}
  obtain ⟨hTcover, hspan_T_le⟩ := vertexCover_of_prime_ge hQp hQge
  -- T ⊆ S because Q ≤ span(X '' S)
  have hTS : T ⊆ S := fun i (hi : X i ∈ Q) =>
    X_mem_span_X_image_iff.mp (hQle hi)
  -- By minimality of S, S ⊆ T
  have hST : S ⊆ T := hS.2 T hTcover hTS
  -- So X i ∈ Q for all i ∈ S
  intro p hp
  have hpT : p ∈ span (X '' T : Set (MvPolynomial σ R)) :=
    span_mono (Set.image_mono hST) hp
  exact hspan_T_le hpT

/-- The minimal primes of `variablePairIdeal edges` are exactly the ideals
`span (X '' S)` for minimal vertex covers `S`. -/
theorem minimalPrime_variablePairIdeal_iff
    {edges : Set (σ × σ)}
    {P : Ideal (MvPolynomial σ R)} :
    P ∈ Ideal.minimalPrimes (variablePairIdeal edges) ↔
      ∃ S : Set σ, IsMinimalVertexCover edges S ∧ P = span (X '' S) := by
  constructor
  · exact minimalPrime_variablePairIdeal_eq_span
  · rintro ⟨S, hS, rfl⟩
    exact span_minimalVertexCover_minimalPrime hS

end MvPolynomial

end

