title: BEI Formalization
description: Lean formalization of Herzog et al. (2010)
theme: minima
markdown: kramdown
kramdown:
  math_engine:
header_pages:
  - overview.md
  - foundations.md
  - toMathlib.md
  - section-1.md
  - section-2.md
  - section-3.md
  - section-4.md
  - about.md
